# 05 — Extract emotion2vec utterance-level features

Revised version for IJAE revision.

Main changes:
- uses the new `newcode` project folder;
- uses `iic/emotion2vec_plus_base` consistently;
- saves checkpoint SHA256 and environment manifest;
- validates that extracted embeddings are 768-dimensional;
- saves crop/padding duration statistics;
- saves SHA256 manifest for generated feature files.

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
# Clean compatible PyTorch stack for Colab
# Run this once after a fresh runtime, then restart runtime if Colab asks.

!pip -q uninstall -y torch torchvision torchaudio cuda-python cuda-bindings cuda-toolkit nvidia-cublas-cu13 nvidia-cuda-runtime-cu13 nvidia-cudnn-cu13

!pip -q install torch==2.11.0 torchvision==0.26.0 torchaudio==2.11.0 --index-url https://download.pytorch.org/whl/cu128

!pip -q install "jedi>=0.16"
!pip -q install "pandas==2.2.2" "numpy<2.1" "scikit-learn" "librosa==0.11.0" "soundfile" "tqdm"
!pip -q install "funasr==1.4.1" "modelscope==1.39.1" --upgrade-strategy only-if-needed

WARNING: Skipping nvidia-cublas-cu13 as it is not installed.
WARNING: Skipping nvidia-cuda-runtime-cu13 as it is not installed.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 820.3/820.3 MB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 142.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 90.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.3/188.3 MB 13.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 148.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 80.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 26.2.1 requires cuda-python<13.0,>=12.9.2, which is not installed.
pylibraft-cu12 26.2.0 requires cuda-python<13.0,>=12.9.2, which is not installed.
cuml-cu12 26.2.0 requires cuda-python<13.0,>=12.9.2, which is not installed.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 147.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 26.2.1 requires cuda-python<13.0,>=12.9.2, which is not installed.
cuml-cu12 26.2.0 requires cuda-python<13.0,>=12.9.2, which is not installed.

In [3]:
import os
import json
import random
import warnings
import hashlib
import platform
import datetime
import importlib.metadata as im

import numpy as np
import pandas as pd
import librosa
import soundfile as sf

from pathlib import Path
from tqdm import tqdm
from collections import Counter

warnings.filterwarnings("ignore")

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

# ============================================================
# IMPORTANT:
# Use the original project folder requested by the user.
# ============================================================
BASE_PROJECT = Path("/content/drive/MyDrive/New Jurnal Cross")

CSV_DIR = BASE_PROJECT / "processed_intra_csv"

# Use a folder name that matches the actual checkpoint.
# If you use iic/emotion2vec_plus_base, keep this as e2v_plus_base.
OUT_DIR = BASE_PROJECT / "processed_intra_features_e2v_plus_base"
TMP_AUDIO_DIR = BASE_PROJECT / "tmp_e2v_16k_audio_plus_base"

OUT_DIR.mkdir(parents=True, exist_ok=True)
TMP_AUDIO_DIR.mkdir(parents=True, exist_ok=True)

DATASETS = ["emodb", "ravdess", "resd"]

CSV_FILES = {
    "emodb": CSV_DIR / "split_emodb_6class_optimized.csv",
    "ravdess": CSV_DIR / "split_ravdess_6class_optimized.csv",
    "resd": CSV_DIR / "split_resd_6class_optimized.csv",
}

LABELS = [
    "angry",
    "disgust",
    "fear",
    "happy",
    "neutral",
    "sad",
]

LABEL_TO_ID = {label: i for i, label in enumerate(LABELS)}
ID_TO_LABEL = {i: label for label, i in LABEL_TO_ID.items()}

CONFIG = {
    "sample_rate": 16000,
    "duration": 4.0,
    "model_name": "iic/emotion2vec_plus_base",
    "granularity": "utterance",
    "extract_embedding": True,
    "expected_embedding_dim": 768,
    "labels": LABELS,
    "preprocessing": {
        "mono": True,
        "resample_hz": 16000,
        "fixed_duration_sec": 4.0,
        "longer_utterances": "center-cropped",
        "shorter_utterances": "reflect-padded if length > 1 sample, otherwise zero-padded",
        "augmentation": "none",
        "scaler": "none at feature extraction stage",
    },
}

print("BASE_PROJECT :", BASE_PROJECT)
print("CSV_DIR      :", CSV_DIR)
print("OUT_DIR      :", OUT_DIR)
print("TMP_AUDIO_DIR:", TMP_AUDIO_DIR)
print("Model        :", CONFIG["model_name"])

missing = []
for ds, path in CSV_FILES.items():
    print(f"{ds:8s}", path.exists(), path)
    if not path.exists():
        missing.append(str(path))

if missing:
    raise FileNotFoundError("Missing CSV files:\n" + "\n".join(missing))

BASE_PROJECT : /content/drive/MyDrive/New Jurnal Cross
CSV_DIR      : /content/drive/MyDrive/New Jurnal Cross/processed_intra_csv
OUT_DIR      : /content/drive/MyDrive/New Jurnal Cross/processed_intra_features_e2v_plus_base
TMP_AUDIO_DIR: /content/drive/MyDrive/New Jurnal Cross/tmp_e2v_16k_audio_plus_base
Model        : iic/emotion2vec_plus_base
emodb    True /content/drive/MyDrive/New Jurnal Cross/processed_intra_csv/split_emodb_6class_optimized.csv
ravdess  True /content/drive/MyDrive/New Jurnal Cross/processed_intra_csv/split_ravdess_6class_optimized.csv
resd     True /content/drive/MyDrive/New Jurnal Cross/processed_intra_csv/split_resd_6class_optimized.csv

In [4]:
from funasr import AutoModel

e2v_model = AutoModel(
    model=CONFIG["model_name"],
    trust_remote_code=True,
    device="cuda:0",      # change to "cpu" if GPU is unavailable
    disable_update=True   # important for reproducibility
)

print("Loaded model:", CONFIG["model_name"])

funasr version: 1.4.1.

2026-08-08 09:45:16,150 | INFO    | modelscope_hub.download | Downloading 11 files from iic/emotion2vec_plus_base@master

Downloading:   0%|          | 0/11 [00:00<?, ?file/s]

.gitattributes:   0%|          | 0.00/1.51k [00:00<?, ?B/s]

.DS_Store:   0%|          | 0.00/6.15k [00:00<?, ?B/s]

config.yaml:   0%|          | 0.00/3.17k [00:00<?, ?B/s]

emotion2vec+data.png:   0%|          | 0.00/274k [00:00<?, ?B/s]

emotion2vec+radar.png:   0%|          | 0.00/682k [00:00<?, ?B/s]

logo.png:   0%|          | 0.00/1.85M [00:00<?, ?B/s]

configuration.json:   0%|          | 0.00/343 [00:00<?, ?B/s]

model.pt:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

README.md:   0%|          | 0.00/6.15k [00:00<?, ?B/s]

test.wav:   0%|          | 0.00/131k [00:00<?, ?B/s]

tokens.txt:   0%|          | 0.00/120 [00:00<?, ?B/s]

WARNING:root:trust_remote_code: True

Loading remote code failed: model, No module named 'model'
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.0.0.weight, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.0.0.bias, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.1.0.weight, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.1.0.bias, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.2.0.weight, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.2.0.bias, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.3.0.weight, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.3.0.bias, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.proj.weight, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.proj.bias, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Loaded model: iic/emotion2vec_plus_base

In [5]:
def pkg_ver(package_name):
    try:
        return im.version(package_name)
    except Exception:
        return "not installed"


def sha256_of_file(path, chunk_size=1024 * 1024):
    path = Path(path)
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(chunk_size), b""):
            h.update(chunk)
    return h.hexdigest()


def find_modelscope_checkpoint(model_id):
    """
    Cari checkpoint ModelScope/FunASR secara robust.
    Untuk iic/emotion2vec_plus_base, biasanya file checkpoint adalah model.pt.
    """
    org, name = model_id.split("/", 1)

    candidate_roots = [
        Path.home() / ".cache" / "modelscope" / "hub" / "models" / org / name,
        Path("/root/.cache/modelscope/hub/models") / org / name,
        Path.home() / ".cache" / "modelscope" / "hub" / org / name,
        Path("/root/.cache/modelscope/hub") / org / name,
        Path.home() / ".cache" / "modelscope" / "models" / f"{org}--{name}",
        Path("/root/.cache/modelscope/models") / f"{org}--{name}",
    ]

    exts = [".pt", ".pth", ".bin", ".safetensors"]
    candidates = []

    for root in candidate_roots:
        if root.exists():
            for ext in exts:
                candidates.extend(root.rglob(f"*{ext}"))

    candidates = sorted(
        list({p.resolve() for p in candidates if p.is_file()}),
        key=lambda p: p.stat().st_size,
        reverse=True
    )

    if len(candidates) == 0:
        return None, []

    return candidates[0], candidates


checkpoint_path, checkpoint_candidates = find_modelscope_checkpoint(CONFIG["model_name"])

checkpoint_info = []
for p in checkpoint_candidates:
    checkpoint_info.append({
        "path": str(p),
        "name": p.name,
        "size_bytes": p.stat().st_size,
        "sha256": sha256_of_file(p),
    })

primary_checkpoint = checkpoint_info[0] if checkpoint_info else None

environment_manifest = {
    "notebook": "05_extract_emotion2vec_intra.ipynb",
    "task": "emotion2vec utterance-level feature extraction",
    "created_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(),
    "base_project": str(BASE_PROJECT),
    "csv_dir": str(CSV_DIR),
    "out_dir": str(OUT_DIR),
    "tmp_audio_dir": str(TMP_AUDIO_DIR),

    "model_id": CONFIG["model_name"],
    "granularity": CONFIG["granularity"],
    "extract_embedding": CONFIG["extract_embedding"],
    "expected_embedding_dim": CONFIG["expected_embedding_dim"],

    "checkpoint_path": str(checkpoint_path) if checkpoint_path is not None else None,
    "checkpoint_size_mb": round(checkpoint_path.stat().st_size / (1024 ** 2), 2) if checkpoint_path is not None else None,
    "checkpoint_sha256": sha256_of_file(checkpoint_path) if checkpoint_path is not None else None,
    "all_checkpoint_candidates": checkpoint_info,

    "config": CONFIG,
    "python_version": platform.python_version(),
    "platform": platform.platform(),
    "funasr_version": pkg_ver("funasr"),
    "modelscope_version": pkg_ver("modelscope"),
    "torch_version": pkg_ver("torch"),
    "torchaudio_version": pkg_ver("torchaudio"),
    "librosa_version": pkg_ver("librosa"),
    "soundfile_version": pkg_ver("soundfile"),
    "numpy_version": pkg_ver("numpy"),
    "pandas_version": pkg_ver("pandas"),
    "scikit_learn_version": pkg_ver("scikit-learn"),
}

with open(OUT_DIR / "environment_manifest.json", "w") as f:
    json.dump(environment_manifest, f, indent=2)

print("=" * 80)
print("EMOTION2VEC REPRODUCIBILITY MANIFEST")
print("=" * 80)
print("Model ID          :", environment_manifest["model_id"])
print("Checkpoint path   :", environment_manifest["checkpoint_path"])
print("Checkpoint SHA256 :", environment_manifest["checkpoint_sha256"])
print("Checkpoint size   :", environment_manifest["checkpoint_size_mb"], "MB")
print("FunASR version    :", environment_manifest["funasr_version"])
print("ModelScope ver.   :", environment_manifest["modelscope_version"])
print("Torch version     :", environment_manifest["torch_version"])
print("Saved manifest    :", OUT_DIR / "environment_manifest.json")

if primary_checkpoint is None:
    print("\nWARNING: No checkpoint file was found in the expected ModelScope cache.")

================================================================================
EMOTION2VEC REPRODUCIBILITY MANIFEST
================================================================================
Model ID          : iic/emotion2vec_plus_base
Checkpoint path   : /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Checkpoint SHA256 : 60710b5aae1dbe69bdac8920028fb05882d4314fd09031922b4b61ee9e7aadbd
Checkpoint size   : 1066.44 MB
FunASR version    : 1.4.1
ModelScope ver.   : 1.39.1
Torch version     : 2.11.0+cu128
Saved manifest    : /content/drive/MyDrive/New Jurnal Cross/processed_intra_features_e2v_plus_base/environment_manifest.json

In [6]:
def load_audio_fixed(path, sr=16000, duration=4.0, return_info=False):
    """
    Load audio as mono 16 kHz and convert it to fixed duration.
    Longer utterances are center-cropped.
    Shorter utterances are reflect-padded.

    If return_info=True, also return crop/padding metadata for reviewer analysis.
    """
    path = str(path)
    audio, _ = librosa.load(path, sr=sr, mono=True)

    original_len = int(len(audio))
    target_len = int(sr * duration)

    info = {
        "original_n_samples": original_len,
        "target_n_samples": target_len,
        "original_duration_sec": float(original_len / sr),
        "target_duration_sec": float(duration),
        "was_cropped": False,
        "was_padded": False,
        "crop_start_sample": 0,
        "crop_end_sample": original_len,
        "cropped_samples": 0,
        "padded_samples": 0,
        "cropped_seconds": 0.0,
        "padded_seconds": 0.0,
        "padding_mode": "none",
    }

    if original_len >= target_len:
        start = (original_len - target_len) // 2
        end = start + target_len
        audio = audio[start:end]

        info["was_cropped"] = bool(original_len > target_len)
        info["crop_start_sample"] = int(start)
        info["crop_end_sample"] = int(end)
        info["cropped_samples"] = int(max(0, original_len - target_len))
        info["cropped_seconds"] = float(max(0, original_len - target_len) / sr)
    else:
        pad_len = target_len - original_len
        if original_len > 1:
            audio = np.pad(audio, (0, pad_len), mode="reflect")
            padding_mode = "reflect"
        else:
            audio = np.pad(audio, (0, pad_len), mode="constant")
            padding_mode = "constant"

        info["was_padded"] = True
        info["padded_samples"] = int(pad_len)
        info["padded_seconds"] = float(pad_len / sr)
        info["padding_mode"] = padding_mode

    audio = audio.astype(np.float32)

    if return_info:
        return audio, info
    return audio

In [7]:
def parse_e2v_output(res):
    """
    Parse FunASR emotion2vec output robustly.

    We explicitly prioritize embedding-like keys. Classification scores are
    not accepted as embeddings unless no other option exists, and the final
    dimensionality check will stop the pipeline if a non-768 vector is returned.
    """
    if isinstance(res, list):
        item = res[0]
    else:
        item = res

    # Prefer embedding-like keys.
    possible_embedding_keys = [
        "feats",
        "feature",
        "embedding",
        "embeddings",
    ]

    if isinstance(item, dict):
        for key in possible_embedding_keys:
            if key in item:
                return np.asarray(item[key], dtype=np.float32)

        # Fallback: find the largest numeric array-like object, but avoid
        # obvious classification-score keys if possible.
        candidates = []
        for k, v in item.items():
            if str(k).lower() in ["scores", "score", "labels", "label"]:
                continue
            try:
                arr = np.asarray(v, dtype=np.float32)
                if arr.ndim >= 1 and arr.size > 10:
                    candidates.append((k, arr))
            except Exception:
                pass

        if len(candidates) > 0:
            candidates = sorted(candidates, key=lambda x: x[1].size, reverse=True)
            print(f"Fallback selected output key: {candidates[0][0]}")
            return candidates[0][1]

    raise ValueError(
        f"Cannot parse emotion2vec embedding output. "
        f"Available keys: {list(item.keys()) if isinstance(item, dict) else type(item)}"
    )


def extract_e2v_embedding_from_audio(audio, uid, tmp_dir, sr=16000):
    """Save temporary WAV and extract an utterance-level emotion2vec embedding."""
    tmp_path = tmp_dir / f"{uid}.wav"
    sf.write(tmp_path, audio, sr)

    res = e2v_model.generate(
        input=str(tmp_path),
        granularity=CONFIG["granularity"],
        extract_embedding=CONFIG["extract_embedding"],
    )

    emb = parse_e2v_output(res)
    emb = np.asarray(emb, dtype=np.float32)

    # Utterance output may be [D] or [1, D].
    # If frame-level output appears, mean-pool over time as a conservative fallback.
    if emb.ndim == 1:
        out = emb
    elif emb.ndim == 2:
        if emb.shape[0] == 1:
            out = emb[0]
        else:
            out = emb.mean(axis=0)
    elif emb.ndim == 3:
        out = emb.reshape(-1, emb.shape[-1]).mean(axis=0)
    else:
        out = emb.reshape(-1)

    out = np.nan_to_num(out, nan=0.0, posinf=0.0, neginf=0.0).astype(np.float32)

    expected_dim = int(CONFIG["expected_embedding_dim"])
    if out.shape[0] != expected_dim:
        raise ValueError(
            f"Unexpected emotion2vec embedding dimension: got {out.shape[0]}, "
            f"expected {expected_dim}. This usually means the parser selected "
            f"classification scores instead of embeddings, or the model/config changed."
        )

    return out

In [8]:
# Smoke test on one EmoDB row before processing all files.
test_df = pd.read_csv(CSV_FILES["emodb"])
test_row = test_df.iloc[0]

audio, audio_info = load_audio_fixed(
    test_row["filepath"],
    sr=CONFIG["sample_rate"],
    duration=CONFIG["duration"],
    return_info=True,
)

emb = extract_e2v_embedding_from_audio(
    audio=audio,
    uid="test_e2v",
    tmp_dir=TMP_AUDIO_DIR,
    sr=CONFIG["sample_rate"],
)

print("Embedding shape:", emb.shape)
print("First 10 values:", emb[:10])
print("NaN:", np.isnan(emb).any())
print("Audio info:", audio_info)

if emb.shape[0] != CONFIG["expected_embedding_dim"]:
    raise RuntimeError("Smoke test failed: unexpected embedding dimension.")

rtf_avg: 0.364: 100%|██████████| 1/1 [00:01<00:00,  1.46s/it]

Embedding shape: (768,)
First 10 values: [-0.38277912  0.90200233 -0.15388812 -1.0022807  -0.18847048  0.7996264
 -0.43421695  1.0762302  -0.36453864  0.1717488 ]
NaN: False
Audio info: {'original_n_samples': 31304, 'target_n_samples': 64000, 'original_duration_sec': 1.9565, 'target_duration_sec': 4.0, 'was_cropped': False, 'was_padded': True, 'crop_start_sample': 0, 'crop_end_sample': 31304, 'cropped_samples': 0, 'padded_samples': 32696, 'cropped_seconds': 0.0, 'padded_seconds': 2.0435, 'padding_mode': 'reflect'}

In [9]:
def safe_uid(uid):
    return str(uid).replace("/", "_").replace("\\", "_").replace(" ", "_").replace(":", "_")


def extract_split_e2v(df_split, dataset_name, split_name):
    X = []
    rows = []
    errors = []

    split_tmp_dir = TMP_AUDIO_DIR / dataset_name / split_name
    split_tmp_dir.mkdir(parents=True, exist_ok=True)

    for idx, row in tqdm(
        df_split.iterrows(),
        total=len(df_split),
        desc=f"{dataset_name} {split_name} e2v"
    ):
        try:
            audio, audio_info = load_audio_fixed(
                row["filepath"],
                sr=CONFIG["sample_rate"],
                duration=CONFIG["duration"],
                return_info=True,
            )

            uid = safe_uid(row["uid"])

            emb = extract_e2v_embedding_from_audio(
                audio=audio,
                uid=uid,
                tmp_dir=split_tmp_dir,
                sr=CONFIG["sample_rate"],
            )

            X.append(emb)

            new_row = row.to_dict()
            new_row["is_augmented"] = False
            new_row.update(audio_info)
            rows.append(new_row)

        except Exception as e:
            errors.append({
                "idx": idx,
                "uid": row.get("uid", ""),
                "filepath": row.get("filepath", ""),
                "error": str(e),
                "split": split_name,
                "dataset": dataset_name,
            })

    if len(X) == 0:
        raise RuntimeError(f"No valid embeddings for {dataset_name} {split_name}")

    dims = [x.shape[0] for x in X]
    if len(set(dims)) != 1:
        raise ValueError(f"Inconsistent embedding dims in {dataset_name} {split_name}: {Counter(dims)}")

    X = np.asarray(X, dtype=np.float32)
    meta = pd.DataFrame(rows)
    err = pd.DataFrame(errors)

    y = meta["emotion"].map(LABEL_TO_ID).values.astype(np.int64)

    return X, y, meta, err

In [10]:
def summarize_duration_crop_padding(meta_df, group_cols):
    numeric_cols = [
        "original_duration_sec",
        "was_cropped",
        "was_padded",
        "cropped_seconds",
        "padded_seconds",
    ]

    df = meta_df.copy()
    df["was_cropped"] = df["was_cropped"].astype(int)
    df["was_padded"] = df["was_padded"].astype(int)

    summary = (
        df.groupby(group_cols)
        .agg(
            n=("uid", "count"),
            duration_mean=("original_duration_sec", "mean"),
            duration_std=("original_duration_sec", "std"),
            duration_median=("original_duration_sec", "median"),
            duration_min=("original_duration_sec", "min"),
            duration_max=("original_duration_sec", "max"),
            cropped_n=("was_cropped", "sum"),
            padded_n=("was_padded", "sum"),
            cropped_pct=("was_cropped", lambda x: 100.0 * float(np.mean(x))),
            padded_pct=("was_padded", lambda x: 100.0 * float(np.mean(x))),
            cropped_seconds_mean=("cropped_seconds", "mean"),
            padded_seconds_mean=("padded_seconds", "mean"),
        )
        .reset_index()
    )
    return summary


def process_one_dataset_e2v(dataset_name, csv_path):
    print("=" * 90)
    print(f"Processing emotion2vec: {dataset_name.upper()}")
    print("=" * 90)

    out_ds = OUT_DIR / dataset_name
    out_ds.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(csv_path)
    df = df[df["emotion"].isin(LABELS)].copy()
    df["label"] = df["emotion"].map(LABEL_TO_ID).astype(int)

    print("Rows:", len(df))
    print("Speakers:", df["speaker"].nunique())
    print("\nDistribution:")
    display(df.groupby(["split", "emotion"]).size().unstack(fill_value=0))

    outputs = {}
    all_errors = []

    for split_name in ["train", "val", "test"]:
        df_split = df[df["split"] == split_name].reset_index(drop=True)

        X, y, meta, err = extract_split_e2v(
            df_split=df_split,
            dataset_name=dataset_name,
            split_name=split_name
        )

        outputs[split_name] = {
            "X": X,
            "y": y,
            "meta": meta,
            "err": err,
        }

        print(f"{split_name}: X={X.shape}, y={y.shape}, errors={len(err)}")

        np.save(out_ds / f"X_e2v_{split_name}.npy", X)
        np.save(out_ds / f"y_{split_name}.npy", y)
        meta.to_csv(out_ds / f"meta_{split_name}.csv", index=False)

        if len(err) > 0:
            all_errors.append(err)

    if len(all_errors) > 0:
        errors_df = pd.concat(all_errors, ignore_index=True)
    else:
        errors_df = pd.DataFrame(columns=["idx", "uid", "filepath", "error", "split", "dataset"])

    errors_df.to_csv(out_ds / "errors.csv", index=False)

    all_meta = pd.concat(
        [outputs[split_name]["meta"].assign(split=split_name) for split_name in ["train", "val", "test"]],
        ignore_index=True,
    )

    duration_stats_split_emotion = summarize_duration_crop_padding(
        all_meta,
        group_cols=["split", "emotion"],
    )
    duration_stats_emotion = summarize_duration_crop_padding(
        all_meta,
        group_cols=["emotion"],
    )
    duration_stats_overall = summarize_duration_crop_padding(
        all_meta.assign(all="all"),
        group_cols=["all"],
    )

    duration_stats_split_emotion.to_csv(out_ds / "duration_crop_padding_stats_by_split_emotion.csv", index=False)
    duration_stats_emotion.to_csv(out_ds / "duration_crop_padding_stats_by_emotion.csv", index=False)
    duration_stats_overall.to_csv(out_ds / "duration_crop_padding_stats_overall.csv", index=False)

    feature_config = {
        **CONFIG,
        "dataset": dataset_name,
        "embedding_dim": int(outputs["train"]["X"].shape[1]),
        "n_train": int(outputs["train"]["X"].shape[0]),
        "n_val": int(outputs["val"]["X"].shape[0]),
        "n_test": int(outputs["test"]["X"].shape[0]),
        "label_to_id": LABEL_TO_ID,
        "note": (
            "emotion2vec-plus-base utterance-level embeddings; no augmentation; "
            "no scaler applied at extraction stage; audio fixed to 4 seconds by "
            "center cropping or reflect padding."
        ),
    }

    with open(out_ds / "feature_config.json", "w") as f:
        json.dump(feature_config, f, indent=2)

    print("\nSaved:", out_ds)
    print("Embedding dim:", outputs["train"]["X"].shape[1])
    print("Errors:", len(errors_df))

    return {
        "dataset": dataset_name,
        "embedding_dim": outputs["train"]["X"].shape[1],
        "n_train": outputs["train"]["X"].shape[0],
        "n_val": outputs["val"]["X"].shape[0],
        "n_test": outputs["test"]["X"].shape[0],
        "n_errors": len(errors_df),
        "duration_mean": float(all_meta["original_duration_sec"].mean()),
        "cropped_pct": float(100.0 * all_meta["was_cropped"].mean()),
        "padded_pct": float(100.0 * all_meta["was_padded"].mean()),
    }

In [11]:
summary_rows = []

for dataset_name in DATASETS:
    result = process_one_dataset_e2v(
        dataset_name=dataset_name,
        csv_path=CSV_FILES[dataset_name]
    )
    summary_rows.append(result)

summary_e2v = pd.DataFrame(summary_rows)
summary_e2v.to_csv(OUT_DIR / "emotion2vec_extraction_summary.csv", index=False)

display(summary_e2v)
print("Saved:", OUT_DIR / "emotion2vec_extraction_summary.csv")

==========================================================================================
Processing emotion2vec: EMODB
==========================================================================================
Rows: 718
Speakers: 10

Distribution:

emotion  angry  disgust  fear  happy  neutral  sad
split
test        29       22    25     24       22   27
train       98       73    85     82       74   86
val         13       11    13     12       10   12

emodb train e2v:   0%|          | 0/498 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.84it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.22it/s]
emodb train e2v:   0%|          | 1/498 [00:01<16:14,  1.96s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.42it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.58it/s]
emodb train e2v:   0%|          | 2/498 [00:03<12:54,  1.56s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.93it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.16it/s]
emodb train e2v:   1%|          | 3/498 [00:04<11:52,  1.44s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.51it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.87it/s]
emodb train e2v:   1%|          | 4/498 [00:05<11:13,  1.36s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.23it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.99it/s]
emodb train e2v:   1%|          | 5/498 [00:07<10:51,  1.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.64it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.05it/s]
emodb train e2v:   1%|          | 6/498 [00:08<10:58,  1.34s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.57it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.37it/s]
emodb train e2v:   1%|▏         | 7/498 [00:09<10:56,  1.34s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.24it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.35it/s]
emodb train e2v:   2%|▏         | 8/498 [00:10<10:27,  1.28s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.97it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.05it/s]
emodb train e2v:   2%|▏         | 9/498 [00:12<10:38,  1.31s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.45it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.98it/s]
emodb train e2v:   2%|▏         | 10/498 [00:13<10:09,  1.25s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.15it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.89it/s]
emodb train e2v:   2%|▏         | 11/498 [00:14<10:23,  1.28s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.90it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.37it/s]
emodb train e2v:   2%|▏         | 12/498 [00:16<10:24,  1.29s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.29it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.55it/s]
emodb train e2v:   3%|▎         | 13/498 [00:17<10:05,  1.25s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.64it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.39it/s]
emodb train e2v:   3%|▎         | 14/498 [00:18<10:00,  1.24s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.08it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.03it/s]
emodb train e2v:   3%|▎         | 15/498 [00:19<09:49,  1.22s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.20it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.81it/s]
emodb train e2v:   3%|▎         | 16/498 [00:21<10:20,  1.29s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.45it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.58it/s]
emodb train e2v:   3%|▎         | 17/498 [00:22<11:35,  1.45s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.01it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.87it/s]
emodb train e2v:   4%|▎         | 18/498 [00:23<10:32,  1.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.99it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.46it/s]
emodb train e2v:   4%|▍         | 19/498 [00:25<10:33,  1.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.037', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 26.62it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]
emodb train e2v:   4%|▍         | 20/498 [00:26<10:34,  1.33s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.17it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.01it/s]
emodb train e2v:   4%|▍         | 21/498 [00:27<10:11,  1.28s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.10it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.09it/s]
emodb train e2v:   4%|▍         | 22/498 [00:28<10:11,  1.28s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.13it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.18it/s]
emodb train e2v:   5%|▍         | 23/498 [00:30<10:28,  1.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.88it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.73it/s]
emodb train e2v:   5%|▍         | 24/498 [00:31<10:28,  1.33s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.88it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.54it/s]
emodb train e2v:   5%|▌         | 25/498 [00:33<10:21,  1.31s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.40it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.69it/s]
emodb train e2v:   5%|▌         | 26/498 [00:34<10:41,  1.36s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.62it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.52it/s]
emodb train e2v:   5%|▌         | 27/498 [00:35<10:22,  1.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.51it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.86it/s]
emodb train e2v:   6%|▌         | 28/498 [00:36<10:05,  1.29s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.06it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.34it/s]
emodb train e2v:   6%|▌         | 29/498 [00:38<09:47,  1.25s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.56it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.79it/s]
emodb train e2v:   6%|▌         | 30/498 [00:39<10:15,  1.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.86it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.40it/s]
emodb train e2v:   6%|▌         | 31/498 [00:40<10:22,  1.33s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.10it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.94it/s]
emodb train e2v:   6%|▋         | 32/498 [00:42<10:03,  1.30s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.00it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.70it/s]
emodb train e2v:   7%|▋         | 33/498 [00:43<09:58,  1.29s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.48it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.25it/s]
emodb train e2v:   7%|▋         | 34/498 [00:44<10:14,  1.32s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.85it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.41it/s]
emodb train e2v:   7%|▋         | 35/498 [00:46<10:27,  1.35s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.50it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.71it/s]
emodb train e2v:   7%|▋         | 36/498 [00:47<10:05,  1.31s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.06it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.72it/s]
emodb train e2v:   7%|▋         | 37/498 [00:48<09:40,  1.26s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.31it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.78it/s]
emodb train e2v:   8%|▊         | 38/498 [00:49<09:38,  1.26s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.35it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.14it/s]
emodb train e2v:   8%|▊         | 39/498 [00:51<09:29,  1.24s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.54it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.54it/s]
emodb train e2v:   8%|▊         | 40/498 [00:52<09:58,  1.31s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.24it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.92it/s]
emodb train e2v:   8%|▊         | 41/498 [00:53<09:28,  1.24s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.64it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.50it/s]
emodb train e2v:   8%|▊         | 42/498 [00:54<09:24,  1.24s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.40it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.22it/s]
emodb train e2v:   9%|▊         | 43/498 [00:56<09:17,  1.22s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.08it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.62it/s]
emodb train e2v:   9%|▉         | 44/498 [00:57<09:09,  1.21s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.19it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.85it/s]
emodb train e2v:   9%|▉         | 45/498 [00:57<08:10,  1.08s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.83it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.19it/s]
emodb train e2v:   9%|▉         | 46/498 [00:59<08:48,  1.17s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.51it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.72it/s]
emodb train e2v:   9%|▉         | 47/498 [01:00<09:23,  1.25s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.79it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.14it/s]
emodb train e2v:  10%|▉         | 48/498 [01:02<09:26,  1.26s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.65it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.30it/s]
emodb train e2v:  10%|▉         | 49/498 [01:03<09:11,  1.23s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.77it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.07it/s]
emodb train e2v:  10%|█         | 50/498 [01:04<09:22,  1.26s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.019', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.27it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.53it/s]
emodb train e2v:  10%|█         | 51/498 [01:06<09:56,  1.33s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.27it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.37it/s]
emodb train e2v:  10%|█         | 52/498 [01:07<09:29,  1.28s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.57it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.93it/s]
emodb train e2v:  11%|█         | 53/498 [01:08<09:10,  1.24s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.026', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 37.04it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.05it/s]
emodb train e2v:  11%|█         | 54/498 [01:09<09:05,  1.23s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.62it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.23it/s]
emodb train e2v:  11%|█         | 55/498 [01:10<09:00,  1.22s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.99it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.41it/s]
emodb train e2v:  11%|█         | 56/498 [01:12<09:01,  1.22s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.14it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.32it/s]
emodb train e2v:  11%|█▏        | 57/498 [01:13<09:10,  1.25s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.16it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.16it/s]
emodb train e2v:  12%|█▏        | 58/498 [01:14<09:12,  1.26s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.94it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.98it/s]
emodb train e2v:  12%|█▏        | 59/498 [01:15<09:17,  1.27s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.70it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.45it/s]
emodb train e2v:  12%|█▏        | 60/498 [01:16<08:34,  1.17s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.57it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.15it/s]
emodb train e2v:  12%|█▏        | 61/498 [01:18<08:45,  1.20s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.19it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.43it/s]
emodb train e2v:  12%|█▏        | 62/498 [01:19<09:04,  1.25s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.33it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.04it/s]
emodb train e2v:  13%|█▎        | 63/498 [01:20<08:55,  1.23s/it]
  0%|          | 0/1 [00:00<?, ?it/s]

train: X=(498, 768), y=(498,), errors=0

emodb val e2v:   0%|          | 0/71 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.84it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.08it/s]
emodb val e2v:   1%|▏         | 1/71 [00:00<00:53,  1.31it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.29it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.87it/s]
emodb val e2v:   3%|▎         | 2/71 [00:01<00:50,  1.38it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.43it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.70it/s]
emodb val e2v:   4%|▍         | 3/71 [00:02<00:49,  1.38it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.14it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.90it/s]
emodb val e2v:   6%|▌         | 4/71 [00:02<00:44,  1.50it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.19it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.52it/s]
emodb val e2v:   7%|▋         | 5/71 [00:03<00:44,  1.50it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.26it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.55it/s]
emodb val e2v:   8%|▊         | 6/71 [00:04<00:42,  1.54it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.02it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.66it/s]
emodb val e2v:  10%|▉         | 7/71 [00:04<00:43,  1.47it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.65it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 26.70it/s]
emodb val e2v:  11%|█▏        | 8/71 [00:05<00:44,  1.43it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.10it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.85it/s]
emodb val e2v:  13%|█▎        | 9/71 [00:06<00:41,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.48it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.95it/s]
emodb val e2v:  14%|█▍        | 10/71 [00:06<00:37,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.18it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.39it/s]
emodb val e2v:  15%|█▌        | 11/71 [00:07<00:36,  1.66it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.67it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.91it/s]
emodb val e2v:  17%|█▋        | 12/71 [00:07<00:34,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.30it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.77it/s]
emodb val e2v:  18%|█▊        | 13/71 [00:08<00:36,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.66it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.16it/s]
emodb val e2v:  20%|█▉        | 14/71 [00:09<00:35,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.46it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.66it/s]
emodb val e2v:  21%|██        | 15/71 [00:09<00:33,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.78it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.79it/s]
emodb val e2v:  23%|██▎       | 16/71 [00:10<00:31,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.24it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.69it/s]
emodb val e2v:  24%|██▍       | 17/71 [00:10<00:32,  1.64it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.31it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.18it/s]
emodb val e2v:  25%|██▌       | 18/71 [00:11<00:29,  1.80it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.91it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.01it/s]
emodb val e2v:  27%|██▋       | 19/71 [00:11<00:28,  1.84it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.88it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.62it/s]
emodb val e2v:  28%|██▊       | 20/71 [00:12<00:27,  1.89it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.08it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.43it/s]
emodb val e2v:  30%|██▉       | 21/71 [00:13<00:29,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.98it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.18it/s]
emodb val e2v:  31%|███       | 22/71 [00:13<00:28,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.09it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.93it/s]
emodb val e2v:  32%|███▏      | 23/71 [00:14<00:29,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.39it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.03it/s]
emodb val e2v:  34%|███▍      | 24/71 [00:14<00:28,  1.67it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.54it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.31it/s]
emodb val e2v:  35%|███▌      | 25/71 [00:15<00:26,  1.72it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.68it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.95it/s]
emodb val e2v:  37%|███▋      | 26/71 [00:16<00:28,  1.60it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.69it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.38it/s]
emodb val e2v:  38%|███▊      | 27/71 [00:16<00:26,  1.66it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.81it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.77it/s]
emodb val e2v:  39%|███▉      | 28/71 [00:17<00:25,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.42it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.15it/s]
emodb val e2v:  41%|████      | 29/71 [00:17<00:25,  1.66it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.30it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.47it/s]
emodb val e2v:  42%|████▏     | 30/71 [00:18<00:24,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.79it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.51it/s]
emodb val e2v:  44%|████▎     | 31/71 [00:19<00:23,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.74it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.51it/s]
emodb val e2v:  45%|████▌     | 32/71 [00:19<00:22,  1.72it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.97it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.81it/s]
emodb val e2v:  46%|████▋     | 33/71 [00:20<00:21,  1.74it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.55it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.70it/s]
emodb val e2v:  48%|████▊     | 34/71 [00:20<00:20,  1.80it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.66it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.68it/s]
emodb val e2v:  49%|████▉     | 35/71 [00:21<00:19,  1.81it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.53it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.86it/s]
emodb val e2v:  51%|█████     | 36/71 [00:21<00:18,  1.92it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.54it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.16it/s]
emodb val e2v:  52%|█████▏    | 37/71 [00:22<00:17,  1.90it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.56it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.39it/s]
emodb val e2v:  54%|█████▎    | 38/71 [00:22<00:18,  1.79it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.44it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.17it/s]
emodb val e2v:  55%|█████▍    | 39/71 [00:23<00:16,  1.90it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.86it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.80it/s]
emodb val e2v:  56%|█████▋    | 40/71 [00:23<00:15,  1.97it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.98it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.97it/s]
emodb val e2v:  58%|█████▊    | 41/71 [00:24<00:14,  2.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.07it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.43it/s]
emodb val e2v:  59%|█████▉    | 42/71 [00:24<00:14,  1.95it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.020', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.42it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 23.17it/s]
emodb val e2v:  61%|██████    | 43/71 [00:25<00:14,  1.89it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.83it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.72it/s]
emodb val e2v:  62%|██████▏   | 44/71 [00:25<00:15,  1.77it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.39it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.34it/s]
emodb val e2v:  63%|██████▎   | 45/71 [00:26<00:14,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.65it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.24it/s]
emodb val e2v:  65%|██████▍   | 46/71 [00:27<00:14,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.02it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.37it/s]
emodb val e2v:  66%|██████▌   | 47/71 [00:27<00:15,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.18it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.98it/s]
emodb val e2v:  68%|██████▊   | 48/71 [00:28<00:15,  1.46it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.98it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.51it/s]
emodb val e2v:  69%|██████▉   | 49/71 [00:29<00:14,  1.56it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.85it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.39it/s]
emodb val e2v:  70%|███████   | 50/71 [00:29<00:13,  1.50it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.44it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.41it/s]
emodb val e2v:  72%|███████▏  | 51/71 [00:30<00:12,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.26it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.69it/s]
emodb val e2v:  73%|███████▎  | 52/71 [00:31<00:11,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.70it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.70it/s]
emodb val e2v:  75%|███████▍  | 53/71 [00:31<00:11,  1.62it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.46it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.86it/s]
emodb val e2v:  76%|███████▌  | 54/71 [00:32<00:10,  1.57it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.66it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.90it/s]
emodb val e2v:  77%|███████▋  | 55/71 [00:32<00:09,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.71it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.12it/s]
emodb val e2v:  79%|███████▉  | 56/71 [00:33<00:09,  1.60it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.48it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.85it/s]
emodb val e2v:  80%|████████  | 57/71 [00:34<00:08,  1.66it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.81it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.53it/s]
emodb val e2v:  82%|████████▏ | 58/71 [00:34<00:07,  1.83it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.04it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.65it/s]
emodb val e2v:  83%|████████▎ | 59/71 [00:35<00:06,  1.79it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.54it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.84it/s]
emodb val e2v:  85%|████████▍ | 60/71 [00:35<00:06,  1.83it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.32it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.62it/s]
emodb val e2v:  86%|████████▌ | 61/71 [00:36<00:05,  1.80it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.81it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.14it/s]
emodb val e2v:  87%|████████▋ | 62/71 [00:36<00:05,  1.78it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.51it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.73it/s]
emodb val e2v:  89%|████████▊ | 63/71 [00:37<00:04,  1.71it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.021', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.04it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 23.15it/s]
emodb val e2v:  90%|█████████ | 64/71 [00:38<00:04,  1.74it/s]
  0%|          | 0/1 [00:00<?, ?it/s]

val: X=(71, 768), y=(71,), errors=0

emodb test e2v:   0%|          | 0/149 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.20it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.36it/s]
emodb test e2v:   1%|          | 1/149 [00:00<01:20,  1.83it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.34it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.63it/s]
emodb test e2v:   1%|▏         | 2/149 [00:01<01:20,  1.82it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.64it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.81it/s]
emodb test e2v:   2%|▏         | 3/149 [00:01<01:26,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.13it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.17it/s]
emodb test e2v:   3%|▎         | 4/149 [00:02<01:34,  1.54it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.06it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.81it/s]
emodb test e2v:   3%|▎         | 5/149 [00:03<01:32,  1.56it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.66it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.60it/s]
emodb test e2v:   4%|▍         | 6/149 [00:03<01:19,  1.81it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.80it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.01it/s]
emodb test e2v:   5%|▍         | 7/149 [00:04<01:23,  1.71it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.79it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.15it/s]
emodb test e2v:   5%|▌         | 8/149 [00:04<01:22,  1.72it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.38it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.89it/s]
emodb test e2v:   6%|▌         | 9/149 [00:05<01:19,  1.75it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.49it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.32it/s]
emodb test e2v:   7%|▋         | 10/149 [00:05<01:26,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.91it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.95it/s]
emodb test e2v:   7%|▋         | 11/149 [00:06<01:23,  1.65it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.66it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.69it/s]
emodb test e2v:   8%|▊         | 12/149 [00:07<01:21,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.06it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.05it/s]
emodb test e2v:   9%|▊         | 13/149 [00:07<01:19,  1.72it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.019', 'extract_feat': 0.0, 'forward': '0.036', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 27.58it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 25.03it/s]
emodb test e2v:   9%|▉         | 14/149 [00:08<01:16,  1.77it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.27it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.39it/s]
emodb test e2v:  10%|█         | 15/149 [00:08<01:13,  1.83it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.95it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.83it/s]
emodb test e2v:  11%|█         | 16/149 [00:09<01:11,  1.87it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.99it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.26it/s]
emodb test e2v:  11%|█▏        | 17/149 [00:09<01:05,  2.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.77it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.69it/s]
emodb test e2v:  12%|█▏        | 18/149 [00:10<01:08,  1.90it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.83it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.40it/s]
emodb test e2v:  13%|█▎        | 19/149 [00:10<01:07,  1.91it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.019', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.23it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.42it/s]
emodb test e2v:  13%|█▎        | 20/149 [00:11<01:12,  1.78it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.35it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.90it/s]
emodb test e2v:  14%|█▍        | 21/149 [00:11<01:08,  1.86it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.23it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.04it/s]
emodb test e2v:  15%|█▍        | 22/149 [00:12<01:13,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.97it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.23it/s]
emodb test e2v:  15%|█▌        | 23/149 [00:13<01:14,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.26it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.34it/s]
emodb test e2v:  16%|█▌        | 24/149 [00:13<01:11,  1.75it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.63it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.33it/s]
emodb test e2v:  17%|█▋        | 25/149 [00:14<01:08,  1.80it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.38it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.95it/s]
emodb test e2v:  17%|█▋        | 26/149 [00:14<01:04,  1.90it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.30it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.95it/s]
emodb test e2v:  18%|█▊        | 27/149 [00:15<01:05,  1.86it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.90it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.33it/s]
emodb test e2v:  19%|█▉        | 28/149 [00:15<01:07,  1.79it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.31it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.63it/s]
emodb test e2v:  19%|█▉        | 29/149 [00:16<01:06,  1.81it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.63it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.73it/s]
emodb test e2v:  20%|██        | 30/149 [00:17<01:10,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.21it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.79it/s]
emodb test e2v:  21%|██        | 31/149 [00:17<01:09,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.17it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.24it/s]
emodb test e2v:  21%|██▏       | 32/149 [00:18<01:11,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.61it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.72it/s]
emodb test e2v:  22%|██▏       | 33/149 [00:18<01:07,  1.71it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.83it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.42it/s]
emodb test e2v:  23%|██▎       | 34/149 [00:19<01:03,  1.80it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.54it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.78it/s]
emodb test e2v:  23%|██▎       | 35/149 [00:20<01:08,  1.67it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.22it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.68it/s]
emodb test e2v:  24%|██▍       | 36/149 [00:20<01:14,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.39it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.93it/s]
emodb test e2v:  25%|██▍       | 37/149 [00:21<01:13,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.66it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.50it/s]
emodb test e2v:  26%|██▌       | 38/149 [00:22<01:15,  1.47it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.80it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.15it/s]
emodb test e2v:  26%|██▌       | 39/149 [00:22<01:10,  1.56it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.71it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.70it/s]
emodb test e2v:  27%|██▋       | 40/149 [00:23<01:14,  1.47it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.82it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.87it/s]
emodb test e2v:  28%|██▊       | 41/149 [00:24<01:07,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.85it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.81it/s]
emodb test e2v:  28%|██▊       | 42/149 [00:24<01:04,  1.66it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.61it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.54it/s]
emodb test e2v:  29%|██▉       | 43/149 [00:25<01:01,  1.72it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.80it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.92it/s]
emodb test e2v:  30%|██▉       | 44/149 [00:25<01:01,  1.71it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.98it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.79it/s]
emodb test e2v:  30%|███       | 45/149 [00:26<00:59,  1.75it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.94it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.66it/s]
emodb test e2v:  31%|███       | 46/149 [00:26<01:02,  1.64it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.64it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.87it/s]
emodb test e2v:  32%|███▏      | 47/149 [00:27<01:00,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.46it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.02it/s]
emodb test e2v:  32%|███▏      | 48/149 [00:28<00:57,  1.74it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.78it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.60it/s]
emodb test e2v:  33%|███▎      | 49/149 [00:28<00:55,  1.79it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.82it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.67it/s]
emodb test e2v:  34%|███▎      | 50/149 [00:29<00:54,  1.80it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.73it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.31it/s]
emodb test e2v:  34%|███▍      | 51/149 [00:29<00:59,  1.65it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.36it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.66it/s]
emodb test e2v:  35%|███▍      | 52/149 [00:30<00:57,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.59it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.40it/s]
emodb test e2v:  36%|███▌      | 53/149 [00:31<01:02,  1.54it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.63it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.60it/s]
emodb test e2v:  36%|███▌      | 54/149 [00:31<00:59,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.77it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.30it/s]
emodb test e2v:  37%|███▋      | 55/149 [00:32<00:57,  1.62it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.80it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.57it/s]
emodb test e2v:  38%|███▊      | 56/149 [00:32<00:57,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.40it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.22it/s]
emodb test e2v:  38%|███▊      | 57/149 [00:33<01:01,  1.50it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.41it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.79it/s]
emodb test e2v:  39%|███▉      | 58/149 [00:34<01:03,  1.44it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.76it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.51it/s]
emodb test e2v:  40%|███▉      | 59/149 [00:35<01:02,  1.43it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.45it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.01it/s]
emodb test e2v:  40%|████      | 60/149 [00:35<01:04,  1.37it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.33it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.58it/s]
emodb test e2v:  41%|████      | 61/149 [00:36<00:59,  1.48it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 36.12it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 32.71it/s]
emodb test e2v:  42%|████▏     | 62/149 [00:37<00:58,  1.50it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.95it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.21it/s]
emodb test e2v:  42%|████▏     | 63/149 [00:37<00:54,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.90it/s]

test: X=(149, 768), y=(149,), errors=0

Saved: /content/drive/MyDrive/New Jurnal Cross/processed_intra_features_e2v_plus_base/emodb
Embedding dim: 768
Errors: 0
==========================================================================================
Processing emotion2vec: RAVDESS
==========================================================================================
Rows: 1056
Speakers: 24

Distribution:

emotion  angry  disgust  fear  happy  neutral  sad
split
test        32       32    32     32       16   32
train      128      128   128    128       64  128
val         32       32    32     32       16   32

ravdess train e2v:   0%|          | 0/704 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.90it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.79it/s]
ravdess train e2v:   0%|          | 1/704 [00:02<24:55,  2.13s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.91it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.23it/s]
ravdess train e2v:   0%|          | 2/704 [00:03<19:36,  1.68s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.10it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.22it/s]
ravdess train e2v:   0%|          | 3/704 [00:04<17:14,  1.48s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.39it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.17it/s]
ravdess train e2v:   1%|          | 4/704 [00:05<12:53,  1.11s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.66it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.25it/s]
ravdess train e2v:   1%|          | 5/704 [00:06<14:25,  1.24s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.043', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.68it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.80it/s]
ravdess train e2v:   1%|          | 6/704 [00:08<15:03,  1.29s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.11it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.00it/s]
ravdess train e2v:   1%|          | 7/704 [00:08<13:12,  1.14s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.62it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.37it/s]
ravdess train e2v:   1%|          | 8/704 [00:09<11:17,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.24it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.26it/s]
ravdess train e2v:   1%|▏         | 9/704 [00:10<09:34,  1.21it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.27it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.58it/s]
ravdess train e2v:   1%|▏         | 10/704 [00:10<08:39,  1.34it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.87it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.96it/s]
ravdess train e2v:   2%|▏         | 11/704 [00:11<08:10,  1.41it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.03it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.28it/s]
ravdess train e2v:   2%|▏         | 12/704 [00:11<07:45,  1.49it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.59it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.86it/s]
ravdess train e2v:   2%|▏         | 13/704 [00:12<07:25,  1.55it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.89it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.45it/s]
ravdess train e2v:   2%|▏         | 14/704 [00:13<07:44,  1.49it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.42it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.06it/s]
ravdess train e2v:   2%|▏         | 15/704 [00:13<07:26,  1.54it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.81it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.43it/s]
ravdess train e2v:   2%|▏         | 16/704 [00:14<07:19,  1.57it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.06it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.06it/s]
ravdess train e2v:   2%|▏         | 17/704 [00:14<07:06,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.56it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.67it/s]
ravdess train e2v:   3%|▎         | 18/704 [00:15<07:04,  1.62it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.019', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 28.52it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 26.02it/s]
ravdess train e2v:   3%|▎         | 19/704 [00:16<06:55,  1.65it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 28.93it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.64it/s]
ravdess train e2v:   3%|▎         | 20/704 [00:16<06:43,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.15it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.97it/s]
ravdess train e2v:   3%|▎         | 21/704 [00:17<07:06,  1.60it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.14it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.76it/s]
ravdess train e2v:   3%|▎         | 22/704 [00:17<06:41,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.80it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.06it/s]
ravdess train e2v:   3%|▎         | 23/704 [00:18<07:18,  1.55it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.16it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.69it/s]
ravdess train e2v:   3%|▎         | 24/704 [00:19<06:57,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.09it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.22it/s]
ravdess train e2v:   4%|▎         | 25/704 [00:19<06:42,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.89it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.22it/s]
ravdess train e2v:   4%|▎         | 26/704 [00:20<06:53,  1.64it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.20it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.25it/s]
ravdess train e2v:   4%|▍         | 27/704 [00:21<06:47,  1.66it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.15it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.21it/s]
ravdess train e2v:   4%|▍         | 28/704 [00:21<07:23,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.13it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.05it/s]
ravdess train e2v:   4%|▍         | 29/704 [00:22<07:33,  1.49it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.54it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.08it/s]
ravdess train e2v:   4%|▍         | 30/704 [00:23<07:13,  1.55it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.06it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.03it/s]
ravdess train e2v:   4%|▍         | 31/704 [00:23<07:04,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.13it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.57it/s]
ravdess train e2v:   5%|▍         | 32/704 [00:24<07:24,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.70it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.28it/s]
ravdess train e2v:   5%|▍         | 33/704 [00:25<07:29,  1.49it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.86it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.56it/s]
ravdess train e2v:   5%|▍         | 34/704 [00:25<06:59,  1.60it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.16it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.48it/s]
ravdess train e2v:   5%|▍         | 35/704 [00:26<06:53,  1.62it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.96it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.99it/s]
ravdess train e2v:   5%|▌         | 36/704 [00:26<06:49,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.20it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.29it/s]
ravdess train e2v:   5%|▌         | 37/704 [00:27<07:20,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.019', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.54it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.75it/s]
ravdess train e2v:   5%|▌         | 38/704 [00:28<07:37,  1.46it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.41it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.00it/s]
ravdess train e2v:   6%|▌         | 39/704 [00:28<07:24,  1.49it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.42it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.62it/s]
ravdess train e2v:   6%|▌         | 40/704 [00:29<07:17,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.79it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.01it/s]
ravdess train e2v:   6%|▌         | 41/704 [00:30<07:27,  1.48it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.77it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.74it/s]
ravdess train e2v:   6%|▌         | 42/704 [00:30<07:17,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.78it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.57it/s]
ravdess train e2v:   6%|▌         | 43/704 [00:31<06:29,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.69it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.76it/s]
ravdess train e2v:   6%|▋         | 44/704 [00:32<06:50,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.94it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.03it/s]
ravdess train e2v:   6%|▋         | 45/704 [00:32<06:39,  1.65it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.48it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.50it/s]
ravdess train e2v:   7%|▋         | 46/704 [00:33<07:11,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.98it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.75it/s]
ravdess train e2v:   7%|▋         | 47/704 [00:33<06:53,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.16it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.36it/s]
ravdess train e2v:   7%|▋         | 48/704 [00:34<06:36,  1.66it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.75it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 28.94it/s]
ravdess train e2v:   7%|▋         | 49/704 [00:34<06:04,  1.80it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.74it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.57it/s]
ravdess train e2v:   7%|▋         | 50/704 [00:35<06:12,  1.75it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.39it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.93it/s]
ravdess train e2v:   7%|▋         | 51/704 [00:36<06:26,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.97it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.93it/s]
ravdess train e2v:   7%|▋         | 52/704 [00:36<06:16,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.77it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.66it/s]
ravdess train e2v:   8%|▊         | 53/704 [00:37<06:15,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.61it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.80it/s]
ravdess train e2v:   8%|▊         | 54/704 [00:37<06:22,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.21it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.72it/s]
ravdess train e2v:   8%|▊         | 55/704 [00:38<06:09,  1.76it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.44it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.06it/s]
ravdess train e2v:   8%|▊         | 56/704 [00:39<06:05,  1.77it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.020', 'extract_feat': 0.0, 'forward': '0.035', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 28.00it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 25.17it/s]
ravdess train e2v:   8%|▊         | 57/704 [00:39<06:12,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.019', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.02it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.25it/s]
ravdess train e2v:   8%|▊         | 58/704 [00:40<06:43,  1.60it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.69it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.87it/s]
ravdess train e2v:   8%|▊         | 59/704 [00:40<06:32,  1.65it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.99it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.56it/s]
ravdess train e2v:   9%|▊         | 60/704 [00:41<06:22,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.019', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.26it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.44it/s]
ravdess train e2v:   9%|▊         | 61/704 [00:42<06:14,  1.72it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.026', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.52it/s]
ravdess train e2v:   9%|▉         | 62/704 [00:42<06:09,  1.74it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.99it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.10it/s]
ravdess train e2v:   9%|▉         | 63/704 [00:43<06:33,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]

train: X=(704, 768), y=(704,), errors=0

ravdess val e2v:   0%|          | 0/176 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.34it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.77it/s]
ravdess val e2v:   1%|          | 1/176 [00:00<01:58,  1.47it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.26it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.17it/s]
ravdess val e2v:   1%|          | 2/176 [00:01<01:49,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.03it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.38it/s]
ravdess val e2v:   2%|▏         | 3/176 [00:01<01:45,  1.65it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.04it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.10it/s]
ravdess val e2v:   2%|▏         | 4/176 [00:02<01:41,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.15it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.78it/s]
ravdess val e2v:   3%|▎         | 5/176 [00:03<01:40,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.16it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.18it/s]
ravdess val e2v:   3%|▎         | 6/176 [00:03<01:41,  1.67it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.63it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.11it/s]
ravdess val e2v:   4%|▍         | 7/176 [00:04<01:47,  1.57it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.45it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.77it/s]
ravdess val e2v:   5%|▍         | 8/176 [00:04<01:44,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.18it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.45it/s]
ravdess val e2v:   5%|▌         | 9/176 [00:05<01:50,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.89it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.66it/s]
ravdess val e2v:   6%|▌         | 10/176 [00:06<01:38,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.98it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.73it/s]
ravdess val e2v:   6%|▋         | 11/176 [00:06<01:43,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.99it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.86it/s]
ravdess val e2v:   7%|▋         | 12/176 [00:07<01:39,  1.64it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.37it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.89it/s]
ravdess val e2v:   7%|▋         | 13/176 [00:07<01:37,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.29it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.02it/s]
ravdess val e2v:   8%|▊         | 14/176 [00:08<01:36,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.68it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.38it/s]
ravdess val e2v:   9%|▊         | 15/176 [00:09<01:30,  1.78it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.08it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.74it/s]
ravdess val e2v:   9%|▉         | 16/176 [00:09<01:37,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.06it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.93it/s]
ravdess val e2v:  10%|▉         | 17/176 [00:10<01:39,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.50it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.13it/s]
ravdess val e2v:  10%|█         | 18/176 [00:10<01:32,  1.71it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.15it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.50it/s]
ravdess val e2v:  11%|█         | 19/176 [00:11<01:31,  1.72it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.36it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.98it/s]
ravdess val e2v:  11%|█▏        | 20/176 [00:12<01:31,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.42it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.76it/s]
ravdess val e2v:  12%|█▏        | 21/176 [00:12<01:26,  1.80it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.23it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 23.30it/s]
ravdess val e2v:  12%|█▎        | 22/176 [00:13<01:25,  1.80it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.80it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.83it/s]
ravdess val e2v:  13%|█▎        | 23/176 [00:13<01:25,  1.80it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.34it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.45it/s]
ravdess val e2v:  14%|█▎        | 24/176 [00:14<01:26,  1.76it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.07it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.13it/s]
ravdess val e2v:  14%|█▍        | 25/176 [00:14<01:24,  1.79it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.77it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.30it/s]
ravdess val e2v:  15%|█▍        | 26/176 [00:15<01:23,  1.79it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.020', 'extract_feat': 0.0, 'forward': '0.036', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 26.86it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]
ravdess val e2v:  15%|█▌        | 27/176 [00:15<01:24,  1.77it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 28.81it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 26.27it/s]
ravdess val e2v:  16%|█▌        | 28/176 [00:16<01:25,  1.74it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.49it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.41it/s]
ravdess val e2v:  16%|█▋        | 29/176 [00:16<01:18,  1.87it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.78it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.46it/s]
ravdess val e2v:  17%|█▋        | 30/176 [00:17<01:20,  1.82it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.05it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.56it/s]
ravdess val e2v:  18%|█▊        | 31/176 [00:18<01:21,  1.78it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.18it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.39it/s]
ravdess val e2v:  18%|█▊        | 32/176 [00:18<01:25,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.19it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.78it/s]
ravdess val e2v:  19%|█▉        | 33/176 [00:19<01:22,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.09it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.97it/s]
ravdess val e2v:  19%|█▉        | 34/176 [00:20<01:28,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.94it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.25it/s]
ravdess val e2v:  20%|█▉        | 35/176 [00:20<01:33,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.74it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.32it/s]
ravdess val e2v:  20%|██        | 36/176 [00:21<01:36,  1.45it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.44it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.34it/s]
ravdess val e2v:  21%|██        | 37/176 [00:22<01:31,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.46it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.68it/s]
ravdess val e2v:  22%|██▏       | 38/176 [00:22<01:29,  1.55it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.53it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.65it/s]
ravdess val e2v:  22%|██▏       | 39/176 [00:23<01:26,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.91it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.42it/s]
ravdess val e2v:  23%|██▎       | 40/176 [00:24<01:26,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.88it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.47it/s]
ravdess val e2v:  23%|██▎       | 41/176 [00:24<01:23,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.26it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.33it/s]
ravdess val e2v:  24%|██▍       | 42/176 [00:25<01:25,  1.57it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.05it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.21it/s]
ravdess val e2v:  24%|██▍       | 43/176 [00:25<01:19,  1.67it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.62it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.83it/s]
ravdess val e2v:  25%|██▌       | 44/176 [00:26<01:19,  1.66it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.28it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.97it/s]
ravdess val e2v:  26%|██▌       | 45/176 [00:26<01:15,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.020', 'extract_feat': 0.0, 'forward': '0.036', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 27.02it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 24.77it/s]
ravdess val e2v:  26%|██▌       | 46/176 [00:27<01:17,  1.67it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.42it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.63it/s]
ravdess val e2v:  27%|██▋       | 47/176 [00:28<01:15,  1.72it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.77it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.71it/s]
ravdess val e2v:  27%|██▋       | 48/176 [00:28<01:11,  1.80it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.035', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 28.24it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 25.68it/s]
ravdess val e2v:  28%|██▊       | 49/176 [00:29<01:17,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.27it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.39it/s]
ravdess val e2v:  28%|██▊       | 50/176 [00:30<01:19,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.020', 'extract_feat': 0.0, 'forward': '0.035', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 28.08it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 25.30it/s]
ravdess val e2v:  29%|██▉       | 51/176 [00:30<01:16,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.58it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.53it/s]
ravdess val e2v:  30%|██▉       | 52/176 [00:31<01:14,  1.67it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.66it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.38it/s]
ravdess val e2v:  30%|███       | 53/176 [00:31<01:09,  1.76it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.38it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.14it/s]
ravdess val e2v:  31%|███       | 54/176 [00:32<01:11,  1.71it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.97it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.25it/s]
ravdess val e2v:  31%|███▏      | 55/176 [00:32<01:09,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.03it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.25it/s]
ravdess val e2v:  32%|███▏      | 56/176 [00:33<01:08,  1.74it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.65it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.81it/s]
ravdess val e2v:  32%|███▏      | 57/176 [00:34<01:15,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.29it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.38it/s]
ravdess val e2v:  33%|███▎      | 58/176 [00:34<01:09,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.19it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.23it/s]
ravdess val e2v:  34%|███▎      | 59/176 [00:35<01:09,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.38it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.37it/s]
ravdess val e2v:  34%|███▍      | 60/176 [00:36<01:13,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 28.54it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 26.19it/s]
ravdess val e2v:  35%|███▍      | 61/176 [00:36<01:11,  1.60it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.21it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.52it/s]
ravdess val e2v:  35%|███▌      | 62/176 [00:37<01:11,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.51it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.39it/s]
ravdess val e2v:  36%|███▌      | 63/176 [00:37<01:07,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]

val: X=(176, 768), y=(176,), errors=0

ravdess test e2v:   0%|          | 0/176 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.30it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.42it/s]
ravdess test e2v:   1%|          | 1/176 [00:00<01:31,  1.91it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.40it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.21it/s]
ravdess test e2v:   1%|          | 2/176 [00:01<01:37,  1.78it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.81it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.85it/s]
ravdess test e2v:   2%|▏         | 3/176 [00:01<01:36,  1.79it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.69it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.80it/s]
ravdess test e2v:   2%|▏         | 4/176 [00:02<01:28,  1.95it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.70it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.60it/s]
ravdess test e2v:   3%|▎         | 5/176 [00:02<01:25,  2.01it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.05it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.92it/s]
ravdess test e2v:   3%|▎         | 6/176 [00:03<01:22,  2.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.13it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.82it/s]
ravdess test e2v:   4%|▍         | 7/176 [00:03<01:33,  1.81it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.47it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.29it/s]
ravdess test e2v:   5%|▍         | 8/176 [00:04<01:35,  1.76it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.05it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.41it/s]
ravdess test e2v:   5%|▌         | 9/176 [00:04<01:36,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.60it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.55it/s]
ravdess test e2v:   6%|▌         | 10/176 [00:05<01:37,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.019', 'extract_feat': 0.0, 'forward': '0.036', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 27.60it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 25.33it/s]
ravdess test e2v:   6%|▋         | 11/176 [00:06<01:37,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.08it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.77it/s]
ravdess test e2v:   7%|▋         | 12/176 [00:06<01:43,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.01it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.55it/s]
ravdess test e2v:   7%|▋         | 13/176 [00:07<01:39,  1.64it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.60it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.08it/s]
ravdess test e2v:   8%|▊         | 14/176 [00:07<01:36,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.23it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.95it/s]
ravdess test e2v:   9%|▊         | 15/176 [00:08<01:35,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.75it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.47it/s]
ravdess test e2v:   9%|▉         | 16/176 [00:09<01:39,  1.60it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.76it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.30it/s]
ravdess test e2v:  10%|▉         | 17/176 [00:10<01:44,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.71it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.66it/s]
ravdess test e2v:  10%|█         | 18/176 [00:10<01:33,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.44it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.11it/s]
ravdess test e2v:  11%|█         | 19/176 [00:11<01:30,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.37it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.60it/s]
ravdess test e2v:  11%|█▏        | 20/176 [00:11<01:25,  1.83it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.62it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.44it/s]
ravdess test e2v:  12%|█▏        | 21/176 [00:12<01:44,  1.48it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.28it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.46it/s]
ravdess test e2v:  12%|█▎        | 22/176 [00:13<01:38,  1.57it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.75it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.69it/s]
ravdess test e2v:  13%|█▎        | 23/176 [00:13<01:38,  1.56it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.96it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.14it/s]
ravdess test e2v:  14%|█▎        | 24/176 [00:14<01:35,  1.60it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.94it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.96it/s]
ravdess test e2v:  14%|█▍        | 25/176 [00:15<01:48,  1.39it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.60it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.83it/s]
ravdess test e2v:  15%|█▍        | 26/176 [00:15<01:40,  1.49it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.35it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.94it/s]
ravdess test e2v:  15%|█▌        | 27/176 [00:16<01:34,  1.57it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.62it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.63it/s]
ravdess test e2v:  16%|█▌        | 28/176 [00:17<01:37,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.037', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 26.42it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]
ravdess test e2v:  16%|█▋        | 29/176 [00:17<01:36,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.33it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.35it/s]
ravdess test e2v:  17%|█▋        | 30/176 [00:18<01:33,  1.56it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.82it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.18it/s]
ravdess test e2v:  18%|█▊        | 31/176 [00:19<01:38,  1.47it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.23it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.12it/s]
ravdess test e2v:  18%|█▊        | 32/176 [00:19<01:41,  1.42it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.01it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.01it/s]
ravdess test e2v:  19%|█▉        | 33/176 [00:20<01:41,  1.41it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.95it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.07it/s]
ravdess test e2v:  19%|█▉        | 34/176 [00:21<01:39,  1.42it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.08it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.41it/s]
ravdess test e2v:  20%|█▉        | 35/176 [00:21<01:33,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.61it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.18it/s]
ravdess test e2v:  20%|██        | 36/176 [00:22<01:28,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.52it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.95it/s]
ravdess test e2v:  21%|██        | 37/176 [00:22<01:22,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.57it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.64it/s]
ravdess test e2v:  22%|██▏       | 38/176 [00:23<01:22,  1.67it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.34it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 23.24it/s]
ravdess test e2v:  22%|██▏       | 39/176 [00:24<01:29,  1.54it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.04it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.99it/s]
ravdess test e2v:  23%|██▎       | 40/176 [00:24<01:25,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.06it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.81it/s]
ravdess test e2v:  23%|██▎       | 41/176 [00:25<01:29,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.98it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.92it/s]
ravdess test e2v:  24%|██▍       | 42/176 [00:26<01:24,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.27it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.12it/s]
ravdess test e2v:  24%|██▍       | 43/176 [00:26<01:22,  1.60it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.33it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.96it/s]
ravdess test e2v:  25%|██▌       | 44/176 [00:27<01:20,  1.64it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.58it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.87it/s]
ravdess test e2v:  26%|██▌       | 45/176 [00:27<01:18,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.25it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.72it/s]
ravdess test e2v:  26%|██▌       | 46/176 [00:28<01:22,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.037', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 26.43it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 24.47it/s]
ravdess test e2v:  27%|██▋       | 47/176 [00:29<01:20,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.044', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.39it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.75it/s]
ravdess test e2v:  27%|██▋       | 48/176 [00:29<01:16,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.021', 'extract_feat': 0.0, 'forward': '0.038', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 26.04it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]
ravdess test e2v:  28%|██▊       | 49/176 [00:30<01:17,  1.64it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.10it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.68it/s]
ravdess test e2v:  28%|██▊       | 50/176 [00:30<01:15,  1.66it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.29it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.02it/s]
ravdess test e2v:  29%|██▉       | 51/176 [00:31<01:14,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.39it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.48it/s]
ravdess test e2v:  30%|██▉       | 52/176 [00:32<01:14,  1.66it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.45it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.49it/s]
ravdess test e2v:  30%|███       | 53/176 [00:32<01:13,  1.67it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.29it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.56it/s]
ravdess test e2v:  31%|███       | 54/176 [00:33<01:14,  1.64it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.58it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.55it/s]
ravdess test e2v:  31%|███▏      | 55/176 [00:33<01:13,  1.64it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.37it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.70it/s]
ravdess test e2v:  32%|███▏      | 56/176 [00:34<01:06,  1.80it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.92it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.56it/s]
ravdess test e2v:  32%|███▏      | 57/176 [00:34<01:04,  1.83it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.34it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.16it/s]
ravdess test e2v:  33%|███▎      | 58/176 [00:35<01:06,  1.78it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.03it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.87it/s]
ravdess test e2v:  34%|███▎      | 59/176 [00:36<01:04,  1.82it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.16it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.30it/s]
ravdess test e2v:  34%|███▍      | 60/176 [00:36<01:04,  1.80it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.40it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.39it/s]
ravdess test e2v:  35%|███▍      | 61/176 [00:37<01:12,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.24it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.97it/s]
ravdess test e2v:  35%|███▌      | 62/176 [00:37<01:09,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.48it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.22it/s]
ravdess test e2v:  36%|███▌      | 63/176 [00:38<01:02,  1.79it/s]
  0%|          | 0/1 [00:00<?, ?it/s]

test: X=(176, 768), y=(176,), errors=0

Saved: /content/drive/MyDrive/New Jurnal Cross/processed_intra_features_e2v_plus_base/ravdess
Embedding dim: 768
Errors: 0
==========================================================================================
Processing emotion2vec: RESD
==========================================================================================
Rows: 1198
Speakers: 50

Distribution:

emotion  angry  disgust  fear  happy  neutral  sad
split
test        34       15    29     23       20   18
train      154      135   162    160      140  122
val         31       35    32     35       31   22

resd train e2v:   0%|          | 0/873 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.13it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.80it/s]
resd train e2v:   0%|          | 1/873 [00:01<22:59,  1.58s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.16it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.19it/s]
resd train e2v:   0%|          | 2/873 [00:02<14:43,  1.01s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.22it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.70it/s]
resd train e2v:   0%|          | 3/873 [00:02<11:42,  1.24it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.74it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.10it/s]
resd train e2v:   0%|          | 4/873 [00:03<10:03,  1.44it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.36it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.66it/s]
resd train e2v:   1%|          | 5/873 [00:03<09:30,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.34it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.38it/s]
resd train e2v:   1%|          | 6/873 [00:04<09:05,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.74it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.55it/s]
resd train e2v:   1%|          | 7/873 [00:05<08:48,  1.64it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.21it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.56it/s]
resd train e2v:   1%|          | 8/873 [00:05<08:06,  1.78it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.34it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.22it/s]
resd train e2v:   1%|          | 9/873 [00:06<09:14,  1.56it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.89it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.62it/s]
resd train e2v:   1%|          | 10/873 [00:06<08:44,  1.65it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.43it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.43it/s]
resd train e2v:   1%|▏         | 11/873 [00:07<09:45,  1.47it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.12it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.80it/s]
resd train e2v:   1%|▏         | 12/873 [00:08<09:21,  1.53it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.021', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.96it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.52it/s]
resd train e2v:   1%|▏         | 13/873 [00:09<09:57,  1.44it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.21it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.58it/s]
resd train e2v:   2%|▏         | 14/873 [00:09<09:28,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.020', 'extract_feat': 0.0, 'forward': '0.036', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 27.50it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 25.12it/s]
resd train e2v:   2%|▏         | 15/873 [00:10<09:21,  1.53it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.88it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 28.88it/s]
resd train e2v:   2%|▏         | 16/873 [00:10<08:53,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.04it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.08it/s]
resd train e2v:   2%|▏         | 17/873 [00:11<08:49,  1.62it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.95it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.89it/s]
resd train e2v:   2%|▏         | 18/873 [00:11<08:35,  1.66it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.81it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.32it/s]
resd train e2v:   2%|▏         | 19/873 [00:12<08:29,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.86it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.64it/s]
resd train e2v:   2%|▏         | 20/873 [00:13<09:22,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.52it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.29it/s]
resd train e2v:   2%|▏         | 21/873 [00:14<09:11,  1.54it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.93it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.47it/s]
resd train e2v:   3%|▎         | 22/873 [00:14<09:33,  1.48it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.77it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.10it/s]
resd train e2v:   3%|▎         | 23/873 [00:15<09:26,  1.50it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.37it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.83it/s]
resd train e2v:   3%|▎         | 24/873 [00:16<09:18,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.37it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.07it/s]
resd train e2v:   3%|▎         | 25/873 [00:16<08:54,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.95it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.53it/s]
resd train e2v:   3%|▎         | 26/873 [00:17<08:39,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.96it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.58it/s]
resd train e2v:   3%|▎         | 27/873 [00:17<08:38,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.76it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.06it/s]
resd train e2v:   3%|▎         | 28/873 [00:18<08:24,  1.67it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.42it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.02it/s]
resd train e2v:   3%|▎         | 29/873 [00:18<08:10,  1.72it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.027', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.57it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.50it/s]
resd train e2v:   3%|▎         | 30/873 [00:19<09:01,  1.56it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.38it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.82it/s]
resd train e2v:   4%|▎         | 31/873 [00:20<08:44,  1.60it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.92it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.56it/s]
resd train e2v:   4%|▎         | 32/873 [00:20<09:07,  1.54it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.33it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.92it/s]
resd train e2v:   4%|▍         | 33/873 [00:21<09:21,  1.50it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.12it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.39it/s]
resd train e2v:   4%|▍         | 34/873 [00:22<11:36,  1.20it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.020', 'extract_feat': 0.0, 'forward': '0.038', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.59it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 23.64it/s]
resd train e2v:   4%|▍         | 35/873 [00:23<09:58,  1.40it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.58it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.37it/s]
resd train e2v:   4%|▍         | 36/873 [00:24<09:51,  1.42it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.08it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.40it/s]
resd train e2v:   4%|▍         | 37/873 [00:24<08:53,  1.57it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.15it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.11it/s]
resd train e2v:   4%|▍         | 38/873 [00:25<08:38,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.02it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.88it/s]
resd train e2v:   4%|▍         | 39/873 [00:25<08:31,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.31it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.22it/s]
resd train e2v:   5%|▍         | 40/873 [00:26<08:13,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.74it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.62it/s]
resd train e2v:   5%|▍         | 41/873 [00:26<08:09,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.56it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.77it/s]
resd train e2v:   5%|▍         | 42/873 [00:27<07:56,  1.74it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.42it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.15it/s]
resd train e2v:   5%|▍         | 43/873 [00:27<08:04,  1.71it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.43it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.04it/s]
resd train e2v:   5%|▌         | 44/873 [00:28<07:57,  1.74it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.82it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.89it/s]
resd train e2v:   5%|▌         | 45/873 [00:29<09:04,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.07it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.55it/s]
resd train e2v:   5%|▌         | 46/873 [00:29<08:43,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.44it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.39it/s]
resd train e2v:   5%|▌         | 47/873 [00:30<08:52,  1.55it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.021', 'extract_feat': 0.0, 'forward': '0.037', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 26.35it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 24.52it/s]
resd train e2v:   5%|▌         | 48/873 [00:31<08:38,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.15it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.04it/s]
resd train e2v:   6%|▌         | 49/873 [00:31<08:23,  1.64it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.61it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.14it/s]
resd train e2v:   6%|▌         | 50/873 [00:32<08:03,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.44it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.89it/s]
resd train e2v:   6%|▌         | 51/873 [00:32<08:00,  1.71it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.46it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.94it/s]
resd train e2v:   6%|▌         | 52/873 [00:33<08:34,  1.60it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.12it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.47it/s]
resd train e2v:   6%|▌         | 53/873 [00:34<08:38,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.71it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.67it/s]
resd train e2v:   6%|▌         | 54/873 [00:34<07:54,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.99it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.74it/s]
resd train e2v:   6%|▋         | 55/873 [00:35<07:52,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.85it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 28.99it/s]
resd train e2v:   6%|▋         | 56/873 [00:36<09:08,  1.49it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.42it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.06it/s]
resd train e2v:   7%|▋         | 57/873 [00:36<08:41,  1.56it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.24it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.62it/s]
resd train e2v:   7%|▋         | 58/873 [00:37<10:10,  1.33it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.50it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.58it/s]
resd train e2v:   7%|▋         | 59/873 [00:38<09:20,  1.45it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.28it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.69it/s]
resd train e2v:   7%|▋         | 60/873 [00:38<08:56,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.27it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.50it/s]
resd train e2v:   7%|▋         | 61/873 [00:39<10:16,  1.32it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.13it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 28.92it/s]
resd train e2v:   7%|▋         | 62/873 [00:40<09:39,  1.40it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.18it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.67it/s]
resd train e2v:   7%|▋         | 63/873 [00:40<08:35,  1.57it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.25it/s]

train: X=(873, 768), y=(873,), errors=0

resd val e2v:   0%|          | 0/186 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.13it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.54it/s]
resd val e2v:   1%|          | 1/186 [00:00<01:45,  1.76it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.84it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 28.98it/s]
resd val e2v:   1%|          | 2/186 [00:01<02:09,  1.42it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.59it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.63it/s]
resd val e2v:   2%|▏         | 3/186 [00:01<01:46,  1.71it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.21it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.36it/s]
resd val e2v:   2%|▏         | 4/186 [00:02<01:47,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.84it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.25it/s]
resd val e2v:   3%|▎         | 5/186 [00:03<01:55,  1.56it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.90it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.61it/s]
resd val e2v:   3%|▎         | 6/186 [00:03<01:49,  1.64it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.00it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.80it/s]
resd val e2v:   4%|▍         | 7/186 [00:04<01:44,  1.72it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.97it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.77it/s]
resd val e2v:   4%|▍         | 8/186 [00:04<01:47,  1.65it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.88it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.15it/s]
resd val e2v:   5%|▍         | 9/186 [00:05<01:58,  1.50it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.021', 'extract_feat': 0.0, 'forward': '0.036', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 27.16it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 24.80it/s]
resd val e2v:   5%|▌         | 10/186 [00:06<02:01,  1.45it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.38it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.19it/s]
resd val e2v:   6%|▌         | 11/186 [00:06<01:53,  1.55it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.49it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.28it/s]
resd val e2v:   6%|▋         | 12/186 [00:07<02:04,  1.40it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.93it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.09it/s]
resd val e2v:   7%|▋         | 13/186 [00:08<01:50,  1.57it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.62it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.09it/s]
resd val e2v:   8%|▊         | 14/186 [00:09<01:59,  1.44it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.00it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.84it/s]
resd val e2v:   8%|▊         | 15/186 [00:09<01:52,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.67it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.51it/s]
resd val e2v:   9%|▊         | 16/186 [00:10<01:48,  1.57it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.54it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.16it/s]
resd val e2v:   9%|▉         | 17/186 [00:11<01:55,  1.46it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.29it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.42it/s]
resd val e2v:  10%|▉         | 18/186 [00:11<02:00,  1.40it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.63it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.48it/s]
resd val e2v:  10%|█         | 19/186 [00:12<02:00,  1.38it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.01it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.46it/s]
resd val e2v:  11%|█         | 20/186 [00:13<01:52,  1.47it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.98it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.24it/s]
resd val e2v:  11%|█▏        | 21/186 [00:13<01:53,  1.46it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.021', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.05it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 23.14it/s]
resd val e2v:  12%|█▏        | 22/186 [00:14<01:48,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 28.88it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.15it/s]
resd val e2v:  12%|█▏        | 23/186 [00:15<01:50,  1.47it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.021', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.98it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 23.04it/s]
resd val e2v:  13%|█▎        | 24/186 [00:15<01:44,  1.55it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.86it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.35it/s]
resd val e2v:  13%|█▎        | 25/186 [00:16<01:41,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.26it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.79it/s]
resd val e2v:  14%|█▍        | 26/186 [00:17<01:51,  1.44it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.34it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.48it/s]
resd val e2v:  15%|█▍        | 27/186 [00:17<01:48,  1.46it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 28.86it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.09it/s]
resd val e2v:  15%|█▌        | 28/186 [00:18<01:44,  1.51it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.29it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.12it/s]
resd val e2v:  16%|█▌        | 29/186 [00:19<01:39,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.58it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.11it/s]
resd val e2v:  16%|█▌        | 30/186 [00:19<01:42,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.07it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.25it/s]
resd val e2v:  17%|█▋        | 31/186 [00:20<01:46,  1.45it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.26it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.24it/s]
resd val e2v:  17%|█▋        | 32/186 [00:21<01:45,  1.46it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.23it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.13it/s]
resd val e2v:  18%|█▊        | 33/186 [00:21<01:42,  1.50it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.14it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.52it/s]
resd val e2v:  18%|█▊        | 34/186 [00:22<01:38,  1.55it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.74it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.92it/s]
resd val e2v:  19%|█▉        | 35/186 [00:22<01:28,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.31it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.45it/s]
resd val e2v:  19%|█▉        | 36/186 [00:23<01:28,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.50it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.10it/s]
resd val e2v:  20%|█▉        | 37/186 [00:24<01:27,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 28.84it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 25.78it/s]
resd val e2v:  20%|██        | 38/186 [00:24<01:27,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.32it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.45it/s]
resd val e2v:  21%|██        | 39/186 [00:25<01:26,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.96it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.05it/s]
resd val e2v:  22%|██▏       | 40/186 [00:25<01:24,  1.74it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.78it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.64it/s]
resd val e2v:  22%|██▏       | 41/186 [00:26<01:22,  1.75it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.18it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.65it/s]
resd val e2v:  23%|██▎       | 42/186 [00:26<01:22,  1.75it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.17it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.73it/s]
resd val e2v:  23%|██▎       | 43/186 [00:27<01:23,  1.71it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.07it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.61it/s]
resd val e2v:  24%|██▎       | 44/186 [00:28<01:22,  1.72it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.58it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.59it/s]
resd val e2v:  24%|██▍       | 45/186 [00:28<01:21,  1.74it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.35it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.35it/s]
resd val e2v:  25%|██▍       | 46/186 [00:29<01:20,  1.75it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.67it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.12it/s]
resd val e2v:  25%|██▌       | 47/186 [00:29<01:20,  1.72it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.81it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.37it/s]
resd val e2v:  26%|██▌       | 48/186 [00:30<01:19,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.60it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.22it/s]
resd val e2v:  26%|██▋       | 49/186 [00:30<01:19,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.50it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.55it/s]
resd val e2v:  27%|██▋       | 50/186 [00:31<01:17,  1.75it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.04it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.74it/s]
resd val e2v:  27%|██▋       | 51/186 [00:32<01:16,  1.77it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.97it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.91it/s]
resd val e2v:  28%|██▊       | 52/186 [00:32<01:16,  1.75it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.69it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.94it/s]
resd val e2v:  28%|██▊       | 53/186 [00:33<01:21,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.69it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.63it/s]
resd val e2v:  29%|██▉       | 54/186 [00:34<01:21,  1.62it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.70it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.91it/s]
resd val e2v:  30%|██▉       | 55/186 [00:34<01:18,  1.67it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.22it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.81it/s]
resd val e2v:  30%|███       | 56/186 [00:35<01:16,  1.71it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.78it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.71it/s]
resd val e2v:  31%|███       | 57/186 [00:35<01:16,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.25it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.08it/s]
resd val e2v:  31%|███       | 58/186 [00:36<01:13,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.019', 'extract_feat': 0.0, 'forward': '0.036', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 27.57it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 25.33it/s]
resd val e2v:  32%|███▏      | 59/186 [00:36<01:13,  1.74it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.97it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.38it/s]
resd val e2v:  32%|███▏      | 60/186 [00:37<01:17,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.11it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.57it/s]
resd val e2v:  33%|███▎      | 61/186 [00:38<01:16,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.61it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.60it/s]
resd val e2v:  33%|███▎      | 62/186 [00:38<01:16,  1.62it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.020', 'extract_feat': 0.0, 'forward': '0.036', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 27.00it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 24.13it/s]
resd val e2v:  34%|███▍      | 63/186 [00:39<01:13,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.76it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.49it/s]
resd val e2v:  34%|███▍      | 64/186 [00:39<01:14,  1.64it/s]
  0%|          | 0/1 [00:00<?, ?it/s]

val: X=(186, 768), y=(186,), errors=0

resd test e2v:   0%|          | 0/139 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.36it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.87it/s]
resd test e2v:   1%|          | 1/139 [00:00<01:21,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.29it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.01it/s]
resd test e2v:   1%|▏         | 2/139 [00:01<01:33,  1.46it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.97it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.56it/s]
resd test e2v:   2%|▏         | 3/139 [00:01<01:27,  1.55it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.62it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.72it/s]
resd test e2v:   3%|▎         | 4/139 [00:02<01:22,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.035', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 28.17it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 25.27it/s]
resd test e2v:   4%|▎         | 5/139 [00:03<01:22,  1.62it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.63it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.63it/s]
resd test e2v:   4%|▍         | 6/139 [00:03<01:19,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.72it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.67it/s]
resd test e2v:   5%|▌         | 7/139 [00:04<01:37,  1.36it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.13it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.77it/s]
resd test e2v:   6%|▌         | 8/139 [00:05<01:38,  1.33it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.019', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 28.60it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 26.09it/s]
resd test e2v:   6%|▋         | 9/139 [00:06<01:30,  1.44it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.45it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.08it/s]
resd test e2v:   7%|▋         | 10/139 [00:06<01:28,  1.46it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.43it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.48it/s]
resd test e2v:   8%|▊         | 11/139 [00:07<01:21,  1.57it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.58it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.31it/s]
resd test e2v:   9%|▊         | 12/139 [00:07<01:19,  1.60it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.018', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 28.65it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 25.74it/s]
resd test e2v:   9%|▉         | 13/139 [00:08<01:16,  1.65it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.52it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.36it/s]
resd test e2v:  10%|█         | 14/139 [00:09<01:20,  1.56it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 35.20it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.71it/s]
resd test e2v:  11%|█         | 15/139 [00:09<01:21,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.40it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.93it/s]
resd test e2v:  12%|█▏        | 16/139 [00:10<01:17,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.96it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.74it/s]
resd test e2v:  12%|█▏        | 17/139 [00:10<01:12,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.85it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.20it/s]
resd test e2v:  13%|█▎        | 18/139 [00:11<01:10,  1.72it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.31it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.09it/s]
resd test e2v:  14%|█▎        | 19/139 [00:12<01:17,  1.55it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.03it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.78it/s]
resd test e2v:  14%|█▍        | 20/139 [00:12<01:13,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.49it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.09it/s]
resd test e2v:  15%|█▌        | 21/139 [00:14<01:36,  1.23it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.61it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.40it/s]
resd test e2v:  16%|█▌        | 22/139 [00:14<01:27,  1.34it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.27it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.38it/s]
resd test e2v:  17%|█▋        | 23/139 [00:15<01:20,  1.45it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.41it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.73it/s]
resd test e2v:  17%|█▋        | 24/139 [00:15<01:15,  1.52it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.012', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.69it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.66it/s]
resd test e2v:  18%|█▊        | 25/139 [00:16<01:19,  1.43it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.021', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.20it/s]
resd test e2v:  19%|█▊        | 26/139 [00:17<01:21,  1.38it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.03it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.00it/s]
resd test e2v:  19%|█▉        | 27/139 [00:17<01:15,  1.48it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.90it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.01it/s]
resd test e2v:  20%|██        | 28/139 [00:18<01:20,  1.37it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.33it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.10it/s]
resd test e2v:  21%|██        | 29/139 [00:19<01:18,  1.40it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.032', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.60it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.99it/s]
resd test e2v:  22%|██▏       | 30/139 [00:20<01:17,  1.40it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.40it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.55it/s]
resd test e2v:  22%|██▏       | 31/139 [00:20<01:10,  1.54it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 32.50it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 29.35it/s]
resd test e2v:  23%|██▎       | 32/139 [00:21<01:07,  1.60it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.37it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.75it/s]
resd test e2v:  24%|██▎       | 33/139 [00:22<01:10,  1.50it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.034', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 28.62it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 25.63it/s]
resd test e2v:  24%|██▍       | 34/139 [00:22<01:11,  1.47it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.97it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.53it/s]
resd test e2v:  25%|██▌       | 35/139 [00:23<01:09,  1.50it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.84it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.41it/s]
resd test e2v:  26%|██▌       | 36/139 [00:23<01:06,  1.54it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.87it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.29it/s]
resd test e2v:  27%|██▋       | 37/139 [00:24<01:04,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.65it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.94it/s]
resd test e2v:  27%|██▋       | 38/139 [00:25<01:02,  1.62it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.97it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.35it/s]
resd test e2v:  28%|██▊       | 39/139 [00:25<01:07,  1.49it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.35it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.61it/s]
resd test e2v:  29%|██▉       | 40/139 [00:26<01:01,  1.62it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.76it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.25it/s]
resd test e2v:  29%|██▉       | 41/139 [00:27<00:59,  1.66it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 29.62it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.72it/s]
resd test e2v:  30%|███       | 42/139 [00:27<00:57,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.90it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.02it/s]
resd test e2v:  31%|███       | 43/139 [00:28<00:56,  1.71it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.29it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.17it/s]
resd test e2v:  32%|███▏      | 44/139 [00:28<00:59,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.06it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.67it/s]
resd test e2v:  32%|███▏      | 45/139 [00:29<01:02,  1.50it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.73it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.81it/s]
resd test e2v:  33%|███▎      | 46/139 [00:30<00:59,  1.58it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.05it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.46it/s]
resd test e2v:  34%|███▍      | 47/139 [00:30<00:55,  1.65it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.036', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 26.98it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 24.56it/s]
resd test e2v:  35%|███▍      | 48/139 [00:31<00:55,  1.63it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.017', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.01it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 26.91it/s]
resd test e2v:  35%|███▌      | 49/139 [00:31<00:52,  1.71it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.033', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 30.14it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.81it/s]
resd test e2v:  36%|███▌      | 50/139 [00:32<00:55,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.015', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.74it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.42it/s]
resd test e2v:  37%|███▋      | 51/139 [00:33<00:53,  1.66it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.47it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 28.97it/s]
resd test e2v:  37%|███▋      | 52/139 [00:33<00:51,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.25it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.39it/s]
resd test e2v:  38%|███▊      | 53/139 [00:34<00:49,  1.73it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.89it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.64it/s]
resd test e2v:  39%|███▉      | 54/139 [00:34<00:50,  1.70it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.20it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.85it/s]
resd test e2v:  40%|███▉      | 55/139 [00:35<00:48,  1.75it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.026', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.21it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 21.51it/s]
resd test e2v:  40%|████      | 56/139 [00:35<00:47,  1.75it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.64it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 28.30it/s]
resd test e2v:  41%|████      | 57/139 [00:36<00:48,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.87it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.32it/s]
resd test e2v:  42%|████▏     | 58/139 [00:37<00:51,  1.59it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.030', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 32.87it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.30it/s]
resd test e2v:  42%|████▏     | 59/139 [00:37<00:48,  1.65it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.82it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.32it/s]
resd test e2v:  43%|████▎     | 60/139 [00:38<00:46,  1.69it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.014', 'extract_feat': 0.0, 'forward': '0.029', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 33.18it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 29.75it/s]
resd test e2v:  44%|████▍     | 61/139 [00:39<00:46,  1.68it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.68it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 31.22it/s]
resd test e2v:  45%|████▍     | 62/139 [00:39<00:44,  1.75it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.020', 'extract_feat': 0.0, 'forward': '0.038', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 26.12it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 23.63it/s]
resd test e2v:  45%|████▌     | 63/139 [00:40<00:47,  1.61it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.013', 'extract_feat': 0.0, 'forward': '0.028', 'batch_size': '1', 'rtf': '0.007'}, : 100%|██████████| 1/1 [00:00<00:00, 34.35it/s]
rtf_avg: 0.007: 100%|██████████| 1/1 [00:00<00:00, 30.77it/s]

test: X=(139, 768), y=(139,), errors=0

Saved: /content/drive/MyDrive/New Jurnal Cross/processed_intra_features_e2v_plus_base/resd
Embedding dim: 768
Errors: 0

,dataset,embedding_dim,n_train,n_val,n_test,n_errors,duration_mean,cropped_pct,padded_pct
0,emodb,768,498,71,149,0,2.768886,9.749304,90.250696
1,ravdess,768,704,176,176,0,3.722143,18.750000,81.250000
2,resd,768,873,186,139,0,6.098272,59.599332,40.400668

Saved: /content/drive/MyDrive/New Jurnal Cross/processed_intra_features_e2v_plus_base/emotion2vec_extraction_summary.csv

In [12]:
# Combined duration/crop/padding statistics across all datasets.
combined_meta = []

for dataset_name in DATASETS:
    ds_dir = OUT_DIR / dataset_name
    for split in ["train", "val", "test"]:
        meta = pd.read_csv(ds_dir / f"meta_{split}.csv")
        meta["dataset"] = dataset_name
        meta["split"] = split
        combined_meta.append(meta)

combined_meta = pd.concat(combined_meta, ignore_index=True)

duration_stats_dataset_emotion = summarize_duration_crop_padding(
    combined_meta,
    group_cols=["dataset", "emotion"],
)
duration_stats_dataset_split = summarize_duration_crop_padding(
    combined_meta,
    group_cols=["dataset", "split"],
)
duration_stats_dataset = summarize_duration_crop_padding(
    combined_meta,
    group_cols=["dataset"],
)

duration_stats_dataset_emotion.to_csv(OUT_DIR / "duration_crop_padding_stats_by_dataset_emotion.csv", index=False)
duration_stats_dataset_split.to_csv(OUT_DIR / "duration_crop_padding_stats_by_dataset_split.csv", index=False)
duration_stats_dataset.to_csv(OUT_DIR / "duration_crop_padding_stats_by_dataset.csv", index=False)

display(duration_stats_dataset)
print("Saved duration/crop/padding summary files in:", OUT_DIR)

,dataset,n,duration_mean,duration_std,duration_median,duration_min,duration_max,cropped_n,padded_n,cropped_pct,padded_pct,cropped_seconds_mean,padded_seconds_mean
0,emodb,718,2.768886,1.042156,2.568781,1.213375,8.978250,70,648,9.749304,90.250696,0.101560,1.332674
1,ravdess,1056,3.722143,0.337217,3.670375,3.069750,5.271937,198,858,18.750000,81.250000,0.048339,0.326197
2,resd,1198,6.098272,3.964249,5.148781,0.370000,20.139312,714,484,59.599332,40.400668,2.713720,0.615447

Saved duration/crop/padding summary files in: /content/drive/MyDrive/New Jurnal Cross/processed_intra_features_e2v_plus_base

In [13]:
# Save SHA256 checksums for generated feature/config files.
feature_manifest_rows = []
suffixes = {".npy", ".csv", ".json"}

for path in sorted(OUT_DIR.rglob("*")):
    if path.is_file() and path.suffix.lower() in suffixes:
        # Avoid hashing this manifest while it is being generated.
        if path.name == "generated_feature_file_manifest_sha256.csv":
            continue
        feature_manifest_rows.append({
            "relative_path": str(path.relative_to(OUT_DIR)),
            "absolute_path": str(path),
            "size_bytes": int(path.stat().st_size),
            "sha256": sha256_of_file(path),
        })

feature_file_manifest = pd.DataFrame(feature_manifest_rows)
feature_file_manifest.to_csv(OUT_DIR / "generated_feature_file_manifest_sha256.csv", index=False)

display(feature_file_manifest.head(20))
print("Saved:", OUT_DIR / "generated_feature_file_manifest_sha256.csv")
print("Number of files hashed:", len(feature_file_manifest))

,relative_path,absolute_path,size_bytes,sha256
0,duration_crop_padding_stats_by_dataset.csv,/content/drive/MyDrive/New Jurnal Cross/proces...,608,59847355c88959a0d018334e4a72d2667846a91a26bff1...
1,duration_crop_padding_stats_by_dataset_emotion...,/content/drive/MyDrive/New Jurnal Cross/proces...,2939,1d7490e4a42f3e6eb3ce25ff55bcb648c5594991457b28...
2,duration_crop_padding_stats_by_dataset_split.csv,/content/drive/MyDrive/New Jurnal Cross/proces...,1629,2b9418916ff886e22973c5daf6bb81ab72b08eeeedfc5b...
3,emodb/X_e2v_test.npy,/content/drive/MyDrive/New Jurnal Cross/proces...,457856,7148f2b153de9715d62414906c5b8500a4099be7f50f3b...
4,emodb/X_e2v_train.npy,/content/drive/MyDrive/New Jurnal Cross/proces...,1529984,4eeae3e88bc83f5b7bd3f3df87da192a2a5fd63fca757c...
5,emodb/X_e2v_val.npy,/content/drive/MyDrive/New Jurnal Cross/proces...,218240,48d88eb77e6bbb12deec43337d059eeaa3933f4dda3127...
6,emodb/duration_crop_padding_stats_by_emotion.csv,/content/drive/MyDrive/New Jurnal Cross/proces...,1007,aa8fe89a68029bd54ecb3d891ac7c8f4128058056729d5...
7,emodb/duration_crop_padding_stats_by_split_emo...,/content/drive/MyDrive/New Jurnal Cross/proces...,2719,134c44c338d5a64ce7ae1ed0e87742f4e9313a975eaf3c...
8,emodb/duration_crop_padding_stats_overall.csv,/content/drive/MyDrive/New Jurnal Cross/proces...,313,c56a87a343964f91d3ce80b081e1f0dde441556a54f5d7...
9,emodb/errors.csv,/content/drive/MyDrive/New Jurnal Cross/proces...,37,f98540dfb13c3a245613a5a867b1461600293818650b2a...
10,emodb/feature_config.json,/content/drive/MyDrive/New Jurnal Cross/proces...,987,ddd47cc9bfd2aaef7d7accacd3b5b270b215ee1effc21d...
11,emodb/meta_test.csv,/content/drive/MyDrive/New Jurnal Cross/proces...,44130,a60f36eb20bb3e515502155950239c13fe706b49290504...
12,emodb/meta_train.csv,/content/drive/MyDrive/New Jurnal Cross/proces...,146356,a1af469fc623f6873c4e24a2a0a232759c97779c1c1642...
13,emodb/meta_val.csv,/content/drive/MyDrive/New Jurnal Cross/proces...,21101,ede8ee1dc14255068e33d64ca4060fe1d07152d2fed338...
14,emodb/y_test.npy,/content/drive/MyDrive/New Jurnal Cross/proces...,1320,c20d7cf6c63374861814d02c98293f18862b912ba4e464...
15,emodb/y_train.npy,/content/drive/MyDrive/New Jurnal Cross/proces...,4112,a0a0e06538205a54e151deec650a0c7ecda6a0afb0d15d...
16,emodb/y_val.npy,/content/drive/MyDrive/New Jurnal Cross/proces...,696,3a9297644812d86a307097e5b74992a7f240db4cd549ee...
17,emotion2vec_extraction_summary.csv,/content/drive/MyDrive/New Jurnal Cross/proces...,299,0857c9eb02b1568b59fcfa3177f334958b5840b9055bbb...
18,environment_manifest.json,/content/drive/MyDrive/New Jurnal Cross/proces...,2177,fa86b6f21412f987067461811b0792f194e2443888bddf...
19,ravdess/X_e2v_test.npy,/content/drive/MyDrive/New Jurnal Cross/proces...,540800,53087b8619c66e9cb737ceea68e47438a2de06749adbfd...

Saved: /content/drive/MyDrive/New Jurnal Cross/processed_intra_features_e2v_plus_base/generated_feature_file_manifest_sha256.csv
Number of files hashed: 47

In [14]:
# Final verification.
for dataset_name in DATASETS:
    ds_dir = OUT_DIR / dataset_name

    print("=" * 80)
    print(dataset_name.upper())

    for split in ["train", "val", "test"]:
        X = np.load(ds_dir / f"X_e2v_{split}.npy")
        y = np.load(ds_dir / f"y_{split}.npy")
        meta = pd.read_csv(ds_dir / f"meta_{split}.csv")

        print(f"{split:5s} X={X.shape} y={y.shape} meta={meta.shape} NaN={np.isnan(X).any()}")

        if X.shape[1] != CONFIG["expected_embedding_dim"]:
            raise RuntimeError(
                f"{dataset_name} {split}: expected dim {CONFIG['expected_embedding_dim']}, got {X.shape[1]}"
            )

        print(pd.Series(y).value_counts().sort_index().rename(index=ID_TO_LABEL).to_dict())

print("\nAll checks passed.")

================================================================================
EMODB
train X=(498, 768) y=(498,) meta=(498, 42) NaN=False
{'angry': 98, 'disgust': 73, 'fear': 85, 'happy': 82, 'neutral': 74, 'sad': 86}
val   X=(71, 768) y=(71,) meta=(71, 42) NaN=False
{'angry': 13, 'disgust': 11, 'fear': 13, 'happy': 12, 'neutral': 10, 'sad': 12}
test  X=(149, 768) y=(149,) meta=(149, 42) NaN=False
{'angry': 29, 'disgust': 22, 'fear': 25, 'happy': 24, 'neutral': 22, 'sad': 27}
================================================================================
RAVDESS
train X=(704, 768) y=(704,) meta=(704, 42) NaN=False
{'angry': 128, 'disgust': 128, 'fear': 128, 'happy': 128, 'neutral': 64, 'sad': 128}
val   X=(176, 768) y=(176,) meta=(176, 42) NaN=False
{'angry': 32, 'disgust': 32, 'fear': 32, 'happy': 32, 'neutral': 16, 'sad': 32}
test  X=(176, 768) y=(176,) meta=(176, 42) NaN=False
{'angry': 32, 'disgust': 32, 'fear': 32, 'happy': 32, 'neutral': 16, 'sad': 32}
================================================================================
RESD
train X=(873, 768) y=(873,) meta=(873, 42) NaN=False
{'angry': 154, 'disgust': 135, 'fear': 162, 'happy': 160, 'neutral': 140, 'sad': 122}
val   X=(186, 768) y=(186,) meta=(186, 42) NaN=False
{'angry': 31, 'disgust': 35, 'fear': 32, 'happy': 35, 'neutral': 31, 'sad': 22}
test  X=(139, 768) y=(139,) meta=(139, 42) NaN=False
{'angry': 34, 'disgust': 15, 'fear': 29, 'happy': 23, 'neutral': 20, 'sad': 18}

All checks passed.