In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
# Safe Colab install cell
# IMPORTANT: do not use -U/--upgrade and do not install torch/torchaudio/cuda here.
# Colab already provides compatible torch, torchvision, torchaudio, pandas, and CUDA packages.
!pip -q install "jedi>=0.16"
!pip -q install "funasr==1.4.1" "modelscope==1.39.1" "librosa==0.11.0" "soundfile" "tqdm" "scikit-learn" --upgrade-strategy only-if-needed

import torch, pandas as pd, numpy as np
print("torch:", torch.__version__)
print("pandas:", pd.__version__)
print("numpy:", np.__version__)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 91.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 4.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.8/298.8 kB 28.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.7/89.7 kB 9.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.6/449.6 kB 10.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 976.3/976.3 kB 63.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 146.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.8/155.8 kB 16.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.0/156.0 kB 16.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 113.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 10.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.5/99.5 kB 10.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 109.2 MB/s eta 0:00:00
  Building wheel for oss2 (setup.py) ... done
  Building wheel for aliyun-python-sdk-core (setup.py) ... done
  Building wheel for crcmod (setup.py) ... done
torch: 2.11.0+cu128
pandas: 2.2.2
numpy: 2.0.2

In [3]:
import os
import json
import random
import warnings
import hashlib
import platform
import datetime
import importlib.metadata as im
import numpy as np
import pandas as pd
import librosa
import soundfile as sf

from pathlib import Path
from tqdm import tqdm
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("ignore")

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

BASE_PROJECT = Path("/content/drive/MyDrive/New Jurnal Cross")

CSV_DIR = BASE_PROJECT / "processed_intra_csv"
OUT_DIR = BASE_PROJECT / "processed_intra_sequence_features_plus_base"
TMP_AUDIO_DIR = BASE_PROJECT / "tmp_e2v_seq_audio_plus_base"

OUT_DIR.mkdir(parents=True, exist_ok=True)
TMP_AUDIO_DIR.mkdir(parents=True, exist_ok=True)

DATASETS = ["emodb", "ravdess", "resd"]

CSV_FILES = {
    "emodb": CSV_DIR / "split_emodb_6class_optimized.csv",
    "ravdess": CSV_DIR / "split_ravdess_6class_optimized.csv",
    "resd": CSV_DIR / "split_resd_6class_optimized.csv",
}

LABELS = ["angry", "disgust", "fear", "happy", "neutral", "sad"]

LABEL_TO_ID = {label: i for i, label in enumerate(LABELS)}
ID_TO_LABEL = {i: label for label, i in LABEL_TO_ID.items()}

CONFIG = {
    "sample_rate": 16000,
    "duration": 4.0,

    # handcrafted frame-level
    "n_mfcc": 40,
    "hop_length": 320,   # 20 ms at 16 kHz
    "n_fft": 1024,

    # sequence control
    "target_frames": 200,  # 4 seconds / 20 ms = approx 200 frames

    # emotion2vec
    "model_name": "iic/emotion2vec_plus_base",
    "granularity": "frame",
    "extract_embedding": True,
    "expected_e2v_dim": 768,

    "labels": LABELS,
}

print("OUT_DIR:", OUT_DIR)
for ds, p in CSV_FILES.items():
    print(ds, p.exists(), p)

OUT_DIR: /content/drive/MyDrive/New Jurnal Cross/processed_intra_sequence_features_plus_base
emodb True /content/drive/MyDrive/New Jurnal Cross/processed_intra_csv/split_emodb_6class_optimized.csv
ravdess True /content/drive/MyDrive/New Jurnal Cross/processed_intra_csv/split_ravdess_6class_optimized.csv
resd True /content/drive/MyDrive/New Jurnal Cross/processed_intra_csv/split_resd_6class_optimized.csv

In [4]:
from funasr import AutoModel

e2v_model = AutoModel(
    model=CONFIG["model_name"],
    trust_remote_code=True,
    device="cuda:0",      # ganti "cpu" jika tidak pakai GPU
    disable_update=True   # penting untuk reproducibility
)

print("Loaded:", CONFIG["model_name"])

funasr version: 1.4.1.

2026-08-08 14:13:46,591 | INFO    | modelscope_hub.download | Downloading 11 files from iic/emotion2vec_plus_base@master

Downloading:   0%|          | 0/11 [00:00<?, ?file/s]

config.yaml:   0%|          | 0.00/3.17k [00:00<?, ?B/s]

.DS_Store:   0%|          | 0.00/6.15k [00:00<?, ?B/s]

configuration.json:   0%|          | 0.00/343 [00:00<?, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

logo.png:   0%|          | 0.00/1.85M [00:00<?, ?B/s]

emotion2vec+data.png:   0%|          | 0.00/274k [00:00<?, ?B/s]

emotion2vec+radar.png:   0%|          | 0.00/682k [00:00<?, ?B/s]

model.pt:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

README.md:   0%|          | 0.00/6.15k [00:00<?, ?B/s]

test.wav:   0%|          | 0.00/131k [00:00<?, ?B/s]

tokens.txt:   0%|          | 0.00/120 [00:00<?, ?B/s]

WARNING:root:trust_remote_code: True

Loading remote code failed: model, No module named 'model'
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.0.0.weight, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.0.0.bias, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.1.0.weight, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.1.0.bias, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.2.0.weight, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.2.0.bias, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.3.0.weight, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.3.0.bias, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.proj.weight, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.proj.bias, /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Loaded: iic/emotion2vec_plus_base

In [5]:
def pkg_ver(package_name):
    try:
        return im.version(package_name)
    except Exception:
        return "not installed"


def sha256_of_file(path, chunk_size=1024 * 1024):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(chunk_size), b""):
            h.update(chunk)
    return h.hexdigest()


def find_modelscope_checkpoint(model_id):
    """
    Cari checkpoint ModelScope/FunASR secara robust.
    Untuk iic/emotion2vec_plus_base, biasanya file checkpoint adalah model.pt.
    """
    org, name = model_id.split("/", 1)

    candidate_roots = [
        Path.home() / ".cache" / "modelscope" / "hub" / "models" / org / name,
        Path("/root/.cache/modelscope/hub/models") / org / name,
        Path.home() / ".cache" / "modelscope" / "hub" / org / name,
        Path("/root/.cache/modelscope/hub") / org / name,
        Path.home() / ".cache" / "modelscope" / "models" / f"{org}--{name}",
        Path("/root/.cache/modelscope/models") / f"{org}--{name}",
    ]

    exts = [".pt", ".pth", ".bin", ".safetensors"]
    candidates = []

    for root in candidate_roots:
        if root.exists():
            for ext in exts:
                candidates.extend(root.rglob(f"*{ext}"))

    candidates = sorted(
        list({p.resolve() for p in candidates if p.is_file()}),
        key=lambda p: p.stat().st_size,
        reverse=True
    )

    if len(candidates) == 0:
        return None, []

    return candidates[0], candidates


checkpoint_path, checkpoint_candidates = find_modelscope_checkpoint(CONFIG["model_name"])

if checkpoint_path is not None:
    checkpoint_sha256 = sha256_of_file(checkpoint_path)
    checkpoint_size_mb = checkpoint_path.stat().st_size / (1024 ** 2)
else:
    checkpoint_sha256 = None
    checkpoint_size_mb = None

sequence_environment_manifest = {
    "notebook": "08b_extract_sequence_features_intra.ipynb",
    "task": "emotion2vec frame-level sequence feature extraction plus handcrafted sequence extraction",
    "created_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(),
    "base_project": str(BASE_PROJECT),
    "csv_dir": str(CSV_DIR),
    "out_dir": str(OUT_DIR),
    "tmp_audio_dir": str(TMP_AUDIO_DIR),

    "model_id": CONFIG["model_name"],
    "granularity": CONFIG["granularity"],
    "extract_embedding": CONFIG["extract_embedding"],
    "expected_e2v_dim": CONFIG["expected_e2v_dim"],
    "target_frames": CONFIG["target_frames"],
    "hop_length": CONFIG["hop_length"],
    "sample_rate": CONFIG["sample_rate"],
    "duration": CONFIG["duration"],

    "checkpoint_path": str(checkpoint_path) if checkpoint_path is not None else None,
    "checkpoint_size_mb": round(checkpoint_size_mb, 2) if checkpoint_size_mb is not None else None,
    "checkpoint_sha256": checkpoint_sha256,
    "checkpoint_candidates": [str(p) for p in checkpoint_candidates],

    "python_version": platform.python_version(),
    "funasr_version": pkg_ver("funasr"),
    "modelscope_version": pkg_ver("modelscope"),
    "torch_version": pkg_ver("torch"),
    "torchaudio_version": pkg_ver("torchaudio"),
    "numpy_version": pkg_ver("numpy"),
    "pandas_version": pkg_ver("pandas"),
    "librosa_version": pkg_ver("librosa"),
    "soundfile_version": pkg_ver("soundfile"),
    "scikit_learn_version": pkg_ver("scikit-learn"),
}

with open(OUT_DIR / "sequence_environment_manifest.json", "w") as f:
    json.dump(sequence_environment_manifest, f, indent=2)

print("=" * 80)
print("SEQUENCE FEATURE EXTRACTION REPRODUCIBILITY MANIFEST")
print("=" * 80)
print("Model ID          :", sequence_environment_manifest["model_id"])
print("Checkpoint path   :", sequence_environment_manifest["checkpoint_path"])
print("Checkpoint SHA256 :", sequence_environment_manifest["checkpoint_sha256"])
print("Checkpoint size   :", sequence_environment_manifest["checkpoint_size_mb"], "MB")
print("FunASR version    :", sequence_environment_manifest["funasr_version"])
print("ModelScope ver.   :", sequence_environment_manifest["modelscope_version"])
print("Torch version     :", sequence_environment_manifest["torch_version"])
print("Saved manifest    :", OUT_DIR / "sequence_environment_manifest.json")

================================================================================
SEQUENCE FEATURE EXTRACTION REPRODUCIBILITY MANIFEST
================================================================================
Model ID          : iic/emotion2vec_plus_base
Checkpoint path   : /root/.cache/modelscope/models/iic--emotion2vec_plus_base/snapshots/master/model.pt
Checkpoint SHA256 : 60710b5aae1dbe69bdac8920028fb05882d4314fd09031922b4b61ee9e7aadbd
Checkpoint size   : 1066.44 MB
FunASR version    : 1.4.1
ModelScope ver.   : 1.39.1
Torch version     : 2.11.0+cu128
Saved manifest    : /content/drive/MyDrive/New Jurnal Cross/processed_intra_sequence_features_plus_base/sequence_environment_manifest.json

In [6]:
def load_audio_fixed(path, sr=16000, duration=4.0):
    audio, _ = librosa.load(path, sr=sr, mono=True)

    target_len = int(sr * duration)

    if len(audio) >= target_len:
        start = (len(audio) - target_len) // 2
        audio = audio[start:start + target_len]
    else:
        pad_len = target_len - len(audio)
        if len(audio) > 1:
            audio = np.pad(audio, (0, pad_len), mode="reflect")
        else:
            audio = np.pad(audio, (0, pad_len), mode="constant")

    return audio.astype(np.float32)

In [7]:
def cmvn_per_utterance(mfcc):
    mean = mfcc.mean(axis=1, keepdims=True)
    std = mfcc.std(axis=1, keepdims=True) + 1e-8
    return (mfcc - mean) / std


def extract_handcrafted_sequence(audio, cfg):
    """
    Output shape: [T, 43]
    Components per frame:
      MFCC 40
      RMS 1
      ZCR 1
      F0 1
    """
    sr = cfg["sample_rate"]
    hop = cfg["hop_length"]
    n_fft = cfg["n_fft"]

    mfcc = librosa.feature.mfcc(
        y=audio,
        sr=sr,
        n_mfcc=cfg["n_mfcc"],
        hop_length=hop,
        n_fft=n_fft
    )
    mfcc = cmvn_per_utterance(mfcc)  # [40, T]

    rms = librosa.feature.rms(
        y=audio,
        hop_length=hop,
        frame_length=n_fft
    )  # [1, T]

    zcr = librosa.feature.zero_crossing_rate(
        y=audio,
        hop_length=hop,
        frame_length=n_fft
    )  # [1, T]

    try:
        f0 = librosa.yin(
            audio,
            fmin=50,
            fmax=500,
            sr=sr,
            hop_length=hop,
            frame_length=n_fft
        )
        f0 = np.nan_to_num(f0, nan=0.0, posinf=0.0, neginf=0.0)

        # librosa.yin often returns fmin for unvoiced-ish frames
        f0 = np.where(f0 <= 51, 0.0, f0)
        f0 = f0.reshape(1, -1)
    except Exception:
        f0 = np.zeros((1, mfcc.shape[1]), dtype=np.float32)

    # Samakan panjang frame
    min_t = min(mfcc.shape[1], rms.shape[1], zcr.shape[1], f0.shape[1])

    mfcc = mfcc[:, :min_t]
    rms = rms[:, :min_t]
    zcr = zcr[:, :min_t]
    f0 = f0[:, :min_t]

    feat = np.concatenate([mfcc, rms, zcr, f0], axis=0)  # [43, T]
    feat = feat.T.astype(np.float32)                    # [T, 43]
    feat = np.nan_to_num(feat, nan=0.0, posinf=0.0, neginf=0.0)

    return feat

In [8]:
def parse_e2v_frame_output(res):
    """
    Ambil frame-level embedding dari output FunASR.
    Expected output ideally: [T, D]
    """
    item = res[0] if isinstance(res, list) else res

    possible_keys = [
        "feats",
        "feature",
        "embedding",
        "embeddings",
    ]

    for key in possible_keys:
        if isinstance(item, dict) and key in item:
            arr = np.asarray(item[key], dtype=np.float32)
            return arr

    if isinstance(item, dict):
        candidates = []
        for k, v in item.items():
            try:
                arr = np.asarray(v, dtype=np.float32)
                if arr.ndim >= 2 and arr.size > 100:
                    candidates.append((k, arr))
            except Exception:
                pass

        if len(candidates) > 0:
            candidates = sorted(candidates, key=lambda x: x[1].size, reverse=True)
            print("Using fallback key:", candidates[0][0], "shape:", candidates[0][1].shape)
            return candidates[0][1]

    raise ValueError(f"Cannot parse emotion2vec output: {item.keys() if isinstance(item, dict) else type(item)}")


def extract_e2v_sequence(audio, uid, tmp_dir, cfg):
    tmp_path = tmp_dir / f"{uid}.wav"
    sf.write(tmp_path, audio, cfg["sample_rate"])

    res = e2v_model.generate(
        input=str(tmp_path),
        granularity="frame",
        extract_embedding=True
    )

    emb = parse_e2v_frame_output(res)
    emb = np.asarray(emb, dtype=np.float32)

    # Robust shape handling
    if emb.ndim == 1:
        # fallback: one utterance vector only
        emb = emb.reshape(1, -1)

    elif emb.ndim == 3:
        # e.g. [1, T, D]
        if emb.shape[0] == 1:
            emb = emb[0]
        else:
            emb = emb.reshape(-1, emb.shape[-1])

    elif emb.ndim > 3:
        emb = emb.reshape(-1, emb.shape[-1])

    emb = np.nan_to_num(emb, nan=0.0, posinf=0.0, neginf=0.0)

    expected_dim = cfg.get("expected_e2v_dim", None)
    if expected_dim is not None and emb.shape[-1] != expected_dim:
        raise ValueError(
            f"Unexpected emotion2vec frame embedding dimension: got {emb.shape[-1]}, "
            f"expected {expected_dim}. "
            "This may indicate that the parser extracted the wrong output field."
        )

    return emb.astype(np.float32)

In [9]:
def resample_sequence_to_target(seq, target_frames):
    """
    Linear interpolation along time.
    Input : [T, D]
    Output: [target_frames, D]
    """
    seq = np.asarray(seq, dtype=np.float32)

    if seq.ndim != 2:
        raise ValueError(f"Expected 2D seq, got {seq.shape}")

    T, D = seq.shape

    if T == target_frames:
        return seq

    if T <= 1:
        return np.repeat(seq, target_frames, axis=0)

    old_idx = np.linspace(0, 1, T)
    new_idx = np.linspace(0, 1, target_frames)

    out = np.zeros((target_frames, D), dtype=np.float32)

    for d in range(D):
        out[:, d] = np.interp(new_idx, old_idx, seq[:, d])

    return out.astype(np.float32)


def make_valid_mask(original_frames, target_frames):
    """
    Karena audio sudah crop/pad ke durasi tetap 4 detik,
    kita gunakan mask semua valid setelah resampling.
    """
    return np.ones((target_frames,), dtype=np.float32)

In [10]:
def extract_split_sequence(df_split, dataset_name, split_name, cfg):
    X_hc = []
    X_e2v = []
    masks = []
    rows = []
    errors = []

    split_tmp_dir = TMP_AUDIO_DIR / dataset_name / split_name
    split_tmp_dir.mkdir(parents=True, exist_ok=True)

    target_frames = cfg["target_frames"]

    for idx, row in tqdm(
        df_split.iterrows(),
        total=len(df_split),
        desc=f"{dataset_name} {split_name}"
    ):
        try:
            audio = load_audio_fixed(
                row["filepath"],
                sr=cfg["sample_rate"],
                duration=cfg["duration"]
            )

            uid = str(row["uid"]).replace("/", "_").replace(" ", "_")

            hc_seq = extract_handcrafted_sequence(audio, cfg)
            e2v_seq = extract_e2v_sequence(audio, uid, split_tmp_dir, cfg)

            hc_seq = resample_sequence_to_target(hc_seq, target_frames)
            e2v_seq = resample_sequence_to_target(e2v_seq, target_frames)

            mask = make_valid_mask(target_frames, target_frames)

            X_hc.append(hc_seq)
            X_e2v.append(e2v_seq)
            masks.append(mask)

            rows.append(row.to_dict())

        except Exception as e:
            errors.append({
                "idx": idx,
                "uid": row.get("uid", ""),
                "filepath": row.get("filepath", ""),
                "error": str(e)
            })

    if len(X_hc) == 0:
        raise RuntimeError(f"No valid sequence for {dataset_name} {split_name}")

    X_hc = np.asarray(X_hc, dtype=np.float32)
    X_e2v = np.asarray(X_e2v, dtype=np.float32)
    masks = np.asarray(masks, dtype=np.float32)

    meta = pd.DataFrame(rows)
    y = meta["emotion"].map(LABEL_TO_ID).values.astype(np.int64)
    err = pd.DataFrame(errors)

    return X_e2v, X_hc, masks, y, meta, err

In [11]:
def fit_transform_sequence_scaler(X_train, X_val, X_test):
    """
    X shape: [N, T, D]
    Fit scaler pada train frames only.
    """
    N, T, D = X_train.shape

    scaler = StandardScaler()

    train_2d = X_train.reshape(-1, D)
    scaler.fit(train_2d)

    X_train_scaled = scaler.transform(X_train.reshape(-1, D)).reshape(X_train.shape).astype(np.float32)
    X_val_scaled = scaler.transform(X_val.reshape(-1, D)).reshape(X_val.shape).astype(np.float32)
    X_test_scaled = scaler.transform(X_test.reshape(-1, D)).reshape(X_test.shape).astype(np.float32)

    return X_train_scaled, X_val_scaled, X_test_scaled, scaler

In [12]:
def process_one_dataset_sequence(dataset_name, csv_path, cfg):
    print("=" * 90)
    print(f"Processing sequence features: {dataset_name.upper()}")
    print("=" * 90)

    out_ds = OUT_DIR / dataset_name
    out_ds.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(csv_path)
    df = df[df["emotion"].isin(LABELS)].copy()
    df["label"] = df["emotion"].map(LABEL_TO_ID).astype(int)

    print("Rows:", len(df))
    print("Speakers:", df["speaker"].nunique())
    display(df.groupby(["split", "emotion"]).size().unstack(fill_value=0))

    split_outputs = {}
    all_errors = []

    for split_name in ["train", "val", "test"]:
        df_split = df[df["split"] == split_name].reset_index(drop=True)

        X_e2v, X_hc, mask, y, meta, err = extract_split_sequence(
            df_split=df_split,
            dataset_name=dataset_name,
            split_name=split_name,
            cfg=cfg
        )

        split_outputs[split_name] = {
            "X_e2v": X_e2v,
            "X_hc": X_hc,
            "mask": mask,
            "y": y,
            "meta": meta,
            "err": err
        }

        print(
            split_name,
            "E2V:", X_e2v.shape,
            "HC:", X_hc.shape,
            "mask:", mask.shape,
            "y:", y.shape,
            "errors:", len(err)
        )

        if len(err) > 0:
            err["split"] = split_name
            all_errors.append(err)

    # Scaling train-only
    X_e2v_train, X_e2v_val, X_e2v_test, scaler_e2v = fit_transform_sequence_scaler(
        split_outputs["train"]["X_e2v"],
        split_outputs["val"]["X_e2v"],
        split_outputs["test"]["X_e2v"]
    )

    X_hc_train, X_hc_val, X_hc_test, scaler_hc = fit_transform_sequence_scaler(
        split_outputs["train"]["X_hc"],
        split_outputs["val"]["X_hc"],
        split_outputs["test"]["X_hc"]
    )

    # Save arrays
    save_map = {
        "train": (X_e2v_train, X_hc_train),
        "val": (X_e2v_val, X_hc_val),
        "test": (X_e2v_test, X_hc_test),
    }

    for split_name in ["train", "val", "test"]:
        X_e2v_scaled, X_hc_scaled = save_map[split_name]

        np.save(out_ds / f"X_e2v_seq_{split_name}.npy", X_e2v_scaled)
        np.save(out_ds / f"X_hc_seq_{split_name}.npy", X_hc_scaled)
        np.save(out_ds / f"mask_{split_name}.npy", split_outputs[split_name]["mask"])
        np.save(out_ds / f"y_{split_name}.npy", split_outputs[split_name]["y"])

        split_outputs[split_name]["meta"].to_csv(
            out_ds / f"meta_{split_name}.csv",
            index=False
        )

    # Save scalers
    import pickle

    with open(out_ds / "scaler_e2v_seq.pkl", "wb") as f:
        pickle.dump(scaler_e2v, f)

    with open(out_ds / "scaler_hc_seq.pkl", "wb") as f:
        pickle.dump(scaler_hc, f)

    if len(all_errors) > 0:
        errors_df = pd.concat(all_errors, ignore_index=True)
    else:
        errors_df = pd.DataFrame(columns=["idx", "uid", "filepath", "error", "split"])

    errors_df.to_csv(out_ds / "errors.csv", index=False)

    feature_config = {
        **cfg,
        "dataset": dataset_name,
        "e2v_dim": int(X_e2v_train.shape[-1]),
        "hc_dim": int(X_hc_train.shape[-1]),
        "target_frames": int(cfg["target_frames"]),
        "label_to_id": LABEL_TO_ID,
        "scaling": "StandardScaler fit on train frames only, separately for e2v and handcrafted",
        "note": "sequence-level features for temporal cross-attention; no augmentation",
    }

    with open(out_ds / "feature_config.json", "w") as f:
        json.dump(feature_config, f, indent=2)

    print("Saved:", out_ds)
    print("Errors:", len(errors_df))

    return {
        "dataset": dataset_name,
        "e2v_shape_train": X_e2v_train.shape,
        "hc_shape_train": X_hc_train.shape,
        "n_errors": len(errors_df),
    }

In [13]:
summary_rows = []

for dataset_name in DATASETS:
    result = process_one_dataset_sequence(
        dataset_name=dataset_name,
        csv_path=CSV_FILES[dataset_name],
        cfg=CONFIG
    )
    summary_rows.append(result)

summary_seq = pd.DataFrame(summary_rows)
summary_seq.to_csv(OUT_DIR / "sequence_extraction_summary.csv", index=False)

display(summary_seq)
print("Saved:", OUT_DIR / "sequence_extraction_summary.csv")

==========================================================================================
Processing sequence features: EMODB
==========================================================================================
Rows: 718
Speakers: 10

emotion  angry  disgust  fear  happy  neutral  sad
split
test        29       22    25     24       22   27
train       98       73    85     82       74   86
val         13       11    13     12       10   12

emodb train:   0%|          | 0/498 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:01<00:00,  1.29s/it]
{'load_data': '0.373', 'extract_feat': 0.0, 'forward': '1.293', 'batch_size': '1', 'rtf': '0.323'}, : 100%|██████████| 1/1 [00:01<00:00,  1.29s/it]
rtf_avg: 0.323: 100%|██████████| 1/1 [00:01<00:00,  1.30s/it]
emodb train:   0%|          | 1/498 [00:17<2:24:04, 17.39s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.055', 'extract_feat': 0.0, 'forward': '0.070', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 14.15it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]
emodb train:   0%|          | 2/498 [00:18<1:04:03,  7.75s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.44it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]
emodb train:   1%|          | 3/498 [00:19<38:25,  4.66s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.046', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 21.37it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.46it/s]
emodb train:   1%|          | 4/498 [00:20<26:20,  3.20s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.85it/s]
emodb train:   1%|          | 5/498 [00:21<19:20,  2.35s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.052', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 19.07it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 17.74it/s]
emodb train:   1%|          | 6/498 [00:22<15:43,  1.92s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.051', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 19.25it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 17.88it/s]
emodb train:   1%|▏         | 7/498 [00:23<12:33,  1.53s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.054', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.26it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 15.10it/s]
emodb train:   2%|▏         | 8/498 [00:24<11:15,  1.38s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.16it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.39it/s]
emodb train:   2%|▏         | 9/498 [00:24<10:05,  1.24s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.025', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.94it/s]
emodb train:   2%|▏         | 10/498 [00:25<08:44,  1.07s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.64it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.70it/s]
emodb train:   2%|▏         | 11/498 [00:26<07:58,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.054', 'extract_feat': 0.0, 'forward': '0.071', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.94it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 13.35it/s]
emodb train:   2%|▏         | 12/498 [00:27<08:00,  1.01it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.04it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.21it/s]
emodb train:   3%|▎         | 13/498 [00:28<07:56,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.057', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.20it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.17it/s]
emodb train:   3%|▎         | 14/498 [00:29<07:45,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.064', 'extract_feat': 0.0, 'forward': '0.078', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
emodb train:   3%|▎         | 15/498 [00:30<07:23,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.062', 'extract_feat': 0.0, 'forward': '0.078', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
emodb train:   3%|▎         | 16/498 [00:31<07:11,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.12it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.15it/s]
emodb train:   3%|▎         | 17/498 [00:31<07:13,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.052', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 18.84it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 14.89it/s]
emodb train:   4%|▎         | 18/498 [00:32<06:49,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.062', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.82it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.80it/s]
emodb train:   4%|▍         | 19/498 [00:33<06:22,  1.25it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.070', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 14.14it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
emodb train:   4%|▍         | 20/498 [00:34<06:18,  1.26it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.75it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.23it/s]
emodb train:   4%|▍         | 21/498 [00:34<06:13,  1.28it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.031', 'extract_feat': 0.0, 'forward': '0.050', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 17.39it/s]
emodb train:   4%|▍         | 22/498 [00:35<06:40,  1.19it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 20.14it/s]
emodb train:   5%|▍         | 23/498 [00:36<06:19,  1.25it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.046', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 21.33it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 19.72it/s]
emodb train:   5%|▍         | 24/498 [00:37<06:33,  1.20it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.047', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 21.03it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 19.60it/s]
emodb train:   5%|▌         | 25/498 [00:38<06:21,  1.24it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.04it/s]
emodb train:   5%|▌         | 26/498 [00:38<06:06,  1.29it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.026', 'extract_feat': 0.0, 'forward': '0.043', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.70it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]
emodb train:   5%|▌         | 27/498 [00:39<06:21,  1.23it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.054', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.07it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.84it/s]
emodb train:   6%|▌         | 28/498 [00:40<06:29,  1.21it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.057', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.42it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 15.08it/s]
emodb train:   6%|▌         | 29/498 [00:41<06:59,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.070', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.25it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
emodb train:   6%|▌         | 30/498 [00:42<06:54,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.053', 'extract_feat': 0.0, 'forward': '0.071', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.90it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
emodb train:   6%|▌         | 31/498 [00:43<06:49,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.30it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 23.22it/s]
emodb train:   6%|▋         | 32/498 [00:44<06:54,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.92it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.72it/s]
emodb train:   7%|▋         | 33/498 [00:45<06:55,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.063', 'extract_feat': 0.0, 'forward': '0.085', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
emodb train:   7%|▋         | 34/498 [00:46<07:13,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.056', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.58it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.53it/s]
emodb train:   7%|▋         | 35/498 [00:46<06:37,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.034', 'extract_feat': 0.0, 'forward': '0.052', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 19.16it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 17.81it/s]
emodb train:   7%|▋         | 36/498 [00:47<06:39,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.57it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.53it/s]
emodb train:   7%|▋         | 37/498 [00:48<06:44,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.025', 'extract_feat': 0.0, 'forward': '0.043', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.12it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.14it/s]
emodb train:   8%|▊         | 38/498 [00:49<06:52,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.51it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.46it/s]
emodb train:   8%|▊         | 39/498 [00:50<07:20,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.062', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.89it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
emodb train:   8%|▊         | 40/498 [00:51<07:00,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.066', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.88it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 14.10it/s]
emodb train:   8%|▊         | 41/498 [00:52<07:16,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.99it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.60it/s]
emodb train:   8%|▊         | 42/498 [00:53<07:11,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.055', 'extract_feat': 0.0, 'forward': '0.076', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
emodb train:   9%|▊         | 43/498 [00:54<07:23,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.078', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]
emodb train:   9%|▉         | 44/498 [00:55<06:51,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.059', 'extract_feat': 0.0, 'forward': '0.077', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
emodb train:   9%|▉         | 45/498 [00:56<06:21,  1.19it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.036', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.82it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 15.52it/s]
emodb train:   9%|▉         | 46/498 [00:56<06:17,  1.20it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.047', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 19.22it/s]
emodb train:   9%|▉         | 47/498 [00:57<06:08,  1.22it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.01it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 12.99it/s]
emodb train:  10%|▉         | 48/498 [00:58<07:10,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.46it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.51it/s]
emodb train:  10%|▉         | 49/498 [00:59<06:54,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.047', 'extract_feat': 0.0, 'forward': '0.066', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.09it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.27it/s]
emodb train:  10%|█         | 50/498 [01:00<06:26,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.034', 'extract_feat': 0.0, 'forward': '0.057', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.45it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.48it/s]
emodb train:  10%|█         | 51/498 [01:01<06:07,  1.22it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.15it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.23it/s]
emodb train:  10%|█         | 52/498 [01:01<05:54,  1.26it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.036', 'extract_feat': 0.0, 'forward': '0.056', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.58it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.44it/s]
emodb train:  11%|█         | 53/498 [01:03<06:41,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.031', 'extract_feat': 0.0, 'forward': '0.048', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.36it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.36it/s]
emodb train:  11%|█         | 54/498 [01:03<06:18,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.021', 'extract_feat': 0.0, 'forward': '0.038', 'batch_size': '1', 'rtf': '0.009'}, : 100%|██████████| 1/1 [00:00<00:00, 26.20it/s]
rtf_avg: 0.009: 100%|██████████| 1/1 [00:00<00:00, 23.77it/s]
emodb train:  11%|█         | 55/498 [01:04<06:22,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.054', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.24it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.34it/s]
emodb train:  11%|█         | 56/498 [01:05<06:34,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.056', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.64it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.36it/s]
emodb train:  11%|█▏        | 57/498 [01:06<06:41,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.073', 'extract_feat': 0.0, 'forward': '0.088', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
emodb train:  12%|█▏        | 58/498 [01:07<06:19,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.069', 'extract_feat': 0.0, 'forward': '0.085', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
emodb train:  12%|█▏        | 59/498 [01:08<06:35,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 19.43it/s]
emodb train:  12%|█▏        | 60/498 [01:09<06:37,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.046', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.60it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 19.53it/s]
emodb train:  12%|█▏        | 61/498 [01:10<06:47,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.059', 'extract_feat': 0.0, 'forward': '0.074', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.42it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.78it/s]
emodb train:  12%|█▏        | 62/498 [01:11<06:24,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.046', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
emodb train:  13%|█▎        | 63/498 [01:12<06:28,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.46it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.12it/s]
emodb train:  13%|█▎        | 64/498 [01:12<05:55,  1.22it/s]
  0%|          | 0/1 [00:00<?, ?it/s]

train E2V: (498, 200, 768) HC: (498, 200, 43) mask: (498, 200) y: (498,) errors: 0

emodb val:   0%|          | 0/71 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.064', 'extract_feat': 0.0, 'forward': '0.080', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
emodb val:   1%|▏         | 1/71 [00:00<00:55,  1.25it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.062', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 15.95it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.70it/s]
emodb val:   3%|▎         | 2/71 [00:01<00:53,  1.29it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.60it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.63it/s]
emodb val:   4%|▍         | 3/71 [00:02<00:57,  1.18it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.048', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 19.29it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 15.86it/s]
emodb val:   6%|▌         | 4/71 [00:03<00:58,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.025', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.18it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 17.87it/s]
emodb val:   7%|▋         | 5/71 [00:04<00:55,  1.18it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.047', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 21.06it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 19.39it/s]
emodb val:   8%|▊         | 6/71 [00:05<00:55,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.047', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 21.09it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 17.84it/s]
emodb val:  10%|▉         | 7/71 [00:05<00:52,  1.23it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.28it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.96it/s]
emodb val:  11%|█▏        | 8/71 [00:06<00:48,  1.29it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.11it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 14.99it/s]
emodb val:  13%|█▎        | 9/71 [00:07<00:50,  1.23it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.32it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 23.37it/s]
emodb val:  14%|█▍        | 10/71 [00:08<00:51,  1.19it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.034', 'extract_feat': 0.0, 'forward': '0.051', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 19.38it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 18.19it/s]
emodb val:  15%|█▌        | 11/71 [00:09<00:51,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.028', 'extract_feat': 0.0, 'forward': '0.046', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 21.27it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 15.67it/s]
emodb val:  17%|█▋        | 12/71 [00:10<00:53,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.47it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.23it/s]
emodb val:  18%|█▊        | 13/71 [00:11<00:55,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.049', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.27it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.60it/s]
emodb val:  20%|█▉        | 14/71 [00:12<00:54,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.47it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.44it/s]
emodb val:  21%|██        | 15/71 [00:13<00:55,  1.01it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.056', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.51it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.18it/s]
emodb val:  23%|██▎       | 16/71 [00:14<00:53,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.98it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.93it/s]
emodb val:  24%|██▍       | 17/71 [00:15<00:50,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.045', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.75it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
emodb val:  25%|██▌       | 18/71 [00:16<00:50,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.25it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.33it/s]
emodb val:  27%|██▋       | 19/71 [00:16<00:45,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.069', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.19it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
emodb val:  28%|██▊       | 20/71 [00:17<00:47,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.048', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.21it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.34it/s]
emodb val:  30%|██▉       | 21/71 [00:18<00:43,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.81it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.82it/s]
emodb val:  31%|███       | 22/71 [00:19<00:40,  1.20it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.39it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.40it/s]
emodb val:  32%|███▏      | 23/71 [00:20<00:40,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.92it/s]
emodb val:  34%|███▍      | 24/71 [00:20<00:37,  1.24it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.025', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.24it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 15.93it/s]
emodb val:  35%|███▌      | 25/71 [00:21<00:40,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.10it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.94it/s]
emodb val:  37%|███▋      | 26/71 [00:22<00:37,  1.19it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.10it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.19it/s]
emodb val:  38%|███▊      | 27/71 [00:23<00:39,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.061', 'extract_feat': 0.0, 'forward': '0.076', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
emodb val:  39%|███▉      | 28/71 [00:24<00:38,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.49it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.47it/s]
emodb val:  41%|████      | 29/71 [00:25<00:35,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.062', 'extract_feat': 0.0, 'forward': '0.078', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
emodb val:  42%|████▏     | 30/71 [00:26<00:33,  1.21it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.74it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.93it/s]
emodb val:  44%|████▎     | 31/71 [00:27<00:34,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.89it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.74it/s]
emodb val:  45%|████▌     | 32/71 [00:27<00:32,  1.19it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.40it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 23.08it/s]
emodb val:  46%|████▋     | 33/71 [00:28<00:30,  1.24it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.027', 'extract_feat': 0.0, 'forward': '0.044', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.30it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.52it/s]
emodb val:  48%|████▊     | 34/71 [00:29<00:34,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.047', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.64it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.74it/s]
emodb val:  49%|████▉     | 35/71 [00:30<00:32,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.94it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.67it/s]
emodb val:  51%|█████     | 36/71 [00:31<00:33,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.048', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 19.07it/s]
emodb val:  52%|█████▏    | 37/71 [00:32<00:31,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.046', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.50it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]
emodb val:  54%|█████▎    | 38/71 [00:33<00:31,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 17.01it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.92it/s]
emodb val:  55%|█████▍    | 39/71 [00:34<00:28,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 17.02it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.70it/s]
emodb val:  56%|█████▋    | 40/71 [00:35<00:28,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.052', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 18.91it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 17.67it/s]
emodb val:  58%|█████▊    | 41/71 [00:36<00:29,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.069', 'extract_feat': 0.0, 'forward': '0.086', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
emodb val:  59%|█████▉    | 42/71 [00:37<00:30,  1.04s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.059', 'extract_feat': 0.0, 'forward': '0.080', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
emodb val:  61%|██████    | 43/71 [00:38<00:28,  1.01s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.068', 'extract_feat': 0.0, 'forward': '0.087', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
emodb val:  62%|██████▏   | 44/71 [00:39<00:27,  1.00s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.85it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 15.05it/s]
emodb val:  63%|██████▎   | 45/71 [00:41<00:30,  1.19s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.38it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 13.71it/s]
emodb val:  65%|██████▍   | 46/71 [00:42<00:27,  1.11s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.70it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.66it/s]
emodb val:  66%|██████▌   | 47/71 [00:42<00:23,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.70it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.41it/s]
emodb val:  68%|██████▊   | 48/71 [00:43<00:20,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.057', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.28it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.08it/s]
emodb val:  69%|██████▉   | 49/71 [00:44<00:19,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.22it/s]
emodb val:  70%|███████   | 50/71 [00:45<00:18,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.057', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.25it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.20it/s]
emodb val:  72%|███████▏  | 51/71 [00:46<00:17,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.066', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 14.98it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.06it/s]
emodb val:  73%|███████▎  | 52/71 [00:47<00:17,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.062', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 15.97it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.09it/s]
emodb val:  75%|███████▍  | 53/71 [00:47<00:15,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.054', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.24it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 15.93it/s]
emodb val:  76%|███████▌  | 54/71 [00:48<00:14,  1.19it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.58it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.54it/s]
emodb val:  77%|███████▋  | 55/71 [00:49<00:14,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.72it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.46it/s]
emodb val:  79%|███████▉  | 56/71 [00:50<00:13,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.070', 'extract_feat': 0.0, 'forward': '0.092', 'batch_size': '1', 'rtf': '0.023'}, : 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
rtf_avg: 0.023: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
emodb val:  80%|████████  | 57/71 [00:51<00:13,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.055', 'extract_feat': 0.0, 'forward': '0.071', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 14.01it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
emodb val:  82%|████████▏ | 58/71 [00:52<00:12,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 14.89it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.65it/s]
emodb val:  83%|████████▎ | 59/71 [00:53<00:11,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.77it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.62it/s]
emodb val:  85%|████████▍ | 60/71 [00:54<00:10,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.048', 'extract_feat': 0.0, 'forward': '0.068', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.55it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.44it/s]
emodb val:  86%|████████▌ | 61/71 [00:55<00:09,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.42it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.41it/s]
emodb val:  87%|████████▋ | 62/71 [00:56<00:08,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.88it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.81it/s]
emodb val:  89%|████████▊ | 63/71 [00:57<00:07,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.14it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.22it/s]
emodb val:  90%|█████████ | 64/71 [00:58<00:06,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.034', 'extract_feat': 0.0, 'forward': '0.051', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 18.10it/s]
emodb val:  92%|█████████▏| 65/71 [00:59<00:05,  1.04it/s]

val E2V: (71, 200, 768) HC: (71, 200, 43) mask: (71, 200) y: (71,) errors: 0

emodb test:   0%|          | 0/149 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.61it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.88it/s]
emodb test:   1%|          | 1/149 [00:01<02:30,  1.02s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 17.06it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 16.02it/s]
emodb test:   1%|▏         | 2/149 [00:01<02:25,  1.01it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.13it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.92it/s]
emodb test:   2%|▏         | 3/149 [00:02<02:09,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 17.01it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.77it/s]
emodb test:   3%|▎         | 4/149 [00:03<01:59,  1.21it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.031', 'extract_feat': 0.0, 'forward': '0.049', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.57it/s]
emodb test:   3%|▎         | 5/149 [00:04<02:04,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.34it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.30it/s]
emodb test:   4%|▍         | 6/149 [00:05<02:05,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.036', 'extract_feat': 0.0, 'forward': '0.056', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.61it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.45it/s]
emodb test:   5%|▍         | 7/149 [00:06<02:11,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.032', 'extract_feat': 0.0, 'forward': '0.052', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 19.09it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 17.70it/s]
emodb test:   5%|▌         | 8/149 [00:07<02:14,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.75it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.65it/s]
emodb test:   6%|▌         | 9/149 [00:08<02:14,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.068', 'extract_feat': 0.0, 'forward': '0.087', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
emodb test:   7%|▋         | 10/149 [00:09<02:06,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.066', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.92it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 14.14it/s]
emodb test:   7%|▋         | 11/149 [00:10<02:06,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.16it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.19it/s]
emodb test:   8%|▊         | 12/149 [00:10<01:59,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.047', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.84it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.82it/s]
emodb test:   9%|▊         | 13/149 [00:11<02:00,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.052', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.70it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.90it/s]
emodb test:   9%|▉         | 14/149 [00:12<02:04,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.025', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.24it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 21.31it/s]
emodb test:  10%|█         | 15/149 [00:13<01:56,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.034', 'extract_feat': 0.0, 'forward': '0.057', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.36it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 15.42it/s]
emodb test:  11%|█         | 16/149 [00:14<01:58,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.056', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.65it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 15.79it/s]
emodb test:  11%|█▏        | 17/149 [00:15<01:59,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.058', 'extract_feat': 0.0, 'forward': '0.081', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
emodb test:  12%|█▏        | 18/149 [00:16<02:02,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.062', 'extract_feat': 0.0, 'forward': '0.083', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
emodb test:  13%|█▎        | 19/149 [00:17<02:02,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.067', 'extract_feat': 0.0, 'forward': '0.089', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
emodb test:  13%|█▎        | 20/149 [00:18<01:52,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.52it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.85it/s]
emodb test:  14%|█▍        | 21/149 [00:18<01:48,  1.18it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.048', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.44it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.94it/s]
emodb test:  15%|█▍        | 22/149 [00:19<01:43,  1.23it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.30it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.93it/s]
emodb test:  15%|█▌        | 23/149 [00:20<01:38,  1.27it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.046', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 21.45it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
emodb test:  16%|█▌        | 24/149 [00:21<01:42,  1.21it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.034', 'extract_feat': 0.0, 'forward': '0.052', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 19.20it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 17.99it/s]
emodb test:  17%|█▋        | 25/149 [00:22<01:45,  1.18it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.04it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 15.89it/s]
emodb test:  17%|█▋        | 26/149 [00:22<01:40,  1.23it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.068', 'extract_feat': 0.0, 'forward': '0.084', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
emodb test:  18%|█▊        | 27/149 [00:23<01:40,  1.22it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.43it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.54it/s]
emodb test:  19%|█▉        | 28/149 [00:24<01:44,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.076', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
emodb test:  19%|█▉        | 29/149 [00:25<01:48,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.060', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
emodb test:  20%|██        | 30/149 [00:26<01:53,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.028', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.90it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.75it/s]
emodb test:  21%|██        | 31/149 [00:27<01:54,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.36it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.73it/s]
emodb test:  21%|██▏       | 32/149 [00:28<01:47,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.69it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.63it/s]
emodb test:  22%|██▏       | 33/149 [00:29<01:48,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.33it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.46it/s]
emodb test:  23%|██▎       | 34/149 [00:30<01:49,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.64it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.81it/s]
emodb test:  23%|██▎       | 35/149 [00:31<01:42,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.047', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 21.09it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]
emodb test:  24%|██▍       | 36/149 [00:31<01:35,  1.18it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.89it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.39it/s]
emodb test:  25%|██▍       | 37/149 [00:32<01:38,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.031', 'extract_feat': 0.0, 'forward': '0.048', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.68it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 17.27it/s]
emodb test:  26%|██▌       | 38/149 [00:33<01:34,  1.18it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.054', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.27it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.98it/s]
emodb test:  26%|██▌       | 39/149 [00:34<01:39,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.09it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 23.09it/s]
emodb test:  27%|██▋       | 40/149 [00:35<01:31,  1.19it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.09it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.16it/s]
emodb test:  28%|██▊       | 41/149 [00:36<01:37,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.068', 'extract_feat': 0.0, 'forward': '0.083', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
emodb test:  28%|██▊       | 42/149 [00:37<01:39,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.050', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.82it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 14.11it/s]
emodb test:  29%|██▉       | 43/149 [00:38<01:39,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.28it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.95it/s]
emodb test:  30%|██▉       | 44/149 [00:39<01:31,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.043', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.06it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 21.22it/s]
emodb test:  30%|███       | 45/149 [00:40<01:32,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.79it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.94it/s]
emodb test:  31%|███       | 46/149 [00:40<01:29,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.99it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 15.90it/s]
emodb test:  32%|███▏      | 47/149 [00:41<01:30,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.80it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.72it/s]
emodb test:  32%|███▏      | 48/149 [00:42<01:30,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.028', 'extract_feat': 0.0, 'forward': '0.045', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.92it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 18.52it/s]
emodb test:  33%|███▎      | 49/149 [00:43<01:30,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.91it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.80it/s]
emodb test:  34%|███▎      | 50/149 [00:44<01:31,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.050', 'extract_feat': 0.0, 'forward': '0.072', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.61it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
emodb test:  34%|███▍      | 51/149 [00:45<01:27,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.88it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.78it/s]
emodb test:  35%|███▍      | 52/149 [00:46<01:26,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.81it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.80it/s]
emodb test:  36%|███▌      | 53/149 [00:47<01:19,  1.20it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.056', 'extract_feat': 0.0, 'forward': '0.074', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
emodb test:  36%|███▌      | 54/149 [00:48<01:23,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.055', 'extract_feat': 0.0, 'forward': '0.081', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
emodb test:  37%|███▋      | 55/149 [00:48<01:23,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.15it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 17.02it/s]
emodb test:  38%|███▊      | 56/149 [00:49<01:24,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.44it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.35it/s]
emodb test:  38%|███▊      | 57/149 [00:50<01:18,  1.18it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.062', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
emodb test:  39%|███▉      | 58/149 [00:51<01:14,  1.23it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.51it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.50it/s]
emodb test:  40%|███▉      | 59/149 [00:52<01:18,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.052', 'extract_feat': 0.0, 'forward': '0.069', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.30it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
emodb test:  40%|████      | 60/149 [00:53<01:14,  1.20it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.048', 'extract_feat': 0.0, 'forward': '0.069', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.36it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.58it/s]
emodb test:  41%|████      | 61/149 [00:54<01:18,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.057', 'extract_feat': 0.0, 'forward': '0.080', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
emodb test:  42%|████▏     | 62/149 [00:54<01:13,  1.18it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.055', 'extract_feat': 0.0, 'forward': '0.083', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
emodb test:  42%|████▏     | 63/149 [00:55<01:14,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.068', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.66it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.88it/s]
emodb test:  43%|████▎     | 64/149 [00:56<01:13,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]

test E2V: (149, 200, 768) HC: (149, 200, 43) mask: (149, 200) y: (149,) errors: 0
Saved: /content/drive/MyDrive/New Jurnal Cross/processed_intra_sequence_features_plus_base/emodb
Errors: 0
==========================================================================================
Processing sequence features: RAVDESS
==========================================================================================
Rows: 1056
Speakers: 24

emotion  angry  disgust  fear  happy  neutral  sad
split
test        32       32    32     32       16   32
train      128      128   128    128       64  128
val         32       32    32     32       16   32

ravdess train:   0%|          | 0/704 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.054', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.13it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 17.22it/s]
ravdess train:   0%|          | 1/704 [00:03<36:11,  3.09s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.034', 'extract_feat': 0.0, 'forward': '0.049', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.71it/s]
ravdess train:   0%|          | 2/704 [00:04<21:42,  1.86s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.064', 'extract_feat': 0.0, 'forward': '0.080', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
ravdess train:   0%|          | 3/704 [00:05<17:41,  1.51s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.052', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.66it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.88it/s]
ravdess train:   1%|          | 4/704 [00:07<20:11,  1.73s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.86it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.77it/s]
ravdess train:   1%|          | 5/704 [00:08<20:04,  1.72s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.30it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.29it/s]
ravdess train:   1%|          | 6/704 [00:11<22:03,  1.90s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.051', 'extract_feat': 0.0, 'forward': '0.071', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.98it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
ravdess train:   1%|          | 7/704 [00:11<17:43,  1.53s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.051', 'extract_feat': 0.0, 'forward': '0.074', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.44it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]
ravdess train:   1%|          | 8/704 [00:12<14:45,  1.27s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.054', 'extract_feat': 0.0, 'forward': '0.081', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
ravdess train:   1%|▏         | 9/704 [00:13<14:12,  1.23s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.40it/s]
ravdess train:   1%|▏         | 10/704 [00:14<13:04,  1.13s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.083', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
ravdess train:   2%|▏         | 11/704 [00:15<12:27,  1.08s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  9.77it/s]
{'load_data': '0.086', 'extract_feat': 0.0, 'forward': '0.102', 'batch_size': '1', 'rtf': '0.026'}, : 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]
rtf_avg: 0.026: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
ravdess train:   2%|▏         | 12/704 [00:16<12:08,  1.05s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.058', 'extract_feat': 0.0, 'forward': '0.074', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
ravdess train:   2%|▏         | 13/704 [00:17<11:56,  1.04s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.070', 'extract_feat': 0.0, 'forward': '0.087', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
ravdess train:   2%|▏         | 14/704 [00:18<11:14,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.049', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.91it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
ravdess train:   2%|▏         | 15/704 [00:19<11:03,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.055', 'extract_feat': 0.0, 'forward': '0.073', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
ravdess train:   2%|▏         | 16/704 [00:20<10:56,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.026', 'extract_feat': 0.0, 'forward': '0.044', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.24it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.45it/s]
ravdess train:   2%|▏         | 17/704 [00:21<11:08,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.027', 'extract_feat': 0.0, 'forward': '0.044', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.31it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.37it/s]
ravdess train:   3%|▎         | 18/704 [00:22<10:51,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.25it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.36it/s]
ravdess train:   3%|▎         | 19/704 [00:23<10:49,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.38it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.44it/s]
ravdess train:   3%|▎         | 20/704 [00:24<11:00,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.057', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.13it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 15.06it/s]
ravdess train:   3%|▎         | 21/704 [00:25<10:35,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.064', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
ravdess train:   3%|▎         | 22/704 [00:25<10:01,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.65it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.66it/s]
ravdess train:   3%|▎         | 23/704 [00:26<09:26,  1.20it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.028', 'extract_feat': 0.0, 'forward': '0.046', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 20.94it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 18.37it/s]
ravdess train:   3%|▎         | 24/704 [00:27<09:51,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.050', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.74it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
ravdess train:   4%|▎         | 25/704 [00:28<10:20,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.051', 'extract_feat': 0.0, 'forward': '0.069', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.35it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.65it/s]
ravdess train:   4%|▎         | 26/704 [00:29<10:15,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.049', 'extract_feat': 0.0, 'forward': '0.080', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
ravdess train:   4%|▍         | 27/704 [00:30<10:23,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.016', 'extract_feat': 0.0, 'forward': '0.031', 'batch_size': '1', 'rtf': '0.008'}, : 100%|██████████| 1/1 [00:00<00:00, 31.26it/s]
rtf_avg: 0.008: 100%|██████████| 1/1 [00:00<00:00, 27.78it/s]
ravdess train:   4%|▍         | 28/704 [00:32<13:42,  1.22s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.025', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.19it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.98it/s]
ravdess train:   4%|▍         | 29/704 [00:33<12:36,  1.12s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.049', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.55it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.83it/s]
ravdess train:   4%|▍         | 30/704 [00:33<11:15,  1.00s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.047', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.35it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.80it/s]
ravdess train:   4%|▍         | 31/704 [00:34<10:24,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.60it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.30it/s]
ravdess train:   5%|▍         | 32/704 [00:35<09:42,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.47it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.71it/s]
ravdess train:   5%|▍         | 33/704 [00:36<09:16,  1.21it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.14it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.25it/s]
ravdess train:   5%|▍         | 34/704 [00:37<10:07,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.16it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.00it/s]
ravdess train:   5%|▍         | 35/704 [00:38<10:14,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.031', 'extract_feat': 0.0, 'forward': '0.048', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.59it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.99it/s]
ravdess train:   5%|▌         | 36/704 [00:39<10:13,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.28it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.25it/s]
ravdess train:   5%|▌         | 37/704 [00:39<09:25,  1.18it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.70it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]
ravdess train:   5%|▌         | 38/704 [00:40<09:03,  1.23it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.034', 'extract_feat': 0.0, 'forward': '0.051', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 19.37it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 18.05it/s]
ravdess train:   6%|▌         | 39/704 [00:41<09:39,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.050', 'extract_feat': 0.0, 'forward': '0.078', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
ravdess train:   6%|▌         | 40/704 [00:42<10:06,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.071', 'extract_feat': 0.0, 'forward': '0.086', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
ravdess train:   6%|▌         | 41/704 [00:43<09:57,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.053', 'extract_feat': 0.0, 'forward': '0.070', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.18it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
ravdess train:   6%|▌         | 42/704 [00:44<10:05,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.028', 'extract_feat': 0.0, 'forward': '0.046', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 21.32it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.10it/s]
ravdess train:   6%|▌         | 43/704 [00:45<10:42,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.77it/s]
ravdess train:   6%|▋         | 44/704 [00:46<09:46,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.031', 'extract_feat': 0.0, 'forward': '0.047', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.85it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 19.34it/s]
ravdess train:   6%|▋         | 45/704 [00:47<09:58,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.066', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.07it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]
ravdess train:   7%|▋         | 46/704 [00:47<09:26,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.57it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.42it/s]
ravdess train:   7%|▋         | 47/704 [00:48<09:46,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.049', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.85it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
ravdess train:   7%|▋         | 48/704 [00:49<10:14,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.57it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.50it/s]
ravdess train:   7%|▋         | 49/704 [00:50<09:37,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.047', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.14it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.20it/s]
ravdess train:   7%|▋         | 50/704 [00:51<09:32,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.026', 'extract_feat': 0.0, 'forward': '0.044', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.57it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 19.12it/s]
ravdess train:   7%|▋         | 51/704 [00:52<09:37,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.062', 'extract_feat': 0.0, 'forward': '0.082', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
ravdess train:   7%|▋         | 52/704 [00:53<09:55,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.24it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.23it/s]
ravdess train:   8%|▊         | 53/704 [00:54<09:56,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.060', 'extract_feat': 0.0, 'forward': '0.087', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
ravdess train:   8%|▊         | 54/704 [00:55<10:04,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.046', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.43it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 17.90it/s]
ravdess train:   8%|▊         | 55/704 [00:56<10:09,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.056', 'extract_feat': 0.0, 'forward': '0.076', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
ravdess train:   8%|▊         | 56/704 [00:57<10:18,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.72it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.72it/s]
ravdess train:   8%|▊         | 57/704 [00:58<10:05,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.057', 'extract_feat': 0.0, 'forward': '0.074', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
ravdess train:   8%|▊         | 58/704 [00:58<09:23,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.069', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.28it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
ravdess train:   8%|▊         | 59/704 [00:59<09:34,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.07it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 15.90it/s]
ravdess train:   9%|▊         | 60/704 [01:00<09:19,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.048', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.56it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.90it/s]
ravdess train:   9%|▊         | 61/704 [01:01<09:26,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.028', 'extract_feat': 0.0, 'forward': '0.045', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.67it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]
ravdess train:   9%|▉         | 62/704 [01:02<09:43,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.056', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.77it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.72it/s]
ravdess train:   9%|▉         | 63/704 [01:03<09:15,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.88it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.85it/s]

train E2V: (704, 200, 768) HC: (704, 200, 43) mask: (704, 200) y: (704,) errors: 0

ravdess val:   0%|          | 0/176 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.026', 'extract_feat': 0.0, 'forward': '0.046', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 21.39it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 19.77it/s]
ravdess val:   1%|          | 1/176 [00:00<02:40,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.048', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.58it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 16.72it/s]
ravdess val:   1%|          | 2/176 [00:01<02:47,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.069', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.40it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.67it/s]
ravdess val:   2%|▏         | 3/176 [00:02<02:43,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.061', 'extract_feat': 0.0, 'forward': '0.077', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.78it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
ravdess val:   2%|▏         | 4/176 [00:03<02:46,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.050', 'extract_feat': 0.0, 'forward': '0.073', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.61it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
ravdess val:   3%|▎         | 5/176 [00:04<02:44,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.077', 'extract_feat': 0.0, 'forward': '0.092', 'batch_size': '1', 'rtf': '0.023'}, : 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
rtf_avg: 0.023: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
ravdess val:   3%|▎         | 6/176 [00:05<02:46,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.88it/s]
ravdess val:   4%|▍         | 7/176 [00:06<02:29,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.026', 'extract_feat': 0.0, 'forward': '0.051', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 18.24it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 16.11it/s]
ravdess val:   5%|▍         | 8/176 [00:07<02:33,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.50it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.58it/s]
ravdess val:   5%|▌         | 9/176 [00:08<02:32,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.56it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.62it/s]
ravdess val:   6%|▌         | 10/176 [00:10<03:42,  1.34s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.063', 'extract_feat': 0.0, 'forward': '0.086', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
ravdess val:   6%|▋         | 11/176 [00:11<03:12,  1.17s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.048', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.61it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 19.15it/s]
ravdess val:   7%|▋         | 12/176 [00:12<03:00,  1.10s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.025', 'extract_feat': 0.0, 'forward': '0.043', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.75it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.97it/s]
ravdess val:   7%|▋         | 13/176 [00:13<02:39,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.053', 'extract_feat': 0.0, 'forward': '0.074', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
ravdess val:   8%|▊         | 14/176 [00:14<02:38,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.048', 'extract_feat': 0.0, 'forward': '0.070', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 14.09it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
ravdess val:   9%|▊         | 15/176 [00:15<02:46,  1.04s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.42it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.21it/s]
ravdess val:   9%|▉         | 16/176 [00:16<02:33,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.064', 'extract_feat': 0.0, 'forward': '0.085', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
ravdess val:  10%|▉         | 17/176 [00:16<02:21,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.048', 'extract_feat': 0.0, 'forward': '0.078', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
ravdess val:  10%|█         | 18/176 [00:17<02:23,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.021', 'extract_feat': 0.0, 'forward': '0.038', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.68it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 23.37it/s]
ravdess val:  11%|█         | 19/176 [00:18<02:24,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.53it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.66it/s]
ravdess val:  11%|█▏        | 20/176 [00:19<02:25,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.74it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.94it/s]
ravdess val:  12%|█▏        | 21/176 [00:20<02:18,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.055', 'extract_feat': 0.0, 'forward': '0.073', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.64it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
ravdess val:  12%|█▎        | 22/176 [00:21<02:19,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.14it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.23it/s]
ravdess val:  13%|█▎        | 23/176 [00:22<02:20,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.82it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.78it/s]
ravdess val:  14%|█▎        | 24/176 [00:23<02:18,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.062', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.02it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 13.98it/s]
ravdess val:  14%|█▍        | 25/176 [00:24<02:18,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  9.92it/s]
{'load_data': '0.076', 'extract_feat': 0.0, 'forward': '0.101', 'batch_size': '1', 'rtf': '0.025'}, : 100%|██████████| 1/1 [00:00<00:00,  9.92it/s]
rtf_avg: 0.025: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
ravdess val:  15%|█▍        | 26/176 [00:25<02:21,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.054', 'extract_feat': 0.0, 'forward': '0.071', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.93it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
ravdess val:  15%|█▌        | 27/176 [00:26<02:23,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.67it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.63it/s]
ravdess val:  16%|█▌        | 28/176 [00:26<02:13,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.064', 'extract_feat': 0.0, 'forward': '0.084', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
ravdess val:  16%|█▋        | 29/176 [00:27<02:16,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.063', 'extract_feat': 0.0, 'forward': '0.082', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
ravdess val:  17%|█▋        | 30/176 [00:28<02:22,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.14it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
ravdess val:  18%|█▊        | 31/176 [00:29<02:21,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.067', 'extract_feat': 0.0, 'forward': '0.083', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
ravdess val:  18%|█▊        | 32/176 [00:30<02:12,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.046', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.69it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
ravdess val:  19%|█▉        | 33/176 [00:31<02:11,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.047', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.53it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.54it/s]
ravdess val:  19%|█▉        | 34/176 [00:32<02:01,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.059', 'extract_feat': 0.0, 'forward': '0.082', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
ravdess val:  20%|█▉        | 35/176 [00:33<01:58,  1.19it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.045', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.92it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]
ravdess val:  20%|██        | 36/176 [00:33<01:51,  1.26it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.054', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.20it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 17.07it/s]
ravdess val:  21%|██        | 37/176 [00:34<01:51,  1.25it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.069', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.24it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
ravdess val:  22%|██▏       | 38/176 [00:35<01:57,  1.18it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.047', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.69it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.75it/s]
ravdess val:  22%|██▏       | 39/176 [00:36<01:59,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.066', 'extract_feat': 0.0, 'forward': '0.081', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
ravdess val:  23%|██▎       | 40/176 [00:37<02:08,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.051', 'extract_feat': 0.0, 'forward': '0.071', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.97it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 13.19it/s]
ravdess val:  23%|██▎       | 41/176 [00:38<02:09,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.060', 'extract_feat': 0.0, 'forward': '0.078', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
ravdess val:  24%|██▍       | 42/176 [00:39<01:58,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.062', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
ravdess val:  24%|██▍       | 43/176 [00:40<02:00,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.77it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 13.62it/s]
ravdess val:  25%|██▌       | 44/176 [00:41<01:55,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.055', 'extract_feat': 0.0, 'forward': '0.084', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
ravdess val:  26%|██▌       | 45/176 [00:42<01:59,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.051', 'extract_feat': 0.0, 'forward': '0.082', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
ravdess val:  26%|██▌       | 46/176 [00:43<01:57,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.063', 'extract_feat': 0.0, 'forward': '0.078', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
ravdess val:  27%|██▋       | 47/176 [00:44<02:06,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.22it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.33it/s]
ravdess val:  27%|██▋       | 48/176 [00:45<02:08,  1.00s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.078', 'extract_feat': 0.0, 'forward': '0.093', 'batch_size': '1', 'rtf': '0.023'}, : 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
rtf_avg: 0.023: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
ravdess val:  28%|██▊       | 49/176 [00:46<02:00,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.068', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.63it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.86it/s]
ravdess val:  28%|██▊       | 50/176 [00:47<02:37,  1.25s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  9.88it/s]
{'load_data': '0.079', 'extract_feat': 0.0, 'forward': '0.101', 'batch_size': '1', 'rtf': '0.025'}, : 100%|██████████| 1/1 [00:00<00:00,  9.88it/s]
rtf_avg: 0.025: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
ravdess val:  29%|██▉       | 51/176 [00:49<02:28,  1.19s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.071', 'extract_feat': 0.0, 'forward': '0.096', 'batch_size': '1', 'rtf': '0.024'}, : 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
rtf_avg: 0.024: 100%|██████████| 1/1 [00:00<00:00,  9.95it/s]
ravdess val:  30%|██▉       | 52/176 [00:50<02:21,  1.14s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.068', 'extract_feat': 0.0, 'forward': '0.086', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
ravdess val:  30%|███       | 53/176 [00:51<02:17,  1.11s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.053', 'extract_feat': 0.0, 'forward': '0.083', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
ravdess val:  31%|███       | 54/176 [00:52<02:10,  1.07s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.055', 'extract_feat': 0.0, 'forward': '0.077', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
ravdess val:  31%|███▏      | 55/176 [00:52<01:59,  1.01it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.052', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 19.14it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 16.39it/s]
ravdess val:  32%|███▏      | 56/176 [00:53<01:54,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.072', 'extract_feat': 0.0, 'forward': '0.096', 'batch_size': '1', 'rtf': '0.024'}, : 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
rtf_avg: 0.024: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
ravdess val:  32%|███▏      | 57/176 [00:54<01:48,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.072', 'extract_feat': 0.0, 'forward': '0.088', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
ravdess val:  33%|███▎      | 58/176 [00:55<01:49,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.060', 'extract_feat': 0.0, 'forward': '0.075', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.66it/s]
ravdess val:  34%|███▎      | 59/176 [00:56<01:48,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.056', 'extract_feat': 0.0, 'forward': '0.078', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
ravdess val:  34%|███▍      | 60/176 [00:57<01:49,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.67it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.83it/s]
ravdess val:  35%|███▍      | 61/176 [00:58<01:49,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.056', 'extract_feat': 0.0, 'forward': '0.078', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
ravdess val:  35%|███▌      | 62/176 [00:59<01:49,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.048', 'extract_feat': 0.0, 'forward': '0.066', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.07it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.28it/s]
ravdess val:  36%|███▌      | 63/176 [01:00<01:39,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.055', 'extract_feat': 0.0, 'forward': '0.074', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.36it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
ravdess val:  36%|███▋      | 64/176 [01:01<01:43,  1.09it/s]

val E2V: (176, 200, 768) HC: (176, 200, 43) mask: (176, 200) y: (176,) errors: 0

ravdess test:   0%|          | 0/176 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.061', 'extract_feat': 0.0, 'forward': '0.084', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
ravdess test:   1%|          | 1/176 [00:00<02:46,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.067', 'extract_feat': 0.0, 'forward': '0.084', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
ravdess test:   1%|          | 2/176 [00:01<02:43,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.052', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 18.83it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 17.49it/s]
ravdess test:   2%|▏         | 3/176 [00:02<02:43,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.49it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.70it/s]
ravdess test:   2%|▏         | 4/176 [00:03<02:46,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.075', 'extract_feat': 0.0, 'forward': '0.096', 'batch_size': '1', 'rtf': '0.024'}, : 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
rtf_avg: 0.024: 100%|██████████| 1/1 [00:00<00:00,  9.94it/s]
ravdess test:   3%|▎         | 5/176 [00:04<02:34,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.048', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.66it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.73it/s]
ravdess test:   3%|▎         | 6/176 [00:05<02:26,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.069', 'extract_feat': 0.0, 'forward': '0.085', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
ravdess test:   4%|▍         | 7/176 [00:06<02:24,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.60it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.68it/s]
ravdess test:   5%|▍         | 8/176 [00:07<02:23,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.67it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.66it/s]
ravdess test:   5%|▌         | 9/176 [00:08<02:29,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.036', 'extract_feat': 0.0, 'forward': '0.066', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.93it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
ravdess test:   6%|▌         | 10/176 [00:09<02:30,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.79it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.74it/s]
ravdess test:   6%|▋         | 11/176 [00:10<02:35,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.034', 'extract_feat': 0.0, 'forward': '0.052', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 19.12it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 16.92it/s]
ravdess test:   7%|▋         | 12/176 [00:10<02:24,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.55it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
ravdess test:   7%|▋         | 13/176 [00:11<02:29,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.12it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.26it/s]
ravdess test:   8%|▊         | 14/176 [00:12<02:39,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.28it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.17it/s]
ravdess test:   9%|▊         | 15/176 [00:13<02:35,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.028', 'extract_feat': 0.0, 'forward': '0.046', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.62it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]
ravdess test:   9%|▉         | 16/176 [00:14<02:31,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.76it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 14.01it/s]
ravdess test:  10%|▉         | 17/176 [00:15<02:24,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.14it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.32it/s]
ravdess test:  10%|█         | 18/176 [00:16<02:15,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.062', 'extract_feat': 0.0, 'forward': '0.082', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
ravdess test:  11%|█         | 19/176 [00:17<02:20,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.065', 'extract_feat': 0.0, 'forward': '0.085', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
ravdess test:  11%|█▏        | 20/176 [00:18<02:31,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.052', 'extract_feat': 0.0, 'forward': '0.069', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.30it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]
ravdess test:  12%|█▏        | 21/176 [00:19<02:20,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.034', 'extract_feat': 0.0, 'forward': '0.054', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 18.39it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 16.86it/s]
ravdess test:  12%|█▎        | 22/176 [00:20<02:19,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.053', 'extract_feat': 0.0, 'forward': '0.076', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
ravdess test:  13%|█▎        | 23/176 [00:21<02:20,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.031', 'extract_feat': 0.0, 'forward': '0.048', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 19.30it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 17.30it/s]
ravdess test:  14%|█▎        | 24/176 [00:21<02:18,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.066', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.00it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.95it/s]
ravdess test:  14%|█▍        | 25/176 [00:22<02:10,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.066', 'extract_feat': 0.0, 'forward': '0.081', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
ravdess test:  15%|█▍        | 26/176 [00:24<02:32,  1.02s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.026', 'extract_feat': 0.0, 'forward': '0.043', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.78it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.55it/s]
ravdess test:  15%|█▌        | 27/176 [00:25<02:29,  1.00s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.15it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.64it/s]
ravdess test:  16%|█▌        | 28/176 [00:25<02:18,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.052', 'extract_feat': 0.0, 'forward': '0.071', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.89it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
ravdess test:  16%|█▋        | 29/176 [00:26<02:17,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.057', 'extract_feat': 0.0, 'forward': '0.074', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
ravdess test:  17%|█▋        | 30/176 [00:27<02:17,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.049', 'extract_feat': 0.0, 'forward': '0.068', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.46it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.72it/s]
ravdess test:  18%|█▊        | 31/176 [00:28<02:07,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.063', 'extract_feat': 0.0, 'forward': '0.084', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
ravdess test:  18%|█▊        | 32/176 [00:29<02:03,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.059', 'extract_feat': 0.0, 'forward': '0.076', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
ravdess test:  19%|█▉        | 33/176 [00:30<02:02,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.080', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
ravdess test:  19%|█▉        | 34/176 [00:30<01:57,  1.20it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.051', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
ravdess test:  20%|█▉        | 35/176 [00:31<02:04,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.35it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.41it/s]
ravdess test:  20%|██        | 36/176 [00:32<02:03,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.062', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.85it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.93it/s]
ravdess test:  21%|██        | 37/176 [00:33<02:05,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.056', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.59it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.52it/s]
ravdess test:  22%|██▏       | 38/176 [00:34<02:05,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.047', 'extract_feat': 0.0, 'forward': '0.068', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.64it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
ravdess test:  22%|██▏       | 39/176 [00:35<01:58,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.079', 'extract_feat': 0.0, 'forward': '0.098', 'batch_size': '1', 'rtf': '0.025'}, : 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
rtf_avg: 0.025: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
ravdess test:  23%|██▎       | 40/176 [00:36<02:00,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.025', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.71it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.86it/s]
ravdess test:  23%|██▎       | 41/176 [00:37<01:50,  1.22it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.52it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 18.92it/s]
ravdess test:  24%|██▍       | 42/176 [00:37<01:55,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.049', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 17.03it/s]
ravdess test:  24%|██▍       | 43/176 [00:38<01:58,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.053', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 18.56it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 16.99it/s]
ravdess test:  25%|██▌       | 44/176 [00:39<01:59,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.048', 'extract_feat': 0.0, 'forward': '0.071', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 14.02it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 13.36it/s]
ravdess test:  26%|██▌       | 45/176 [00:40<01:53,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.062', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.02it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.07it/s]
ravdess test:  26%|██▌       | 46/176 [00:41<01:46,  1.22it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.054', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 18.28it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 15.50it/s]
ravdess test:  27%|██▋       | 47/176 [00:42<01:43,  1.24it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.071', 'extract_feat': 0.0, 'forward': '0.086', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
ravdess test:  27%|██▋       | 48/176 [00:43<01:50,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.060', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
ravdess test:  28%|██▊       | 49/176 [00:44<01:54,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.054', 'extract_feat': 0.0, 'forward': '0.075', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.11it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
ravdess test:  28%|██▊       | 50/176 [00:45<01:55,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.79it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.58it/s]
ravdess test:  29%|██▉       | 51/176 [00:45<01:55,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.031', 'extract_feat': 0.0, 'forward': '0.056', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.64it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.67it/s]
ravdess test:  30%|██▉       | 52/176 [00:46<01:55,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.89it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.52it/s]
ravdess test:  30%|███       | 53/176 [00:47<01:55,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.049', 'extract_feat': 0.0, 'forward': '0.070', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.20it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
ravdess test:  31%|███       | 54/176 [00:48<01:54,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.058', 'extract_feat': 0.0, 'forward': '0.073', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.52it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
ravdess test:  31%|███▏      | 55/176 [00:49<01:47,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.026', 'extract_feat': 0.0, 'forward': '0.044', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.55it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 18.59it/s]
ravdess test:  32%|███▏      | 56/176 [00:50<01:50,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.46it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.55it/s]
ravdess test:  32%|███▏      | 57/176 [00:51<01:41,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.047', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.46it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
ravdess test:  33%|███▎      | 58/176 [00:52<01:44,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  9.96it/s]
{'load_data': '0.079', 'extract_feat': 0.0, 'forward': '0.100', 'batch_size': '1', 'rtf': '0.025'}, : 100%|██████████| 1/1 [00:00<00:00,  9.96it/s]
rtf_avg: 0.025: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
ravdess test:  34%|███▎      | 59/176 [00:53<01:51,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.049', 'extract_feat': 0.0, 'forward': '0.074', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.35it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
ravdess test:  34%|███▍      | 60/176 [00:54<01:50,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.051', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 19.28it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 18.02it/s]
ravdess test:  35%|███▍      | 61/176 [00:55<01:42,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.074', 'extract_feat': 0.0, 'forward': '0.089', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
ravdess test:  35%|███▌      | 62/176 [00:56<01:45,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.060', 'extract_feat': 0.0, 'forward': '0.087', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
ravdess test:  36%|███▌      | 63/176 [00:57<01:49,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.15it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.33it/s]
ravdess test:  36%|███▋      | 64/176 [00:58<01:47,  1.04it/s]

test E2V: (176, 200, 768) HC: (176, 200, 43) mask: (176, 200) y: (176,) errors: 0
Saved: /content/drive/MyDrive/New Jurnal Cross/processed_intra_sequence_features_plus_base/ravdess
Errors: 0
==========================================================================================
Processing sequence features: RESD
==========================================================================================
Rows: 1198
Speakers: 50

emotion  angry  disgust  fear  happy  neutral  sad
split
test        34       15    29     23       20   18
train      154      135   162    160      140  122
val         31       35    32     35       31   22

resd train:   0%|          | 0/873 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.91it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.99it/s]
resd train:   0%|          | 1/873 [00:02<32:59,  2.27s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.062', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.86it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 15.01it/s]
resd train:   0%|          | 2/873 [00:03<21:32,  1.48s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.21it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.18it/s]
resd train:   0%|          | 3/873 [00:04<18:20,  1.26s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.062', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.90it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.97it/s]
resd train:   0%|          | 4/873 [00:05<17:34,  1.21s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.080', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
resd train:   1%|          | 5/873 [00:06<16:57,  1.17s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.060', 'extract_feat': 0.0, 'forward': '0.076', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
resd train:   1%|          | 6/873 [00:07<17:09,  1.19s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.065', 'extract_feat': 0.0, 'forward': '0.083', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
resd train:   1%|          | 7/873 [00:08<15:07,  1.05s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.027', 'extract_feat': 0.0, 'forward': '0.045', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.73it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]
resd train:   1%|          | 8/873 [00:09<13:26,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.070', 'extract_feat': 0.0, 'forward': '0.089', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
resd train:   1%|          | 9/873 [00:09<12:39,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.050', 'extract_feat': 0.0, 'forward': '0.066', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.00it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.16it/s]
resd train:   1%|          | 10/873 [00:10<13:24,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.047', 'extract_feat': 0.0, 'forward': '0.068', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.53it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.50it/s]
resd train:   1%|▏         | 11/873 [00:11<12:33,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.048', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.54it/s]
resd train:   1%|▏         | 12/873 [00:12<13:07,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.031', 'extract_feat': 0.0, 'forward': '0.048', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.37it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 17.54it/s]
resd train:   1%|▏         | 13/873 [00:13<12:18,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.54it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.50it/s]
resd train:   2%|▏         | 14/873 [00:14<13:05,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.043', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.11it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 21.22it/s]
resd train:   2%|▏         | 15/873 [00:15<12:13,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 15.35it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.49it/s]
resd train:   2%|▏         | 16/873 [00:16<12:48,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 19.05it/s]
resd train:   2%|▏         | 17/873 [00:17<12:39,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.055', 'extract_feat': 0.0, 'forward': '0.071', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 14.04it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
resd train:   2%|▏         | 18/873 [00:18<13:04,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.082', 'extract_feat': 0.0, 'forward': '0.100', 'batch_size': '1', 'rtf': '0.025'}, : 100%|██████████| 1/1 [00:00<00:00,  9.97it/s]
rtf_avg: 0.025: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
resd train:   2%|▏         | 19/873 [00:18<13:15,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.061', 'extract_feat': 0.0, 'forward': '0.086', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
resd train:   2%|▏         | 20/873 [00:19<12:28,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.058', 'extract_feat': 0.0, 'forward': '0.083', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
resd train:   2%|▏         | 21/873 [00:20<12:51,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.063', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
resd train:   3%|▎         | 22/873 [00:21<12:38,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.08it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.17it/s]
resd train:   3%|▎         | 23/873 [00:22<13:04,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.031', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.08it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.85it/s]
resd train:   3%|▎         | 24/873 [00:23<12:58,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.052', 'extract_feat': 0.0, 'forward': '0.083', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
resd train:   3%|▎         | 25/873 [00:24<13:26,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.070', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.17it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
resd train:   3%|▎         | 26/873 [00:25<13:16,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.066', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 14.99it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]
resd train:   3%|▎         | 27/873 [00:26<13:20,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.68it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.59it/s]
resd train:   3%|▎         | 28/873 [00:27<14:45,  1.05s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.073', 'extract_feat': 0.0, 'forward': '0.092', 'batch_size': '1', 'rtf': '0.023'}, : 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
rtf_avg: 0.023: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
resd train:   3%|▎         | 29/873 [00:28<14:28,  1.03s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.033', 'extract_feat': 0.0, 'forward': '0.056', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.56it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 14.48it/s]
resd train:   3%|▎         | 30/873 [00:29<13:25,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.067', 'extract_feat': 0.0, 'forward': '0.095', 'batch_size': '1', 'rtf': '0.024'}, : 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
rtf_avg: 0.024: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
resd train:   4%|▎         | 31/873 [00:30<13:54,  1.01it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.047', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.38it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.60it/s]
resd train:   4%|▎         | 32/873 [00:31<13:43,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.067', 'extract_feat': 0.0, 'forward': '0.085', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
resd train:   4%|▍         | 33/873 [00:32<13:17,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.056', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.61it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.50it/s]
resd train:   4%|▍         | 34/873 [00:35<21:54,  1.57s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.41it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
resd train:   4%|▍         | 35/873 [00:36<19:44,  1.41s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.058', 'extract_feat': 0.0, 'forward': '0.088', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
resd train:   4%|▍         | 36/873 [00:37<16:50,  1.21s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.025', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 16.72it/s]
resd train:   4%|▍         | 37/873 [00:37<14:55,  1.07s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.030', 'extract_feat': 0.0, 'forward': '0.049', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.32it/s]
resd train:   4%|▍         | 38/873 [00:38<14:13,  1.02s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 15.97it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.13it/s]
resd train:   4%|▍         | 39/873 [00:39<13:52,  1.00it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.87it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.85it/s]
resd train:   5%|▍         | 40/873 [00:40<13:27,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.020', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 20.42it/s]
resd train:   5%|▍         | 41/873 [00:41<13:15,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.058', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
resd train:   5%|▍         | 42/873 [00:42<13:15,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.070', 'extract_feat': 0.0, 'forward': '0.087', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
resd train:   5%|▍         | 43/873 [00:43<13:01,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.12it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.59it/s]
resd train:   5%|▌         | 44/873 [00:44<12:58,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.043', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.96it/s]
resd train:   5%|▌         | 45/873 [00:45<12:25,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.062', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.89it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.79it/s]
resd train:   5%|▌         | 46/873 [00:46<12:33,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.054', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 18.46it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 17.28it/s]
resd train:   5%|▌         | 47/873 [00:46<12:13,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.064', 'extract_feat': 0.0, 'forward': '0.085', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
resd train:   5%|▌         | 48/873 [00:47<12:42,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.18it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.14it/s]
resd train:   6%|▌         | 49/873 [00:48<12:18,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.068', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.55it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.76it/s]
resd train:   6%|▌         | 50/873 [00:49<12:40,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.054', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.17it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.97it/s]
resd train:   6%|▌         | 51/873 [00:50<12:48,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.054', 'extract_feat': 0.0, 'forward': '0.075', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.11it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
resd train:   6%|▌         | 52/873 [00:51<12:13,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.050', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.38it/s]
resd train:   6%|▌         | 53/873 [00:52<12:43,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.056', 'extract_feat': 0.0, 'forward': '0.074', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
resd train:   6%|▌         | 54/873 [00:53<12:01,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.18it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.23it/s]
resd train:   6%|▋         | 55/873 [00:54<12:34,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.81it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.81it/s]
resd train:   6%|▋         | 56/873 [00:55<12:10,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.18it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
resd train:   7%|▋         | 57/873 [00:56<12:40,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.050', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
resd train:   7%|▋         | 58/873 [00:56<11:44,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.053', 'extract_feat': 0.0, 'forward': '0.070', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 14.07it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
resd train:   7%|▋         | 59/873 [00:57<11:28,  1.18it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.063', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
resd train:   7%|▋         | 60/873 [00:58<12:05,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.24it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.74it/s]
resd train:   7%|▋         | 61/873 [01:00<14:32,  1.08s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.049', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.41it/s]
resd train:   7%|▋         | 62/873 [01:01<13:58,  1.03s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.032', 'extract_feat': 0.0, 'forward': '0.051', 'batch_size': '1', 'rtf': '0.013'}, : 100%|██████████| 1/1 [00:00<00:00, 19.24it/s]
rtf_avg: 0.013: 100%|██████████| 1/1 [00:00<00:00, 17.58it/s]
resd train:   7%|▋         | 63/873 [01:02<13:46,  1.02s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.45it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.36it/s]
resd train:   7%|▋         | 64/873 [01:03<13:25,  1.00it/s]
  0%|          | 0/1 [00:00<?, ?it/s]

train E2V: (873, 200, 768) HC: (873, 200, 43) mask: (873, 200) y: (873,) errors: 0

resd val:   0%|          | 0/186 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.069', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.27it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
resd val:   1%|          | 1/186 [00:00<02:49,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.069', 'extract_feat': 0.0, 'forward': '0.093', 'batch_size': '1', 'rtf': '0.023'}, : 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
rtf_avg: 0.023: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
resd val:   1%|          | 2/186 [00:01<02:29,  1.23it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.048', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 18.46it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 14.95it/s]
resd val:   2%|▏         | 3/186 [00:02<02:21,  1.29it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.36it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.82it/s]
resd val:   2%|▏         | 4/186 [00:03<02:29,  1.22it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.067', 'extract_feat': 0.0, 'forward': '0.093', 'batch_size': '1', 'rtf': '0.023'}, : 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
rtf_avg: 0.023: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
resd val:   3%|▎         | 5/186 [00:04<02:22,  1.27it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.026', 'extract_feat': 0.0, 'forward': '0.043', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.95it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.59it/s]
resd val:   3%|▎         | 6/186 [00:04<02:32,  1.18it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.35it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.44it/s]
resd val:   4%|▍         | 7/186 [00:05<02:40,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.063', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
resd val:   4%|▍         | 8/186 [00:06<02:44,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.075', 'extract_feat': 0.0, 'forward': '0.093', 'batch_size': '1', 'rtf': '0.023'}, : 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
rtf_avg: 0.023: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
resd val:   5%|▍         | 9/186 [00:07<02:37,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.31it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.48it/s]
resd val:   5%|▌         | 10/186 [00:08<02:30,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.057', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.25it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 13.93it/s]
resd val:   6%|▌         | 11/186 [00:09<02:21,  1.23it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.063', 'extract_feat': 0.0, 'forward': '0.081', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
resd val:   6%|▋         | 12/186 [00:09<02:16,  1.28it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.049', 'extract_feat': 0.0, 'forward': '0.087', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
resd val:   7%|▋         | 13/186 [00:10<02:15,  1.28it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
resd val:   8%|▊         | 14/186 [00:11<02:13,  1.29it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 14.50it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
resd val:   8%|▊         | 15/186 [00:12<02:21,  1.21it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.066', 'extract_feat': 0.0, 'forward': '0.092', 'batch_size': '1', 'rtf': '0.023'}, : 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
rtf_avg: 0.023: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
resd val:   9%|▊         | 16/186 [00:13<02:25,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.027', 'extract_feat': 0.0, 'forward': '0.045', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.98it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]
resd val:   9%|▉         | 17/186 [00:14<02:15,  1.25it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.31it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.47it/s]
resd val:  10%|▉         | 18/186 [00:14<02:09,  1.30it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.81it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
resd val:  10%|█         | 19/186 [00:15<02:09,  1.29it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.063', 'extract_feat': 0.0, 'forward': '0.083', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
resd val:  11%|█         | 20/186 [00:16<02:09,  1.28it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.054', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.15it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 15.51it/s]
resd val:  11%|█▏        | 21/186 [00:17<02:07,  1.29it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.41it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.00it/s]
resd val:  12%|█▏        | 22/186 [00:17<02:13,  1.23it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.073', 'extract_feat': 0.0, 'forward': '0.089', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
resd val:  12%|█▏        | 23/186 [00:18<02:11,  1.24it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.075', 'extract_feat': 0.0, 'forward': '0.091', 'batch_size': '1', 'rtf': '0.023'}, : 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
rtf_avg: 0.023: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
resd val:  13%|█▎        | 24/186 [00:19<02:18,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.075', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
resd val:  13%|█▎        | 25/186 [00:20<02:22,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.97it/s]
resd val:  14%|█▍        | 26/186 [00:21<02:12,  1.21it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.070', 'extract_feat': 0.0, 'forward': '0.090', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
resd val:  15%|█▍        | 27/186 [00:22<02:17,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.062', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
resd val:  15%|█▌        | 28/186 [00:23<02:19,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.38it/s]
resd val:  16%|█▌        | 29/186 [00:24<02:30,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.049', 'extract_feat': 0.0, 'forward': '0.070', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.20it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
resd val:  16%|█▌        | 30/186 [00:25<02:20,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.68it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
resd val:  17%|█▋        | 31/186 [00:26<02:23,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.047', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 21.04it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 17.88it/s]
resd val:  17%|█▋        | 32/186 [00:26<02:13,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.068', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.45it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]
resd val:  18%|█▊        | 33/186 [00:27<02:15,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.047', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.78it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.78it/s]
resd val:  18%|█▊        | 34/186 [00:28<02:15,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.049', 'extract_feat': 0.0, 'forward': '0.070', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
resd val:  19%|█▉        | 35/186 [00:29<02:22,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.79it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.34it/s]
resd val:  19%|█▉        | 36/186 [00:30<02:20,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.066', 'extract_feat': 0.0, 'forward': '0.082', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
resd val:  20%|█▉        | 37/186 [00:31<02:22,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.075', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.17it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
resd val:  20%|██        | 38/186 [00:32<02:22,  1.04it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.054', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
resd val:  21%|██        | 39/186 [00:33<02:24,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.067', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.82it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.26it/s]
resd val:  22%|██▏       | 40/186 [00:34<02:24,  1.01it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.032', 'extract_feat': 0.0, 'forward': '0.049', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.56it/s]
resd val:  22%|██▏       | 41/186 [00:35<02:23,  1.01it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.20it/s]
resd val:  23%|██▎       | 42/186 [00:36<02:17,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.63it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.64it/s]
resd val:  23%|██▎       | 43/186 [00:37<02:15,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.049', 'extract_feat': 0.0, 'forward': '0.075', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 13.23it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
resd val:  24%|██▎       | 44/186 [00:38<02:13,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.021', 'extract_feat': 0.0, 'forward': '0.038', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.58it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.68it/s]
resd val:  24%|██▍       | 45/186 [00:39<02:11,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 18.10it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.99it/s]
resd val:  25%|██▍       | 46/186 [00:40<02:12,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.38it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]
resd val:  25%|██▌       | 47/186 [00:41<02:11,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.053', 'extract_feat': 0.0, 'forward': '0.082', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
resd val:  26%|██▌       | 48/186 [00:42<02:09,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.055', 'extract_feat': 0.0, 'forward': '0.080', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
resd val:  26%|██▋       | 49/186 [00:43<02:09,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.052', 'extract_feat': 0.0, 'forward': '0.081', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
resd val:  27%|██▋       | 50/186 [00:44<02:08,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.078', 'extract_feat': 0.0, 'forward': '0.094', 'batch_size': '1', 'rtf': '0.024'}, : 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
rtf_avg: 0.024: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
resd val:  27%|██▋       | 51/186 [00:45<02:07,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.063', 'extract_feat': 0.0, 'forward': '0.081', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
resd val:  28%|██▊       | 52/186 [00:46<02:10,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.07it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.07it/s]
resd val:  28%|██▊       | 53/186 [00:46<02:04,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.056', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.75it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.56it/s]
resd val:  29%|██▉       | 54/186 [00:47<02:01,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.42it/s]
resd val:  30%|██▉       | 55/186 [00:48<02:01,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 15.99it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.32it/s]
resd val:  30%|███       | 56/186 [00:49<01:59,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.30it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 21.18it/s]
resd val:  31%|███       | 57/186 [00:50<01:59,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.021', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.20it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.94it/s]
resd val:  31%|███       | 58/186 [00:51<02:07,  1.01it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.056', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
resd val:  32%|███▏      | 59/186 [00:52<02:07,  1.00s/it]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.024', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 21.25it/s]
resd val:  32%|███▏      | 60/186 [00:53<02:02,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.047', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 20.92it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 19.23it/s]
resd val:  33%|███▎      | 61/186 [00:54<02:01,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.82it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 16.61it/s]
resd val:  33%|███▎      | 62/186 [00:55<01:52,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.035', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.81it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.48it/s]
resd val:  34%|███▍      | 63/186 [00:56<01:53,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.076', 'extract_feat': 0.0, 'forward': '0.094', 'batch_size': '1', 'rtf': '0.024'}, : 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
rtf_avg: 0.024: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
resd val:  34%|███▍      | 64/186 [00:57<01:56,  1.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.072', 'extract_feat': 0.0, 'forward': '0.089', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
resd val:  35%|███▍      | 65/186 [00:58<02:01,  1.00s/it]

val E2V: (186, 200, 768) HC: (186, 200, 43) mask: (186, 200) y: (186,) errors: 0

resd test:   0%|          | 0/139 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.065', 'extract_feat': 0.0, 'forward': '0.084', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
resd test:   1%|          | 1/139 [00:00<02:14,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.066', 'extract_feat': 0.0, 'forward': '0.086', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
resd test:   1%|▏         | 2/139 [00:01<01:57,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.075', 'extract_feat': 0.0, 'forward': '0.096', 'batch_size': '1', 'rtf': '0.024'}, : 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
rtf_avg: 0.024: 100%|██████████| 1/1 [00:00<00:00,  9.93it/s]
resd test:   2%|▏         | 3/139 [00:02<02:01,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.30it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.39it/s]
resd test:   3%|▎         | 4/139 [00:03<02:05,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.068', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.35it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]
resd test:   4%|▎         | 5/139 [00:04<02:02,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.066', 'extract_feat': 0.0, 'forward': '0.094', 'batch_size': '1', 'rtf': '0.024'}, : 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
rtf_avg: 0.024: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
resd test:   4%|▍         | 6/139 [00:05<01:53,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.54it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.50it/s]
resd test:   5%|▌         | 7/139 [00:06<01:46,  1.24it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.066', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.05it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
resd test:   6%|▌         | 8/139 [00:06<01:45,  1.24it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.068', 'extract_feat': 0.0, 'forward': '0.091', 'batch_size': '1', 'rtf': '0.023'}, : 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
rtf_avg: 0.023: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
resd test:   6%|▋         | 9/139 [00:07<01:50,  1.18it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.062', 'extract_feat': 0.0, 'forward': '0.087', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
resd test:   7%|▋         | 10/139 [00:08<01:51,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.063', 'extract_feat': 0.0, 'forward': '0.084', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
resd test:   8%|▊         | 11/139 [00:09<01:55,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.062', 'extract_feat': 0.0, 'forward': '0.088', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
resd test:   9%|▊         | 12/139 [00:10<01:46,  1.19it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.050', 'extract_feat': 0.0, 'forward': '0.072', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.82it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
resd test:   9%|▉         | 13/139 [00:11<01:51,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.080', 'extract_feat': 0.0, 'forward': '0.095', 'batch_size': '1', 'rtf': '0.024'}, : 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
rtf_avg: 0.024: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
resd test:  10%|█         | 14/139 [00:12<01:46,  1.17it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.059', 'extract_feat': 0.0, 'forward': '0.078', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.78it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
resd test:  11%|█         | 15/139 [00:13<01:49,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.74it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.87it/s]
resd test:  12%|█▏        | 16/139 [00:14<01:51,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
{'load_data': '0.085', 'extract_feat': 0.0, 'forward': '0.100', 'batch_size': '1', 'rtf': '0.025'}, : 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
rtf_avg: 0.025: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
resd test:  12%|█▏        | 17/139 [00:14<01:48,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.026', 'extract_feat': 0.0, 'forward': '0.044', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.51it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.27it/s]
resd test:  13%|█▎        | 18/139 [00:15<01:46,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.53it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 22.41it/s]
resd test:  14%|█▎        | 19/139 [00:16<01:38,  1.22it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.078', 'extract_feat': 0.0, 'forward': '0.095', 'batch_size': '1', 'rtf': '0.024'}, : 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
rtf_avg: 0.024: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
resd test:  14%|█▍        | 20/139 [00:17<01:42,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.059', 'extract_feat': 0.0, 'forward': '0.078', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
resd test:  15%|█▌        | 21/139 [00:18<01:45,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.062', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 15.96it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
resd test:  16%|█▌        | 22/139 [00:19<01:38,  1.19it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.068', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.55it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.80it/s]
resd test:  17%|█▋        | 23/139 [00:19<01:40,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.038', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.87it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.66it/s]
resd test:  17%|█▋        | 24/139 [00:20<01:43,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.053', 'extract_feat': 0.0, 'forward': '0.084', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
resd test:  18%|█▊        | 25/139 [00:21<01:38,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.039', 'extract_feat': 0.0, 'forward': '0.059', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.69it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.65it/s]
resd test:  19%|█▊        | 26/139 [00:22<01:34,  1.20it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.046', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.45it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.47it/s]
resd test:  19%|█▉        | 27/139 [00:23<01:42,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.077', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
resd test:  20%|██        | 28/139 [00:24<01:38,  1.13it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.071', 'extract_feat': 0.0, 'forward': '0.090', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
resd test:  21%|██        | 29/139 [00:25<01:44,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.069', 'extract_feat': 0.0, 'forward': '0.086', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
resd test:  22%|██▏       | 30/139 [00:26<01:37,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.047', 'extract_feat': 0.0, 'forward': '0.070', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.10it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]
resd test:  22%|██▏       | 31/139 [00:27<01:34,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.033', 'extract_feat': 0.0, 'forward': '0.055', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.87it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 15.72it/s]
resd test:  23%|██▎       | 32/139 [00:28<01:36,  1.11it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.040', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.04it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 17.58it/s]
resd test:  24%|██▎       | 33/139 [00:28<01:31,  1.15it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.020', 'extract_feat': 0.0, 'forward': '0.038', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 25.70it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 23.45it/s]
resd test:  24%|██▍       | 34/139 [00:29<01:26,  1.21it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.025', 'extract_feat': 0.0, 'forward': '0.043', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 23.09it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 21.17it/s]
resd test:  25%|██▌       | 35/139 [00:30<01:27,  1.19it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.048', 'extract_feat': 0.0, 'forward': '0.069', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.35it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
resd test:  26%|██▌       | 36/139 [00:31<01:30,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.037', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.22it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.38it/s]
resd test:  27%|██▋       | 37/139 [00:32<01:31,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.036', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.13it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.32it/s]
resd test:  27%|██▋       | 38/139 [00:33<01:33,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.041', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.17it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 14.94it/s]
resd test:  28%|██▊       | 39/139 [00:34<01:27,  1.14it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.027', 'extract_feat': 0.0, 'forward': '0.045', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 21.69it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 19.06it/s]
resd test:  29%|██▉       | 40/139 [00:35<01:30,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.041', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 20.38it/s]
resd test:  29%|██▉       | 41/139 [00:36<01:29,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.061', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.06it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.11it/s]
resd test:  30%|███       | 42/139 [00:37<01:29,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.043', 'extract_feat': 0.0, 'forward': '0.058', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.05it/s]
rtf_avg: 0.014: 100%|██████████| 1/1 [00:00<00:00, 15.98it/s]
resd test:  31%|███       | 43/139 [00:37<01:30,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.060', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
resd test:  32%|███▏      | 44/139 [00:38<01:24,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.040', 'extract_feat': 0.0, 'forward': '0.072', 'batch_size': '1', 'rtf': '0.018'}, : 100%|██████████| 1/1 [00:00<00:00, 13.71it/s]
rtf_avg: 0.018: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
resd test:  32%|███▏      | 45/139 [00:39<01:21,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.029', 'extract_feat': 0.0, 'forward': '0.050', 'batch_size': '1', 'rtf': '0.012'}, : 100%|██████████| 1/1 [00:00<00:00, 19.76it/s]
rtf_avg: 0.012: 100%|██████████| 1/1 [00:00<00:00, 18.29it/s]
resd test:  33%|███▎      | 46/139 [00:40<01:22,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.043', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.77it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.89it/s]
resd test:  34%|███▍      | 47/139 [00:41<01:22,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.026', 'extract_feat': 0.0, 'forward': '0.043', 'batch_size': '1', 'rtf': '0.011'}, : 100%|██████████| 1/1 [00:00<00:00, 22.69it/s]
rtf_avg: 0.011: 100%|██████████| 1/1 [00:00<00:00, 20.46it/s]
resd test:  35%|███▍      | 48/139 [00:42<01:22,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.060', 'batch_size': '1', 'rtf': '0.015'}, : 100%|██████████| 1/1 [00:00<00:00, 16.38it/s]
rtf_avg: 0.015: 100%|██████████| 1/1 [00:00<00:00, 15.33it/s]
resd test:  35%|███▌      | 49/139 [00:43<01:27,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.054', 'extract_feat': 0.0, 'forward': '0.078', 'batch_size': '1', 'rtf': '0.019'}, : 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
rtf_avg: 0.019: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
resd test:  36%|███▌      | 50/139 [00:44<01:26,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.064', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.54it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.64it/s]
resd test:  37%|███▋      | 51/139 [00:45<01:26,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.042', 'extract_feat': 0.0, 'forward': '0.066', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 14.79it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.91it/s]
resd test:  37%|███▋      | 52/139 [00:46<01:26,  1.01it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.069', 'extract_feat': 0.0, 'forward': '0.090', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
resd test:  38%|███▊      | 53/139 [00:47<01:24,  1.01it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.063', 'extract_feat': 0.0, 'forward': '0.088', 'batch_size': '1', 'rtf': '0.022'}, : 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
rtf_avg: 0.022: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
resd test:  39%|███▉      | 54/139 [00:48<01:22,  1.02it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.069', 'batch_size': '1', 'rtf': '0.017'}, : 100%|██████████| 1/1 [00:00<00:00, 14.25it/s]
rtf_avg: 0.017: 100%|██████████| 1/1 [00:00<00:00, 13.23it/s]
resd test:  40%|███▉      | 55/139 [00:49<01:21,  1.03it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.045', 'extract_feat': 0.0, 'forward': '0.065', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.31it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
resd test:  40%|████      | 56/139 [00:50<01:18,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.065', 'extract_feat': 0.0, 'forward': '0.090', 'batch_size': '1', 'rtf': '0.023'}, : 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
rtf_avg: 0.023: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
resd test:  41%|████      | 57/139 [00:51<01:17,  1.06it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.066', 'extract_feat': 0.0, 'forward': '0.083', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
resd test:  42%|████▏     | 58/139 [00:51<01:13,  1.10it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.068', 'extract_feat': 0.0, 'forward': '0.084', 'batch_size': '1', 'rtf': '0.021'}, : 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
rtf_avg: 0.021: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
resd test:  42%|████▏     | 59/139 [00:52<01:14,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.022', 'extract_feat': 0.0, 'forward': '0.039', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 24.89it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.14it/s]
resd test:  43%|████▎     | 60/139 [00:53<01:13,  1.07it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.023', 'extract_feat': 0.0, 'forward': '0.042', 'batch_size': '1', 'rtf': '0.010'}, : 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]
rtf_avg: 0.010: 100%|██████████| 1/1 [00:00<00:00, 21.36it/s]
resd test:  44%|████▍     | 61/139 [00:54<01:11,  1.09it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.061', 'extract_feat': 0.0, 'forward': '0.079', 'batch_size': '1', 'rtf': '0.020'}, : 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
rtf_avg: 0.020: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
resd test:  45%|████▍     | 62/139 [00:55<01:11,  1.08it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.044', 'extract_feat': 0.0, 'forward': '0.063', 'batch_size': '1', 'rtf': '0.016'}, : 100%|██████████| 1/1 [00:00<00:00, 15.73it/s]
rtf_avg: 0.016: 100%|██████████| 1/1 [00:00<00:00, 14.86it/s]
resd test:  45%|████▌     | 63/139 [00:56<01:05,  1.16it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.073', 'extract_feat': 0.0, 'forward': '0.092', 'batch_size': '1', 'rtf': '0.023'}, : 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
rtf_avg: 0.023: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
resd test:  46%|████▌     | 64/139 [00:57<01:06,  1.12it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
{'load_data': '0.034', 'extract_feat': 0.0, 'forward': '0.056', 'batch_size': '1', 'rtf': '0.014'}, : 100%|██████████| 1/1 [00:00<00:00, 17.68it/s]

test E2V: (139, 200, 768) HC: (139, 200, 43) mask: (139, 200) y: (139,) errors: 0
Saved: /content/drive/MyDrive/New Jurnal Cross/processed_intra_sequence_features_plus_base/resd
Errors: 0

   dataset  e2v_shape_train  hc_shape_train  n_errors
0    emodb  (498, 200, 768)  (498, 200, 43)         0
1  ravdess  (704, 200, 768)  (704, 200, 43)         0
2     resd  (873, 200, 768)  (873, 200, 43)         0

Saved: /content/drive/MyDrive/New Jurnal Cross/processed_intra_sequence_features_plus_base/sequence_extraction_summary.csv

In [14]:
for dataset_name in DATASETS:
    ds_dir = OUT_DIR / dataset_name

    print("=" * 80)
    print(dataset_name.upper())

    for split in ["train", "val", "test"]:
        X_e2v = np.load(ds_dir / f"X_e2v_seq_{split}.npy")
        X_hc = np.load(ds_dir / f"X_hc_seq_{split}.npy")
        mask = np.load(ds_dir / f"mask_{split}.npy")
        y = np.load(ds_dir / f"y_{split}.npy")

        print(
            split,
            "E2V:", X_e2v.shape,
            "HC:", X_hc.shape,
            "mask:", mask.shape,
            "y:", y.shape,
            "NaN E2V:", np.isnan(X_e2v).any(),
            "NaN HC:", np.isnan(X_hc).any()
        )

================================================================================
EMODB
train E2V: (498, 200, 768) HC: (498, 200, 43) mask: (498, 200) y: (498,) NaN E2V: False NaN HC: False
val E2V: (71, 200, 768) HC: (71, 200, 43) mask: (71, 200) y: (71,) NaN E2V: False NaN HC: False
test E2V: (149, 200, 768) HC: (149, 200, 43) mask: (149, 200) y: (149,) NaN E2V: False NaN HC: False
================================================================================
RAVDESS
train E2V: (704, 200, 768) HC: (704, 200, 43) mask: (704, 200) y: (704,) NaN E2V: False NaN HC: False
val E2V: (176, 200, 768) HC: (176, 200, 43) mask: (176, 200) y: (176,) NaN E2V: False NaN HC: False
test E2V: (176, 200, 768) HC: (176, 200, 43) mask: (176, 200) y: (176,) NaN E2V: False NaN HC: False
================================================================================
RESD
train E2V: (873, 200, 768) HC: (873, 200, 43) mask: (873, 200) y: (873,) NaN E2V: False NaN HC: False
val E2V: (186, 200, 768) HC: (186, 200, 43) mask: (186, 200) y: (186,) NaN E2V: False NaN HC: False
test E2V: (139, 200, 768) HC: (139, 200, 43) mask: (139, 200) y: (139,) NaN E2V: False NaN HC: False

In [15]:
# ============================================================
# SHA256 manifest for generated sequence feature files
# ============================================================
sequence_feature_manifest_rows = []

for path in sorted(OUT_DIR.rglob("*")):
    if path.is_file() and path.suffix.lower() in [".npy", ".csv", ".json", ".pkl"]:
        if path.name == "generated_sequence_feature_file_manifest_sha256.csv":
            continue

        sequence_feature_manifest_rows.append({
            "relative_path": str(path.relative_to(OUT_DIR)),
            "absolute_path": str(path),
            "size_bytes": path.stat().st_size,
            "sha256": sha256_of_file(path),
        })

sequence_feature_manifest = pd.DataFrame(sequence_feature_manifest_rows)
sequence_feature_manifest.to_csv(
    OUT_DIR / "generated_sequence_feature_file_manifest_sha256.csv",
    index=False
)

display(sequence_feature_manifest.head())
print("Saved:", OUT_DIR / "generated_sequence_feature_file_manifest_sha256.csv")
print("Number of files hashed:", len(sequence_feature_manifest))

,relative_path,absolute_path,size_bytes,sha256
0,emodb/X_e2v_seq_test.npy,/content/drive/MyDrive/New Jurnal Cross/proces...,91545728,e4f2d821e110ecbea46d670ca7ddfe653b94cb00f512fd...
1,emodb/X_e2v_seq_train.npy,/content/drive/MyDrive/New Jurnal Cross/proces...,305971328,008010ade43f83a69de18d086514537322f810a341a2f0...
2,emodb/X_e2v_seq_val.npy,/content/drive/MyDrive/New Jurnal Cross/proces...,43622528,17e56db66e550d1d9c971c418a4edb7c84ec925d7c95e3...
3,emodb/X_hc_seq_test.npy,/content/drive/MyDrive/New Jurnal Cross/proces...,5125728,666abf5ed8b746f4ff6bbc654249e4a96daa9d9dc9cdbc...
4,emodb/X_hc_seq_train.npy,/content/drive/MyDrive/New Jurnal Cross/proces...,17131328,c25685dd2fc7ba9dfb2358d510c6790c3f96dc6955e97b...

Saved: /content/drive/MyDrive/New Jurnal Cross/processed_intra_sequence_features_plus_base/generated_sequence_feature_file_manifest_sha256.csv
Number of files hashed: 59